### ISSUE TITLE
JavaScript: different behaviour for deep expression operator between using `pattern-inside` and `pattern`

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#1006]
I notice different behaviour for deep expression operator between using it with `pattern-inside` and `pattern`

link: https://semgrep.live/4bDL
while trying to track function argument parameter inside function
example code:

```javascript
function test (foo, bar) {
    var smth = foo.something
    console.log(smth)
}
```

if using `pattern-inside` function it does not work:

```yaml
  patterns:
    - pattern-inside: function $F ($FOO,...) {...}
    - pattern: $X = <... $FOO ...>;
```

but using just `pattern` with function inside of it works:
```yaml
    - pattern: |
        function $F ($FOO,...) {
          ...
          $X = <... $FOO ...>;
          ...
        }
```

as a user would expect behaviour to be the same

**Comment by mschwager** [comment]
This broke because of recent metavariable matching changes. Prior to #947, metavariable matching was broken due to always using the string literal `"md5sum"` instead of grabbing the `md5sum` value from a `dict`: https://github.com/returntocorp/semgrep/pull/947/files#diff-dcf44252140037801168b8192c45e95cR40. After this change metavariable matching logic started working correctly. The issue here is a mismatch between using a metavariable's `sid` and `md5sum`.

For example, using the following configuration we get these results from `semgrep-core`:

```yaml
patterns:
  - pattern: $X = $FOO;
  - pattern-inside: |
      function $F ($FOO, ...) {
        ...
      }
```

```
ipdb> pp outputs                                                                                                                                                                                                   
[<PatternMatch id=.1 range=<Range start=9 end=76 vars={'$FOO': 1, '$F': '120d21832e03b3e020c7eb9472860421'}>>,
 <PatternMatch id=.1 range=<Range start=9 end=76 vars={'$FOO': 1, '$F': '120d21832e03b3e020c7eb9472860421'}>>,
 <PatternMatch id=.1 range=<Range start=9 end=76 vars={'$FOO': 1, '$F': '120d21832e03b3e020c7eb9472860421'}>>,
 <PatternMatch id=.0 range=<Range start=31 end=55 vars={'$FOO': 'ba383ed7bcc9e9ca434ca1c4a04c9bde', '$X': 3}>>]
```

In the first pattern matches `$FOO` is using the `sid` with value `1` - in the last match it's using the `md5sum` with value `ba383ed7bcc9e9ca434ca1c4a04c9bde`. Since these values don't match the metavariables aren't considered equivalent, and so the match doesn't work across `patterns`.

The relevant `semgrep-core` code is here:

```ocaml
let unique_id any =
  match any with
  | E (Id (id, { id_resolved = {contents = Some (resolved, sid)}; _})) ->
      J.Object [
        "type", J.String "id";
        "value", J.String (AST_generic.str_of_ident id);
        "kind", J.String (string_of_resolved resolved);
        (* single unique id *)
        "sid", J.Int sid;
      ]
  (* not an Id, return a md5sum of its AST as a "single unique id" *)
  | _ ->

     (* todo? note that if the any use a parameter, or a local,
      * as in foo(x): return complex(x), then they will have different
      * md5sum because the parameter will be different! We may
      * want to abstract also the resolved information in those cases.
      *)
     let any = Lib_AST.abstract_position_info_any any in
     (* alt: Using the AST dumper should work also.
      * let v = Meta_AST.vof_any any in
      * let s = OCaml.string_of_v v in
      *)
     let s = Marshal.to_string any [] in
     let md5 = Digest.string s in
     J.Object [
      "type", J.String "AST";
      "md5sum", J.String (Digest.to_hex md5);
     ]
```

We conditionally set `sid` or `md5sum` depending on the situation. This makes it difficult/impossible to compare metavariables across different patterns.

We should come up with a consistent way to track metavariables. I'd be in favor of always using the `md5sum` of the AST since, I believe, that should work in all circumstances. That way we can consistently always reference the `md5sum` when tracking metavariables. @aryx thoughts?

**Comment by mschwager** [comment]
I think I figured out what's going on here. The reason you're seeing different behavior is because in the first example `$FOO` is treated as both a parameter **and** and a locally defined variable:

```
  patterns:
    - pattern-inside: function $F ($FOO,...) {...}
    - pattern: $X = <... $FOO ...>;
```

In `pattern-inside` `$FOO` is considered a parameter. In `pattern` `$FOO` is a local variable. In the second example `$FOO` can be considered a parameter throughout the entire `pattern`:

```
    - pattern: |
        function $F ($FOO,...) {
          ...
          $X = <... $FOO ...>;
          ...
        }
```

Since the entire scope of `$FOO` is defined here the deep expression operator knows that `$FOO` is a parameter. This is important because `semgrep-core` considers parameters and locally defined variables to be two different types:

```ocaml
let string_of_resolved = function
  | Global -> "Global"
  | Local -> "Local"
  | Param -> "Param"
  | EnclosedVar -> "EnclosedVar"
  | ImportedEntity _ -> "ImportedEntity"
  | ImportedModule _ -> "ImportedModule"
  | TypeName -> "TypeName"
  | Macro -> "Macro"
  | EnumConstant -> "EnumConstant"
```

This confuses metavariable matching because the two different `$FOO` types (parameter and local variable) will have different unique IDs, and thus it can't match them across `patterns`.

I'm not sure how this would affect all languages, but a good solution here may be to make parameters and local variables use the same unique ID functionality. Further, I still think we should clean up unique IDs to always use `sid` or `md5sum` instead of conditionally setting one or the other.

@inkz a workaround for now would be to use `pattern` when matching parameters and deep expression operations, as you've noted, instead of `pattern` + `pattern-inside`.

**Comment by mschwager** [comment]
Re-assigning to @aryx since I've taken this about as far as my knowledge of `semgrep-core` will get me.

**Comment by dlukeomalley** [comment]
Note that this should be resolved (and decided) by work in https://github.com/returntocorp/semgrep/issues/1218. Let's revisit in the course of that ticket.

**Comment by mschwager** [comment]
> Note that this should be resolved (and decided) by work in #1218. Let's revisit in the course of that ticket.

We should clean this up in `semgrep-core` regardless, it's a generally buggy architecture (`sid` vs. `md5sum`) that will cause other issues too. E.g. here's another example which wasn't simply `pattern` vs. `pattern-inside`: https://github.com/returntocorp/semgrep/issues/1414.

**Comment by inkz** [comment]
:wave:

**Comment by inkz** [comment]
:wave:

**Comment by inkz** [comment]
@mschwager looks like now it can be tackled with taint mode. Does it make sense to keep this ticket open?
