### ISSUE TITLE
pattern-regex not matching on full code snippet

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1072]
I ran into some confusing behavior for `pattern-regex` and don't know if it's user error or a bug:

1. When I search for `Language` I get a match: https://semgrep.live/Ewpo
1. When I search for `@Language` I don’t: https://semgrep.live/7KD4
     1. This appears to be because @ isn't included in the range. Perhaps fixed by #1061?
1. When I search for `Language\(` I get a parse error, even though the documentation shows escaping `(`: https://semgrep.live/4bRZ
   1. Note that this works when using `'` versus `"`. The documentation shows `"`.

Am I misunderstanding what `pattern-regex` searches?

**Comment by mschwager** [comment]
>     2. When I search for `@Language` I don’t: https://semgrep.live/7KD4
>        
>        1. This appears to be because @ isn't included in the range. Perhaps fixed by #1061?

I agree, I don't think this is a `pattern-regex` shortcoming. Since the `@` isn't included then `pattern-regex` cannot match it.

>     3. When I search for `Language\(` I get a parse error, even though the documentation shows escaping `(`: https://semgrep.live/4bRZ
>        
>        1. Note that this works when using `'` versus `"`. The documentation shows `"`.

Good catch! Note that `"Language\\("` also works: https://semgrep.live/DbXW

YAML treats single and double quotes differently: https://docs.octoprint.org/en/master/configuration/yaml.html#scalars - "Backslashes in single quoted strings do not need to be escaped." Regardless, we should update the docs!

Do we want to track (2) in this ticket, or is updating the docs for (3) sufficient?

**Comment by dlukeomalley** [comment]
Even with @aryx's work merging the new pfff it appears the `@` is outside of the range: https://semgrep.live/10gQ?version=develop&stepByStep=1

![image](https://user-images.githubusercontent.com/605906/85178510-86087980-b233-11ea-849c-40e2e048de5b.png)

**Comment by aryx** [comment]
Bug. Can you create a separate issue?

**Comment by dlukeomalley** [comment]
Done. Closing this in favor of https://github.com/returntocorp/semgrep/issues/1081
