### ISSUE TITLE
Semgrep 1.100.0 SARIF missing rules collection in file

### ISSUE THREAD

**Issue by chaoscode** [semgrep/semgrep#10735]
**Describe the bug**
Sarif file used to provide a rules collection with the meta data for the scan findings

**To Reproduce**
Run a semgrep scan with SARIF as the output.

**Expected behavior**
I would expect that data to exist in the rules collection
This was working in 1.97.0

semgrep is installed using "pip3 install semgrep"

**Comment by chaoscode** [comment]
runs.tool.driver.rules[] is missing

**Comment by milanwilliams** [comment]
Hi @chaoscode! 

This is due to a planned change in Semgrep's output formats (introduced in version 1.100.0) as part of our updates to better distinguish between Semgrep Community Edition and the logged-in commercial platform. [View our blog post](https://semgrep.dev/blog/2024/important-updates-to-semgrep-oss/) for the full context.

As a result, some SARIF fields, including the full list of rules, are now reserved for logged-in users of the commercial platform. To regain access, simply run `semgrep login` before your command. 

For a full list of fields that differ between logged-out and logged-in use, please see our [documentation here](https://semgrep.dev/docs/semgrep-appsec-platform/json-and-sarif).

If this is still blocking you, please let me know -- shoot me an email at community-feedback@semgrep.com, here to help!

Milan

**Comment by mokuso** [comment]
It would have been useful if this information was linked in the release notes here:
https://github.com/semgrep/semgrep/releases/tag/v1.100.0
