### ISSUE TITLE
Do not parse extremely large files (e.g., >10k lines, >1MB) by default, and warn user

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1125]
**Is your feature request related to a problem? Please describe.**
Running the [Golang pack](https://semgrep.live/p/golang) with Semgrep on [kubernetes](https://github.com/kubernetes/kubernetes) takes a very long time.

The issue is due to very large files in vendored code. Links to the files:
- https://github.com/kubernetes/kubernetes/blob/a94346bef9806a135ebcfda03672966c336c1c17/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
- https://github.com/kubernetes/kubernetes/blob/a94346bef9806a135ebcfda03672966c336c1c17/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network/models.go

**Describe the solution you'd like**
In order to create a smooth experience, Semgrep should ignore very large files by default and warn the user that these files are being ignored. A flag such as `--ignore:none` should tell Semgrep not to ignore any files.

**Describe alternatives you've considered**
Alternatively, Semgrep could alert the user to the presence of large files and suggest using `--exclude`. This is more inline with how I would expect something "grep-like" to behave. This gives the user the information they need to make a decision, rather than having Semgrep make it for them.

(There might also be a way to recommend using per-file ignores for longer-running rules, too.)

**Additional context**
```console
Azure:$ find . | xargs wc
[...]
wc: ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network: read: Is a directory
    1253    4644   56414 ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network/interfacesgroup.go
     394    1487   16904 ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network/virtualnetworkpeerings.go
   33850  139475 1283208 ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network/models.go
     519    1920   21147 ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network/packetcaptures.go
     155     617    6122 ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network/availabledelegations.go
[...]
Azure:$ time semgrep -f https://semgrep.live/c/r/go.lang.security.audit.database.string-formatted-query ./azure-sdk-for-go/services/network/mgmt/2019-06-01/network
using config from https://semgrep.live/r/go.lang.security.audit.database.string-formatted-query. Visit https://semgrep.live/registry to see all public rules.
running 1 rules......
100%|████████████████|1/1
real	9m30.175s
user	9m27.551s
sys	0m3.209s
```

**Comment by mschwager** [comment]
I like that we're striving to improve the runtime for our users, but do we really want this behavior? My concern is that we'll be getting further and further into "automagic" territory, which will make it difficult for user's to reason about what `semgrep` is doing and which files are analyzed. Instead of being a simple tool that runs over each file in your source code we'll now have to reason about: V files had a parse error, W files were ignored from .gitignore, X files were too large to analyze, Y files were included from the rule, Z files were excluded on the command line. As this becomes more complex it'll be easier and easier for bugs and security issues to slip through the complicated web of files being considered. AppSec teams adopting the "no code left behind" mentality will definitely want every file to be considered. Larger files means bigger attack surface, so one could argue that these files are actually **more** important.

This sounds like a much better solution to me:

> Alternatively, Semgrep could alert the user to the presence of large files and suggest using --exclude. This is more inline with how I would expect something "grep-like" to behave. This gives the user the information they need to make a decision, rather than having Semgrep make it for them.

That way the user is consenting to whether they think that file is important to analyze or not vs. the extra time required.

However, I think the **best solution** here is to continue to tune and optimize `semgrep` until this is no longer a problem. I wonder how long `gosec` takes on these large files?

**Comment by minusworld** [comment]
```
$ gosec ./...

real	33m57.089s
user	57m50.603s
sys	32m34.735s
```

I should note that `gosec` ignored `vendor/` by default.

**Comment by minusworld** [comment]
On vendor:

```
$ gosec vendor/...

real	6m16.579s
user	12m25.012s
sys	7m0.968s
```

**Comment by nbrahms** [comment]
@minusworld Does the new `--timeout` behavior solve this issue for you?

**Comment by minusworld** [comment]
👍
