### ISSUE TITLE
Python: constant propagation for other types

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1151]
cc @aryx, not seeing boolean propagation although strings are working: https://semgrep.live/d8OQ

**Comment by aryx** [comment]
@IagoAbal good issue to explore the codebase.

**Comment by IagoAbal** [comment]
@ievans could you please elaborate what is wrong with Boolean constant propagation and the https://semgrep.live/d8OQ example? Are there any other examples that don't work as expected and that we would like to fix?

**Comment by IagoAbal** [comment]
@DrewDennison @aryx I'm not sure I understand what's wrong with Isaac's example even after reading up on SafeSQL. I get the idea although SafeSQL would report statements that do *not* use constant arguments, do we have a way to express the same thing in Semgrep?

Anyways, back to the example from Isaac, this is the pattern:
```
flask.response.set_cookie(..., httponly=True, secure=True,...)
```
And the latest Semgrep does flag this line exactly as one would expect (?) because `somevar` is assigned just once (hence considered a constant):
```
    # this cookie is secure
    resp = r.set_cookie("sessionid", "RANDOM-UUID", secure=somevar, httponly=True, samesite="Lax")
```
Now if I replace `somevar = True` with `somevar = True or True` then it no longer works, so I can see there is room for improving. However it would be useful to have a short discussion about (or a few examples illustrating) what things we expect to work and which ones do not need to work.

**Comment by aryx** [comment]
@ievans was on vacation this week. Hopefully he can spec out a bit more what he wants next week.

**Comment by ievans** [comment]
I'm back, thanks for chiming in @aryx. I actually think we should close this in favor of https://github.com/returntocorp/semgrep/issues/1645. But yes @IagoAbal this issue was specifically about the fact that only `str` types propagate, and not others like booleans for example.
