### ISSUE TITLE
Order of named fields in struct matters

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1173]
In Go, I _think_ the order of named fields in structs doesn’t matter (much like Python keyword args), but it seems Semgrep doesn’t understand that:

not working: https://semgrep.live/oqjX
not working: https://semgrep.live/zdjn
working: https://semgrep.live/pKde

**Comment by dgryski** [comment]
Value ordering in struct literals only applies to un-keyed literals.  (Note that golint complains about un-keyed literals because they break compatibility with newer versions of packages with extra fields.). Matching on field assignments for unkeyed literals might be nice, but would require full type information from third-party packages.
