### ISSUE TITLE
Incorporate taint tracking in python wrapper

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#1212]
Semgrep-core already has support for rudimentary taint analysis. We should wire it up to the python CLI to make it more accessible to users!

The current core code takes a yaml file specifying sources, sinks, and sanitizers. This seems like a lot of arguments to include directly on the commandline (like what is done with the -e flag), so it may make most sense to pass in the yaml file using some variant of the --config flag.

A few options:
1. We could use the same --config flag to specify the file but then use a second flag like --taint to specify how to interpret that file 
2. We could use a completely new flag like --taint-config to specify the yaml
3. We could use the same --config flag to specify the file and include a line in the yaml file itself indicating how to interpret the file
4. Any other ideas??? 

Welcoming feedback/suggestions/opinions!

**Comment by DrewDennison** [comment]
weak vote for 3. I would use fields like `pattern-source` or `pattern-source-file: <file path>` or `pattern-source-id: <registry id>`

**Comment by minusworld** [comment]
I also vote for 3. Something like `spec:pattern` or `spec:taint` or something similar.
Then we could straight-up use `source:`, `sink:`, and `sanitizers:` inside the config file.

**Comment by dan5382** [comment]
Weak vote for 3 as well. Seems like a good safe path forward. I'd be interested in digging into 1 as well though.

**Comment by clintgibler** [comment]
I'm super excited for this, thanks for starting this thread!

I'm still thinking about the options you've listed. First, I'd like to take a step back and wax philosophical about:
1. What we might want to express with taint
2. How other tools express it
3. How we might want to express taint in semgrep.

## 1. What do we want to express with taint?

At a high level, for **sources** we want to be able to express: for a specific API call, when it is called, what combination of the return value and it's arguments should be considered tainted?

We'll want to be able to do things like (all pseudocode):

```python
get_url_param(request)          # taint return value
parse_packet(packet_struct) # taint the argument packet_struct

# taint only the keyword arg user_info
other_method(foo, bar, to_taint=user_info, other=safe)
```

Similarly, for **sinks**, we may want to be able to express that a call is only dangerous if a specific one of the arguments is tainted, if any of them are tainted, if a keyword arg is tainted, or if the object itself the method is being called on is tained:

```python
eval(tainted) # warn if first arg is tainted

# warn if second arg or if specific keyword arg tainted_args is tainted
some_exec(local_env, cmd, verbose=True, extra_args=tainted_args) 

# flag whenever a tainted object's run() method is called, args don't matter
tainted_obj.run()
```

Similarly, we'll need to specify **sanitizer** functions that make a passed in argument, the return value, or the object calling the method safe.

**Transfer** functions: how does taint propagate between statements? These can be both for stdlib functions like string concatenation as well as third-party libraries.

```python
x = "some string" + tainted_var # x should now be tainted
y = construct_string_buffer(tainted, safe) # y should now be tainted
```

### On source/sink "types"

There will likely be some cases in which we'll want to flag when a given flow reaches a sink of a given type, like `logging`, `sql`, `command_injection`, etc.

At the very least, we'll want rules to be able to express context relevant sanitizers, e.g. shell escaping user input makes it save from passing to a shell command, but may still be vulnerable to XSS, SQLi, etc. 

## 2. How do other tools express taint?

Every tool varies, but at a high level, there are usually groups of related sources/sinks that are designed to be composed:
* **Sources**: `<these>` APIs correspond to user tainted data in Flask, Express, reading from the command line, ...
* **Sinks**: `<these>` are dangerous functions for SQL, XSS, ...
* **Sanitizers**: usually grouped by the contexts in which they make the taint safe (SQL, XSS, ...)

Then, rules are usually expressed by: one of these `sources` gets to a `sink of type X` without passing through `sanitizer for X`.

Examples:
* Facebook's Pysa static analysis tool expresses taint like [these](https://github.com/facebook/pyre-check/tree/ff8a1eda42ca3b84ba891304da44ea7de951c010/stubs/taint).
* Checkmarx uses a similar <base, usable sources query> --> <sinks query> then filter out by santizers structure - [docs](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/5406757/Query+Coding+Example)
* Here's an unsafe [Python serialization check](https://github.com/github/codeql/blob/master/python/ql/src/Security/CWE-502/UnsafeDeserialization.ql) from CodeQL.

## 3. How to express taint in Semgrep?

As one can see from existing approaches, it seems useful to be able to reuse sources and sinks across multiple rules.

* For example, the same Flask sources of tainted of data can be used to find XSS, SQLi, RCE, and more..
* The same SQL Alchemy DB sinks could be used by checks for the Flask and Django frameworks, as well as CLI utils.

I propose we add functionality for Semgrep rules (*not* just individual patterns) be composable and reusable. 

For example, `flask-xss` could just be composing `flask-user-input`, `python-user-input`, etc. + `flask-html-output`, `jinja-output`, etc.

I'd also note that we've gotten requests for being able to compose/reuse Semgrep rules outside of the scope of just taint. I think this would be generally useful functionality that merits further thought, and directly applies here.

For example, in [nodejsscan/exec_os_command.yaml](https://github.com/semgrep/rules-nodejsscan/blob/master/nodejsscan/exec_os_command.yaml), note how there is a list of ways to provide input (initial `pattern-either` and many ways to `exec()` (the second `pattern-either`).

Due to the fact that each Semgrep rule must currently be self-contained, any other pattern that wants to do related functionality must copy and paste most of these clauses, increasing rule writing friction and duplicated code.

**Comment by clintgibler** [comment]
Oh also, some cool related work by Pysa on [Dynamically Generating Models](https://pyre-check.org/docs/pysa-model-generators.html):

> Some sources and sinks may be too numerous or too rapidly changing for defining them statically to be practical. For these scenarios, Pysa has the concept of model generators, which can generate taint stubs by reading the project's source code before static analysis is started.

**Comment by aryx** [comment]
We probably want to create another issue/thread to discuss the compose/reuse of semgrep rules. I remember @rcoh also wanted that.
