### ISSUE TITLE
Merge pattern-inside and pattern, pattern-not-inside and pattern-not

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1218]
As discussed by @nbrahms : we haven't seen any instances where anyone would want to use pattern rather than pattern-inside. We could just alias the keys and stop advertising pattern-inside and pattern-not-inside.

**Comment by mschwager** [comment]
Unassigning myself in case someone can get to this before I can.

**Comment by DrewDennison** [comment]
cc @AzureUmbra

**Comment by ievans** [comment]
Go away stale bot

**Comment by dlukeomalley** [comment]
@ievans Adding a `priority:medium` label, thanks for resurrecting this ticket. It has continued to cause confusion for new (and existing) users and is worth fixing near-term (rather than "future").

**Comment by aryx** [comment]
Actually just found an example where we can't merge pattern-not and pattern-not-inside: https://semgrep.dev/s/PJ7Y/?stepByStep=1

We could merge pattern: and patter-inside, but for negation the difference matters :(

**Comment by aryx** [comment]
Here are example of semgrep-rules that now works if you treat pattern-not and patter-not-inside differently:
Great: a test file now works: ./javascript/browser/security/new-function-detected.yaml
Great: a test file now works: ./python/django/best-practice/upsell_django_environ.yaml
Great: a test file now works: ./python/django/security/audit/xss/template-translate-as-no-escape.yaml
Great: a test file now works: ./python/django/security/audit/xss/template-translate-no-escape.yaml
Great: a test file now works: ./python/django/security/injection/path-traversal/path-traversal-file-name.yaml
Great: a test file now works: ./python/django/security/injection/path-traversal/path-traversal-join.yaml
Great: a test file now works: ./ruby/lang/security/model-attributes-attr-accessible.yaml

For some examples we could rewrite the test file so that the difference does not matter (many examples use multiple times the same function or class which leads to more matching that it should), but not sure we can always do that.

**Comment by aryx** [comment]
Here is another example where merging pattern and pattern-inside would lead to a different behavior:
https://semgrep.dev/s/W8w4/?stepByStep=1

**Comment by aryx** [comment]
the problem is that And is not commutative anymore with pattern-inside and pattern. The evaluation order of
pattern-inside:x AND pattern-inside:y AND pattern:z  matters. We currently rely on
evaluatin first pattern:z and then comparing it with x, and y.

**Comment by ievans** [comment]
@aryx should I close this as #wontfix and make a new issue to improve our documentation or UX?

**Comment by aryx** [comment]
There are very few tests relying on the difference and in most cases the difference is very subtle (too subtle for a regular user i think) so we may still want to merge them; just that we will have to rewrite some of our rules

**Comment by aryx** [comment]
👋

**Comment by ievans** [comment]
:wave

**Comment by IagoAbal** [comment]
Right now we could write a better(?) version of https://semgrep.dev/s/PJ7Y with `metavariable-pattern`.

Would it be simpler having a `pattern-not` with "cannot overlap with this" semantics? That's how `pattern-not-regex` works if I'm not mistaken.

**Comment by dlukeomalley** [comment]
@ievans @emjin - Re-opening given past activity here and added 'planned-project' to avoid Stalebot moving forward.

I'm personally still excited about making the keys and their behavior simpler, in the spirit of this ticket.

**Comment by ievans** [comment]
though seems like the tail wagging the dog re: stalebot, as this is not planned

**Comment by dlukeomalley** [comment]
In that case if it's not planned I'd vote to close this issue or see it implemented. In practice, if we keep deferring an issue, it's probably not an issue we're going to actually act on.

**Comment by 0xDC0DE** [comment]
The difference between `pattern` and `pattern-inside` is also important if you consider fixes. Fixes rewrite the match of `pattern`. So you can use `pattern-inside` to match the bad code, and `pattern` to match the part of the code you wish to rewrite:

![image](https://user-images.githubusercontent.com/3809983/160338777-4814db4c-3692-46a4-91ab-12b942c133e6.png)

**Comment by aryx** [comment]
Closing in favor of #1489
