### ISSUE TITLE
“running 9 rules...” message can’t be suppressed

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#1228]
Semgrep added this progress message in the last few weeks, even on a non-TTY (as simulated here by `|& cat`):

```console
$ semgrep -f tools/semgrep.yml |& cat
running 9 rules...
```

Since Zulip runs [many linters in parallel](https://github.com/zulip/zulip/blob/3.0-rc1/tools/lint#L52), progress messages only make it harder to see when there are actual issues. All our other linters either give no such message or have an option to suppress it.

`semgrep --quiet` is too quiet; that also hides actual issues matched by the configured patterns. We could suppress stderr, but we’d have to write extra code to do that conditionally for this one linter, and also that could hide actual errors in semgrep itself.

Can you add an option to silence this progress message, or silence it by default in the non-TTY case?

**Comment by dlukeomalley** [comment]
@andersk I appreciate you filing this ticket. Do you have an example of the flags your other linters use to suppress these messages?

I'd rather add a flag here than disable it for non-TTY cases. It's been helpful for users to see these messages in build logs to prove to themselves Semgrep did what they expected it to do. Moving forward I'd expect these types of outputs to continue to change and mature; it's important to us that there is proof of work and proof of "value" in the output even when no results are returned. 

A flag should help us be careful about your use case, otherwise I wonder if we should transition to `--json`, which feels appropriate in cases where Semgrep is being used and managed by other tooling.

Thoughts?

**Comment by andersk** [comment]
We have

* `eslint`: (default)
* `isort`: (default)
* `mypy`: **`--no-error-summary`**
* `puppet`: (default)
* `puppet-lint`: (default)
* `pycodestyle`: (default)
* `pyflakes`: (default)
* `shellcheck`: (default)
* `stylelint`: (default)
* `tsc`: (default)
* `yarn-deduplicate`: (default)

and for completeness, I’ve been proposing to add:

* `black`: **`--diff --quiet`**
* `flake8`: (default)
* `prettier`: **`--loglevel=warn`**, once an approved upstream PR is merged

**Comment by dlukeomalley** [comment]
Very helpful, thank you @andersk.

Related to #1243

**Comment by brendongo** [comment]
It makes sense to me that --quiet should suppress out stderr output but should not affect printing of findings.

**Comment by brendongo** [comment]
Will having semgrep output findings on `--quiet` be enough for your use case @andersk. We are in the middle of refactoring the way we output logging messages like this so we should have more granular control on message visibility but that still needs a bit more work

**Comment by andersk** [comment]
Yeah, that’d be great. (I decided to work around this by adding a mechanism to filter lines from the output, but being able to use `--quiet` would be nicer.)

**Comment by brendongo** [comment]
With https://github.com/returntocorp/semgrep/pull/1188/files `--quiet` will only output findings and parse errors. Will go out on next release
