### ISSUE TITLE
Metavariable information discarded when using typed metavariables

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#1256]
Metavariable not being properly extracted from pattern-where-python

Pattern at: https://semgrep.live/6JDY

Trace:

```
$ semgrep --dangerously-allow-arbitrary-code-execution-from-rules -l go -f ~/go/src/github.com/dgryski/semgrep-go/wrongerr.yml
running 1 rules...
error evaluating a where-python expression: `vars[‘$ERR1’] != vars[‘$ERR’].split(' ‘)[-1]`: ‘$ERR1’
error evaluating a where-python expression: `vars[‘$ERR1’] != vars[‘$ERR’].split(' ‘)[-1]`: ‘$ERR1’
error evaluating a where-python expression: `vars[‘$ERR1’] != vars[‘$ERR’].split(' ‘)[-1]`: ‘$ERR1’
error evaluating a where-python expression: `vars[‘$ERR1’] != vars[‘$ERR’].split(' ‘)[-1]`: ‘$ERR1’
```
```
$ cat !$
cat ~/go/src/github.com/dgryski/semgrep-go/wrongerr.yml
rules:
- id: wrong-else-nil-check
  message: Checking the wrong err variable in an if block
  languages: [go]
  severity: WARNING
  patterns:
  - pattern-either:
          - pattern: “if $ERR := ...; ($ERR1 : error) != nil { ... }”
          - pattern: “if $ERR = ...; ($ERR1 : error) != nil { ... }”
  - pattern-where-python: vars[‘$ERR1’] != vars[‘$ERR’].split(' ’)[-1]
```

**Comment by nbrahms** [comment]
is `$ERR1` a valid metavariable? for some reason I thought one couldn't use numerals

**Comment by dgryski** [comment]
Yes, because this is a valid file:
```
rules:
- id: wrong-else-nil-check
  message: Checking the wrong err variable in an if block
  languages: [go]
  severity: WARNING
  patterns:
  - pattern-either:
          - pattern: "if $ERR := ...; $ERR1 != nil { ... }"
          - pattern: "if $ERR = ...; $ERR1 != nil { ... }"
  - pattern-where-python: vars['$ERR1'] != vars['$ERR'].split(' ')[-1]
```

**Comment by mschwager** [comment]
Hi all,

To start, it looks like we have a deficiency in our error messages when using `pattern-where-python`. I'm going to make some improvements there right now. Other than that, it looks like we have a bug in our typed metavariables implementation. `semgrep-core` is failing to include the relevant metavariable information when using typed metavariables. Consider the following simple example:

```
$ cat typed.go 
package main

func main() {
	var x string
	var y string
	var a int
	var b int

	if x == y {
		x = y
	}

	if a == b {
		a = b
	}
}
```

Without typed metavariables we get the expected results:

```
$ semgrep-core -pvar '$Y' -e '$X == $Y' -lang go typed.go 
typed.go:9: y
typed.go:13: b
```

With typed metavariables we get a failure on `$Y`:

```
$ semgrep-core -pvar '$Y' -e '$X == ($Y : string)' -lang go typed.go 
typed.go:1:0: Fatal Error: (Failure "the metavariable '$Y' was not binded")

Fatal error: exception (Failure "the metavariable '$Y' was not binded")
```

Even though, if we don't care about the value of `$Y`, we get the expected result:

```
$ semgrep-core -e '$X == ($Y : string)' -lang go typed.go 
typed.go:9
 	if x == y {
```

Let's fix typed metavariables so they include the metavariable value like un-typed metavariables do :+1:. I'm going to re-assign to @emjin to look into this.

Note that this was manifesting itself as a `pattern-where-python` error because the typed metavariable was not including the relevant information required for the comparison.

**Comment by aryx** [comment]
Can we close this @emjin then?

**Comment by emjin** [comment]
This error should be fixed! The above pattern now does not cause an error (https://semgrep.dev/s/emjin:wrong-error?version=develop). Note that both if statements are matched because the pattern does not include a requirement that the metavariables be different values.
