### ISSUE TITLE
Add support for metavariable statements in Golang

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1292]
https://semgrep.live/zd6n

This is blocking the last go test case for "full support" on our language matrix: https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/tests/go/metavar_equality_stmt.TODO

**Comment by dgryski** [comment]
Note that due to Go's semicolon insertion rules, the else must be cuddled for it to parse correctly.

**Comment by ievans** [comment]
@dgryski thank you, TIL. There is still an issue that $S metavariable should glob the statements in the true/false blocks, but are not; I'm going to edit this issue to reflect that.

**Comment by mschwager** [comment]
Can un-TODO `semgrep-core/tests/go/metavar_equality_stmt.TODO` when this is done.

**Comment by aryx** [comment]
It's because unlike in C or Java, in Go if statements have to be inside { }.
You can not write  if ($E) $S else $S
In C/Java/... this is allowed, which allows us to abuse statement metavariables to also match a list of statement because really they just match a single statement which is a Block statement. Unfortunately this is not valid Go syntax.
