### ISSUE TITLE
Invalid Path Separator on Windows

### ISSUE THREAD

**Issue by skanga** [semgrep/semgrep#1336]
"pip3 install semgrep" fails on windows 10 with Python 3.7.8 and pip 20.1.1 the error seems to be an invalid path separator char.
error: can't copy 'XXXXXXXXXXXXXX\Local\Temp\pip-install-cq40rzma\semgrep-files/semgrep-core': doesn't exist or not a regular file

Anyone here know how to fix that?

**Comment by skanga** [comment]
It appears like the path separator char is hard coded to be the Unix/Linux style forward slash "/" instead of an OS dependent character.

**Comment by skanga** [comment]
Just run "pip3 install semgrep" on Windows 10 to reproduce.

**Comment by ievans** [comment]
Looks like https://github.com/returntocorp/semgrep/blob/1a835b87675e2ba7624ccc1a2c0abd17ecfa1503/semgrep/setup.py#L96

should just provide separated arguments to os.path.join

**Comment by dlukeomalley** [comment]
@skanga Thanks for filing this. I'm less familiar with Windows 10, is the way that this is running via WSL? While we're not formally supporting Windows yet, we have had users running Semgrep via WSL successfully.

@ievans If the compatibility fix is as straightforward as this, seems like a good Semgrep rule for us moving forward - look for calls to `os.path.join` where the arguments contain a `/` and prefer a comma separated list of strings instead. 

CC @brendongo since this touches semgrep/semgrep/setup.py.

**Comment by skanga** [comment]
@dlukeomalley You're welcome. I was running it in a command prompt using Python for Windows. I suspect it WILL work as-in under WSL but have not tried that.

**Comment by dlukeomalley** [comment]
To unblock you in the short-term are you willing to run Semgrep via WSL? If that does work I'd like to close this ticket in favor of #1330 and focus the discussion on Semgrep supporting Windows in general.

**Comment by DrewDennison** [comment]
thanks @skanga I believe I changed to from `/` to `os.path.join` correctly in https://github.com/returntocorp/semgrep/pull/1353/files but I'll hunt down other hardcoded `/` tomorrow

**Comment by dlukeomalley** [comment]
@DrewDennison Thoughts on this Semgrep rule for preventing this in the future? https://semgrep.live/dlukeomalley:avoid-hardcoded-path-seperator
