### ISSUE TITLE
Rust Support

### ISSUE THREAD

**Issue by kevincox** [semgrep/semgrep#1338]
I'm opening a ticket to indicate interest in support for the [Rust Programming Language](https://www.rust-lang.org/).

**Comment by ievans** [comment]
Thanks @kevincox! We are in the midst of a project to use tree-sitter as the basis for all of our parsers going forward. Since tree-sitter (https://tree-sitter.github.io/tree-sitter/) advertises "fairly complete" support for rust, this may not be terribly difficult to do.

cc @aryx @mjambon

**Comment by aryx** [comment]
The main issue will be the changes to the generic AST to handle Rust-specific features. Rust is a quite different beast
compared to the other languages we currently have, but we'll see.

**Comment by aryx** [comment]
Some recent interest for Rust :) https://www.reddit.com/r/rust/comments/kepkjz/well_paid_opportunity_to_add_open_source_support/

**Comment by ievans** [comment]
Thanks to @Ruin0x11 this is well underway and shipped as "experimental" in Semgrep v.38. Tagging the people who liked the issue in case any of you are interested in helping test it! @ArniDagur, @pierwill, @riimak, @lojikil, @Boscop, @underyx, @KevinGimbel, @pcallahan-r7, @DrewDennison


Some related PRs:
https://github.com/returntocorp/semgrep/pull/2385
https://github.com/returntocorp/semgrep/pull/2488

**Comment by sharksforarms** [comment]
Hey @ievans , just found out about this project and was curious on rust support. Any notes you can provide on what needs to be tested? How can people help out? Thanks!

**Comment by aryx** [comment]
@Ruin0x11 started the work and already got many PRs merged. I don't know how much work there remains to do. @Ruin0x11 do you have an estimate?

**Comment by Ruin0x11** [comment]
I would say things like where clauses, macros, type parameters, lifetime modifiers on references, and trait blocks need more testing. Also, to achieve alpha level support there needs to be some amount of Rust-language rules added to Semgrep's rule repository. At the very least, the basic parsing code is there.

**Comment by amietn** [comment]
Hello @Ruin0x11 
I am interested in helping to get this completed. How much effort/time do you think it would take to get full Rust support in semgrep for someone who knows Python and Rust but doesn't know OCaml?

**Comment by Ruin0x11** [comment]
I'm not sure how much functional programming experience you have, but I personally managed to pick up OCaml with no prior experience and learn how the codebase worked successfully as I went along. But that's only my experience, because I already had experience with functional programming from other languages like Lua and Clojure. It could be harder for you if you have no experience with things like pattern matching or higher order functions.

If you can get past that hurdle, then the Rust support shouldn't be that hard to work on, as the code is pretty readable and OCaml's type checker helps you out. But again I'm not sure how long it would take you to learn OCaml if you don't know it. I would say to give it a shot and see how difficult it is to learn. (Plus, you'd be one step closer to that Jane Street internship.)

**Comment by amietn** [comment]
Thanks! I'll give it a shot :)

**Comment by rohitjoshi** [comment]
any update on Rust support?

**Comment by amietn** [comment]
@rohitjoshi I added support for writing semgrep patterns for Rust rules with statements directly:

* https://github.com/returntocorp/ocaml-tree-sitter/pull/177
* https://github.com/returntocorp/semgrep/pull/2910
* https://github.com/returntocorp/ocaml-tree-sitter/pull/184

That was merged in semgrep v0.47.0.

**Comment by rohitjoshi** [comment]
Thank you!  Yes, I tried and it worked. Are there any existing rules ported for rust which can be used as reference?

**Comment by amietn** [comment]
As far as I know, I don't think there are any Rust rules in the https://github.com/returntocorp/semgrep-rules repository at the moment I'm afraid.

**Comment by rohitjoshi** [comment]
Thanks. Do you think we can reuse existing rules or auto-generate from existing? There is lot of good work done by community to create rules. Some of them may be lang specific but some may be able to reuse with little modifications. E.g. RegEx patterns

 I have also started converting go lang s[ecurity/audit/crypto](https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/security/audit/crypto/use_of_weak_crypto.yaml) to Rust.

@aryx

**Comment by aryx** [comment]
For rules you can take inspiration of existing
Rust linters. For example for Ruby we started with imitating what brakeman was doing. Same for JS with eslint. What are the existing Rust linters?

**Comment by dgryski** [comment]
The standard Rust linter is https://github.com/rust-lang/rust-clippy

**Comment by brooksmtownsend** [comment]
Hello, we're using `semgrep` using some custom rules for our Rust project and it's going well so far. One thing we noticed is that metavariables for functions don't work correctly when used with macros, here's a few code snippets.

We're testing to see if a variable is written out to stdout, through `println!` or log macros
```
let $X = $FUNC1(...);
...
$WRITE(..., $X, ...);
```
In the semgrep rule
```
  - metavariable-regex:
      metavariable: $WRITE
      regex: ^(println!?|debug!?|warn!?|error!?|info!?|trace!?|format!?)$
```

This does not trigger on the following piece of code, though it does trigger if you remove the `!` from the `println!` macro
```
    let err = sensitive_error();
    println!("err = {:?}", err);
```

Commenting here to bring attention to macros in general, though I was curious on the estimated level of effort to include function names with a `!` token so that we can take advantage of the ellipses operator for extra arguments. If it's a small change, I'd be happy to contribute.

**Comment by rc-mattschwager** [comment]
Hello from the outside!

Having Rust support would greatly help some of the initiatives I'm working on :)

**Comment by aryx** [comment]
There is actually already some Rust support.
I guess we can close this issue and people can create issues for more specific bugs.

**Comment by aryx** [comment]
It's even mentioned there: https://semgrep.dev/docs/language-support/

**Comment by rc-mattschwager** [comment]
Nice! I'll give it a go

**Comment by aryx** [comment]
OMG it's matt! I didn't even realize it when I answered to you :)
