### ISSUE TITLE
Add support for constant propagation in Ruby

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1345]
We can un-TODO `semgrep-core/tests/ruby/equivalence_constant_propagation.TODO` when this is done.

**Comment by clintgibler** [comment]
Adding a comment here because of a customer ask: 

> I am **really** interested in being able to write a rule for Ruby like, "Alert if the first argument to this function is not a compile-time constant string."

It appears that we already do constant propagation in a number of cases, but support varies:

* Python: https://semgrep.dev/s/clintgibler:python-constant-prop
* Ruby:  https://semgrep.dev/s/clintgibler:ruby-constant-prop

See also https://github.com/returntocorp/semgrep/issues/1645

CC @aryx @IagoAbal
