### ISSUE TITLE
semgrep doesn't parse included headers

### ISSUE THREAD

**Issue by karthick-gururaj** [semgrep/semgrep#1378]
https://semgrep.live/0bpq

In the code snippet:

    #include "some_file.h"
    int i = 0;
    foo_t f;

I expected to see an error - since `semgrep` can't find the included header or definition of the type `foo_t`. But no error is issued. I'm not sure if this is a bug or how the tool is designed fundamentally. I thought the tool should parse _and_ resolve type references. Looks like I'm mistaken.

**Comment by mschwager** [comment]
Hi @karthick-gururaj,

> I'm not sure if this is a bug or how the tool is designed fundamentally.

**Comment by mschwager** [comment]
Hi @karthick-gururaj,

> I'm not sure if this is a bug or how the tool is designed fundamentally.

In this case, this is how the tool is designed. Since Semgrep is performing static analysis on the code itself it will not resolve external references. To do so would require considering the state of the filesystem, the compiler header include flags, and compiler linker flags, which Semgrep doesn't currently have access to. This provides advantages like being very fast and easy to use, but also comes with disadvantages like not considering the dynamic environment the code is in.

If you'd like we can track this as a feature request to resolve external references in C. What do you think?

**Comment by karthick-gururaj** [comment]
> In this case, this is how the tool is designed. Since Semgrep is performing static analysis on the code itself it will not resolve external references. To do so would require considering the state of the filesystem, the compiler header include flags, and compiler linker flags, which Semgrep doesn't currently have access to.

Ok, I understand.

> If you'd like we can track this as a feature request to resolve external references in C. What do you think?

Yes, sure. The feature can be split into two parts - first being resolving references within a [translation unit](https://en.wikipedia.org/wiki/Translation_unit_%28programming%29) and the second will be to analyze across translation units.
