### ISSUE TITLE
Timeout still happens even if default is 0

### ISSUE THREAD

**Issue by TMFRook** [semgrep/semgrep#1471]
**Describe the bug**
When timeout is not provided, the documentation says it defaults to 0 (which means there is no timeout). However, it still timeouts.

**To Reproduce**
1. Run `semgrep --config=https://semgrep.dev/p/r2c-CI .`
2. Returns `Warning: Semgrep exceeded timeout when running contrib.nodejsscan.eval_yaml_deserialize.yaml_deserialize2 on api_manager/static/api_manager/libs/jquery_2.1.3/js/jquery.min.js. See `--timeout` for more info.`.
3. `semgrep -h` says: `--timeout TIMEOUT     Maximum time to spend running a rule on a single file in seconds. If set to 0 will not have time limit. Defaults to 0.`

**Expected behavior**
Should never timeout since that's what the doc says.

**Screenshots**
![image](https://user-images.githubusercontent.com/68116003/89695148-f8ffa980-d8e0-11ea-97d8-5d7475cd32ba.png)

![image](https://user-images.githubusercontent.com/68116003/89695205-1af92c00-d8e1-11ea-9189-6aaca9be15d1.png)

**Environment**
Running off official binary: 
![image](https://user-images.githubusercontent.com/68116003/89695103-d40b3680-d8e0-11ea-8608-2f919939c656.png)

**Comment by brendongo** [comment]
Thanks for filling this issue @TMFRook! Looks like we didn't remove https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/bin/Main.ml#L349 which is setting a default timeout of 5 seconds for javascript files.

**Comment by brendongo** [comment]
A side effect of removing the default timeout of 5 seconds in js will mean if a project has large minified javascript files semgrep will potentially take forever to run.

Thoughts on setting default timeout to 5 seconds @mschwager @TMFRook?

**Comment by TMFRook** [comment]
I don't have an opinion on the default timeout setting. However, it is odd to me that it would choke on seemingly small-ish files. They're only ~82K big. Is this expected?

**Comment by mschwager** [comment]
> A side effect of removing the default timeout of 5 seconds in js will mean if a project has large minified javascript files semgrep will potentially take forever to run.
> 
> Thoughts on setting default timeout to 5 seconds @mschwager @TMFRook?

Javascript tends to be an outlier as far as code files go. Codebases frequently have generated JS files (minified, multiple files combined, etc), so I think it's fine to treat JS as a special case. With that being said, I think it'd be best if this 5 sec JS default was specified in the Python interface rather than the OCaml core. We could include some logic to detect when `lang == 'js'` and `timeout == 0` and update the `timeout` to 5. If `lang == 'js'` and `timeout != 0` then we respect whatever the user specified.

> However, it is odd to me that it would choke on seemingly small-ish files. They're only ~82K big. Is this expected?

You're correct @TMFRook, ~82K is not that large as far as disk space is concerned. However, Semgrep's performance will often be dependent on factors other than filesize such as code complexity, variable/function/class usage, statement depth, etc. Without looking into the individual file that's causing the timeout it would be difficult to say what is causing the slowdown.

**Comment by nbrahms** [comment]
@aryx Would you be able to post an update about our plan for this ticket?

**Comment by aryx** [comment]
As soon as I can fully switch to tree-sitter and use tree-sitter first, we can fix that issue.
Right now we still use the pfff parser first because otherwise we have regressions. I'm working on those regressions.

**Comment by aryx** [comment]
Blocked on https://github.com/returntocorp/ocaml-tree-sitter/issues/102

**Comment by aryx** [comment]
This should work better now!
