### ISSUE TITLE
Support brew version pinning

### ISSUE THREAD

**Issue by kncdev132** [semgrep/semgrep#1477]
We would like semgrep to support version pinning via a formulae such as `semgrep@0.16.0`.

Our current use case:

We have a minimum requirement of 0.17.0. We do not want to necessarily have to install the latest version when someone installs semgrep to avoid introducing potential breaking changes. This is already supported by semgrep via docker with tagging.

**Comment by mjambon** [comment]
Hey @KieranCairney , I assigned this to my colleague @brendongo who knows better about this than me.

**Comment by brendongo** [comment]
Hi @KieranCairney. Does installing using Pypi work for you? We have pinned versions there. Because homebrew-core needs everything to build from source and our build steps have been in flux it's a fair bit of work to get older versions pinned on brew but we will probably start pinning once we've stabilized how we build our dependencies soon.
