### ISSUE TITLE
Regression in matching vardefs with expression patterns in 0.18 

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1497]
**Describe the bug**
Regression in the matching logic in 0.18 caught by @ajinabraham's integration tests: https://semgrep.dev/7g0Q?version=0.18.0

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/7g0Q?version=0.18.0 vs https://semgrep.dev/7g0Q?version=0.17.0

**Expected behavior**
`$X = '...';` should match `var $X = '...';` in javacript

**Comment by nbrahms** [comment]
This appears to be due to returntocorp/pfff@78f052659671. This converts `ExprStmt` nodes into pure expressions.

However, we don't convert `VarDef` nodes into `Expr` nodes when matching against the program, so we no longer match.

IMO, we should perform the `VarDef` conversion instead of reverting 78f052659671, as this would also allow us to match with or without the trailing semicolon.

cc. @aryx

**Comment by nbrahms** [comment]
This will be fixed in 0.20.0.

As a bonus, the trailing semicolon will no longer be required in this type of pattern:
https://semgrep.dev/7g0Q?version=develop
