### ISSUE TITLE
Javascript, can't match repeated 'var $X'

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1516]
https://semgrep.dev/z8xd

**Comment by aryx** [comment]
Because you redefine the same variable, and we resolve names, so the first $X match a global with the single unique identifier Global 1 (see the dumped AST in the editor in Tools/Dump AST), and at the second line it's another variable with the single unique identifier (sid) Global 2, and $X can not match this one.
If you use $X and $Y it will work.
