### ISSUE TITLE
Clean up parser warning UX

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1550]
I'm looking for feedback on the UX of the final semgrep output. I propose the following. When run in an interactive shell, semgrep will print the following final line.

If (internal tool) warnings exist:

```
current> Warnings exist. Run with `--strict` to turn warnings into errors.
proposed> Ran 37 rules over 3817 files: 0 findings
3 files could be not analyzed: run with `--verbose` for details; run with `--strict` to exit non-zero if one or more files cannot e analyzed
```

If (internal tool) warnings do not exist (related to #1562):

```
current> no output
proposed> Ran 37 rules over 3820 files: 0 findings 
proposed> Ran 37 rules over 3820 files: 42 findings (2 info, 3 warn, 37 error)
```

The tricky thing about this text is differentiating _internal tool errors_ from _rules labeled error_.

**Comment by ievans** [comment]
cc @brendongo @DrewDennison @aryx @sabihb @dlukeomalley for thoughts

**Comment by clintgibler** [comment]
I like what you've proposed.

> Warnings exist. Run with `--strict` to turn warnings into errors.

This is unclear whether semgrep found bugs or had some internal problems.

```
proposed> Ran 37 rules over 3817 files: 0 findings
3 files could be not analyzed: ...
```

I like this: printing how many rules were ran over how many finds and a quick summary of findings tells you it's working, or at least points out when you're doing something wrong ("huh, I expected to be running 100 rules but only ran 3").

Can we print more context around **why** files couldn't be analyzed? "Could not be analyzed" makes me wonder, "Well, why not?" At the very least we could mention something about it being due to an error parsing source code files.

```
proposed> Ran 37 rules over 3820 files: 42 findings (2 info, 3 warn, 37 error)
```
I love the extra context here.

As I was thinking about this I had this idea about making it easier to report parser bugs. I think we've already worked on this, but I think we can do more: https://github.com/returntocorp/semgrep/issues/1652.

**Comment by aryx** [comment]
sgtm too. I like the proposed output.

**Comment by aryx** [comment]
Who can do the work? @brendongo @mschwager who is familiar with this part of the codebase?
