### ISSUE TITLE
Use test corpus minimization to speed up QA testing time

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1568]
AFL has this cool corpus minimization technique to remove redundant files: [afl-cmin](https://manpages.debian.org/testing/afl/afl-cmin.1.en.html)

I think we could do something similar with our QA tests and `semgrep-core` where we:

* Integrate code coverage instrumentation into `semgrep-core`
* Gather all QA test repositories
* Gather all code files in QA repositories and group them by language
* Run `semgrep-core` against these code files such that we gather code coverage information for each file
* Find the minimal set of code files necessary to achieve ~100% coverage
* Commit these files to a QA test repository somewhere
* Run QA testing against this (likely much smaller) repository

This provides a few performance benefits: 1.) we no longer need to clone all these repos, we're now cloning just one repo, and 2.) we are now running against a much smaller corpus of test files, but achieving the same coverage. Bonus points: if we mostly automate this process we can continue to update the corpus as we add new features and still maintain ~100% coverage.

**Comment by ievans** [comment]
Couldn't this result in overfitting and then missing cases that we used to past, but now don't?

**Comment by dgryski** [comment]
Corpus minimization makes sense when your binary isn't changing. However, given that semgrep and the rules are under development the corpus would immediately become out of date.

**Comment by mschwager** [comment]
> Couldn't this result in overfitting and then missing cases that we used to past, but now don't?

I'm by no means an expert in this kind of stuff, but after a quick read of [overfitting](https://en.wikipedia.org/wiki/Overfitting) I think you're correct. We should also consider that line coverage != branch coverage. Chasing line coverage will not guarantee us any level of quality. However, these are decent proxies for quality and may make a good trade-off between level of verification and speed to implement and run.

> Corpus minimization makes sense when your binary isn't changing. However, given that semgrep and the rules are under development the corpus would immediately become out of date.

This is a great point as well. Perhaps my proposed solution above is off, but I think the problem identified is valid. That is, how can we take a more measured, faster, more reliable approach to regression testing? Right now we're "flying blind" with a bunch of QA repositories that we think (hope) are representative of all code. The amount of parse errors we see leads me to believe this isn't the case. 

The move towards tree-sitter may make this a moot point, but we still want to be protected against regressions. Disregarding the above approach, we could brainstorm other ways to do this effectively. Do you all have any ideas? Here are the problems we're facing with the current approach:

- QA testing against a [long list of active repositories](https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/public_repos.py#L11) is slow
- We don't know what level of coverage or verification this list is getting us
- We don't know when we should add or remove repositories

**Comment by dgryski** [comment]
For regression testing you want to check a few things:
   1) parsers don't regress; that is, the number of files that fail to parse never increases
   2) pattern matching doesn't regress; that is, given a number of source files and a set of rules, we never find fewer true positive matches than a previous release.

In the first case, this means you want to actually have a significantly large corpus of real-world source code to run against.  Minimizing this corpus to match the current parser necessarily means removing cases that might have different coverage paths when the parser changes.

For case number two, this points to having a set of rules, an unchanging set of source code (which means your QA setup can't just always pull the latest from github), and ensuring that either 1) the old and new version produce exactly the same output or 2) any changes are expected behaviour changes (because they're fixing either a bug in the parser or a bug in the matching code.)

If each rule that gets added to the main semgrep-rules repo has an associated positive and negative test, that will help with ensuring coverage for the different rule features but doesn't help catch edge-cases regressions that will likely only be found via a large real-world corpus.  (The other problem of course with just testing existing rules against a corpus is unless you actually validate each rule by hand + grep + other test oracles, you won't actually know if you have any false negatives caused by bugs.  But, at least you won't *remove* known true positives from the result set and you can have a lower priority background QA task to manually validate each rule against your corpus.)
