### ISSUE TITLE
pattern-inside metavariables are not bound in the message

### ISSUE THREAD

**Issue by dkasak** [semgrep/semgrep#1699]
**Describe the bug**
Metavariables used in a `pattern-inside` are not available in the `message` and are left unexpanded.

**To Reproduce**
https://semgrep.dev/s/gpoK/

**Expected behavior**
`$CLASS` in the above example should be expanded to `Foo`.

Is this a known limitation?

**Comment by brendongo** [comment]
This might be a more complex change than I initially thought. Because of the way we do range resolution we don't actually have access to the pattern_match obj and thus the metavariables of a pattern-inside rule. https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/evaluation.py#L306

IMO might be better to wait til we refactor evaluation.py to be more set-operation-y instead of the multi-pass range approach it uses now.

**Comment by brendongo** [comment]
Related https://github.com/returntocorp/semgrep/issues/1273

**Comment by brendongo** [comment]
Going to wait on progress for https://github.com/returntocorp/semgrep/issues/1489 will revisit if that simplificiation takes too long.
