### ISSUE TITLE
Null AST but no parsing error returned on typescript code in editor

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1709]
In
https://semgrep.dev/s/AjqQ/?version=develop
where Javascript is selected, semgrep does not report any match, but it does not report
any parsing failure either. Selecting Typescript in the menu instead reports correctly the match.
If you select back Javascript and look at the dumped AST (in Help menu), there is a Null AST for
the program.
Why?
semgrep-core correctly parse the file and return a full AST. Not sure what's going on here, and what is
the effect of selecting a language in the menu when there is already a language selected in the yaml.

**Comment by aryx** [comment]
@chmccreery might also know what's going on. Where is the language selected in the dropped-out menu used,
and how it relates to the languages field in the yaml. What has priority?

**Comment by chmccreery** [comment]
Hmm yeah, we need to figure out a better way to handle language conflicts. Right now, we don't really have any guardrails against the user specifying one language in the drop-down and another in their yaml. @aryx what would you expect to happen here? Some ideas:
1) We warn user about the inconsistency and do not even allow code to run until they match (what I am leaning toward)
2) We choose one of them as the "Truth" and use it to automatically overwrite the other
3) We _warn_ the user in the GUI but still allow code to run, choosing which one to treat as "truth"

**Comment by aryx** [comment]
Yes option 1 sounds good to me. Note that a rule can have multiple languages, so just make sure the selected lang is at least part of the list of languages specified in the rule.

But independently of that, why there's a null AST? Where the language specified in the menu is used? I thought it was just a way for the monaco editor to switch to the right mode. Is it passed to the semgrep CLI program? Why do we need to pass this language?

**Comment by chmccreery** [comment]
Cool, I will go for option 1.

It is passed to semgrep-core because users don't have to specify language in their pattern, so we ask semgrep to parse the pattern and target code in whatever language is in the drop-down. The hope was that users would use the language drop-down **instead** of specifying language in the yaml when using the editor, because it wouldn't make sense for users to write a pattern in one language and target code in another. 

I realize now that the assumption we made was pretty naive and we should definitely handle this error case better.

**Comment by aryx** [comment]
I guess this got fixed.
