### ISSUE TITLE
[Golang] Can't find option in var to prevent CORS vuln

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1740]
Semgrep can't find option in var to prevent CORS vuln in Golang
https://semgrep.dev/s/WeKZ/

**Comment by brendongo** [comment]
@dvyakimov thanks for filling. This looks like it might be a bug on our end.

**Comment by colleend** [comment]
Seems like this is parsing in tree-sitter because lack of `package <package name>`. But if we do something like: 

https://semgrep.dev/s/ZWAL/

which parses in pfff, same issue happens. I looked into it a bit, and it appears that AllowedOrigins is parsed as ArgKwd in pfff, 
 `ArgKwd(("AllowedOrigins", ()), L(String(("test", ()))));`
But `AllowedOrigins` pattern is parsed into E(Id). 

@aryx should we change transformation of object key-values in Go to G.Arg(G.Id) or something like that? 

Thanks for the help!

**Comment by dlukeomalley** [comment]
@colleend @DrewDennison @aryx Checking in on this ticket. Any next steps we can queue up? Thank you!

**Comment by aryx** [comment]
One issue is that AllowedOrigin in the pattern is parsed as an identifier, but in the code it's a keyword argument, and those are not matched agains one another. You could add more context around it to disambiguate that you look for a keyword argument, but I failed to get https://semgrep.dev/s/ZWEn/ working, so this needs further investigation.

**Comment by aryx** [comment]
This now works at least: https://semgrep.dev/s/ne2Y/?version=develop
