### ISSUE TITLE
Repeats in results (python)

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1749]
3 results of $PATH in message (repeat)
https://semgrep.dev/s/X2qw/

**Comment by underyx** [comment]
I did a bit of investigation here.

The issue comes from the raw string flag. When searching `eval($FOO)` in this code:

```python
eval(r'foo')

eval('bar')
```

The first metavar has `"abstract_content": "r'foo'r'foo'r'foo'"`, while the second has `"abstract_content": "'bar'"` as you'd expect.

The AST representations are

```ocaml
[Arg(
          Call(IdSpecial((EncodedString(("r", ())), ())),
            [Arg(L(String(("foo", ()))))]))]
```

and

```ocaml
[Arg(L(String(("bar", ()))))]
```

respectively.

@aryx at this point I'm not sure how to investigate further. Is it possible that the issue is that this first multi-layered tree gets multiple nodes in succession written out as `abstract_content`?

**Comment by brendongo** [comment]
Looks like bug is reproducable with binary encoded strings too `eval(b'foo')` so might be an issue in EncodedString

**Comment by underyx** [comment]
Yeah, I get the feeling we might be flattening the tree and each of the three layers outputs itself as a full string.

**Comment by dvyakimov** [comment]
Could you fix it in web editor?

**Comment by aryx** [comment]
Should work in the editor in 30min now with ?develop

**Comment by aryx** [comment]
see https://semgrep.dev/s/X2qw/?version=develop
