### ISSUE TITLE
windows[...] can't be find in React (javascript)

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1792]
Can't find {`window['__initialState'] = ${JSON.stringify(state)};`} by windows[...] pattern
https://semgrep.dev/s/JqoZ/

**Comment by dvyakimov** [comment]
And other question
Is it to complex for semgrep?
https://semgrep.dev/s/5Wzl/

**Comment by dvyakimov** [comment]
One more example :)
https://semgrep.dev/s/Rrx2/

**Comment by dvyakimov** [comment]
There is something happening with "window" or may be html:
https://semgrep.dev/s/D80W/

**Comment by mschwager** [comment]
> Can't find {`window['__initialState'] = ${JSON.stringify(state)};`} by windows[...] pattern
> https://semgrep.dev/s/JqoZ/

I don't think `...` is completely implemented for JSX tags yet. For example, the following works: https://semgrep.dev/s/6Wpj/?version=develop, but this doesn't: https://semgrep.dev/s/z8X0/?version=develop. This is probably related to #1791 - it looks like JSX is missing some Semgrep features.

@aryx does this seem right to you? Do we have any plans for further JSX functionality in the near future?

**Comment by aryx** [comment]
It's because what is inside the backquotes is a template Javascript string which is just interpreted as text by semgrep. Even if you write code in it, semgrep does not know about it so you can only use string patterns, for example
https://semgrep.dev/s/xxQP/ (I have a problem to specify using a regexp with window[.* but that's another issue).
Inside the backquote if you use ${ then semgrep know that what is inside is regular javascript code again, and this is why you can use
the ... in JSON.stringify().
