### ISSUE TITLE
PHP - using isset with pattern-not-inside causes an invalid pattern error

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#1794]
**Describe the bug**
Using `- pattern-not-inside: isset(...)` results in an `semgrep error: invalid pattern`. If `isset` is replaced by `issets`, then it works fine.

**To Reproduce**
https://semgrep.dev/s/GR31/

**Expected behavior**
There should not be any pattern error.

**Screenshots**
<img width="611" alt="Screenshot 2020-10-07 at 13 08 45" src="https://user-images.githubusercontent.com/1668843/95323308-42975100-089e-11eb-9683-94f96ecb4907.png">

**Environment**
semgrep.dev, as well as v0.27.0 on MacOSX 10.15.6 (installed via brew)

**Comment by mschwager** [comment]
Hi @erwanlr,

Thanks for finding this. If my PHP memory serves, `isset` is not actually a function. From [`isset`](https://www.php.net/manual/en/function.isset.php): "Note: Because this is a language construct and not a function, it cannot be called using variable functions."

@aryx do we need special handling for `isset` since it's not a function?
