### ISSUE TITLE
[typescript] Would like to be able to match functions in a pattern

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1852]
**Describe the bug**
Cannot match a function in a pattern.

**To Reproduce**
https://semgrep.dev/s/5WNl/

**Expected behavior**
Should be able to match a TypeScript function in a pattern.

**Screenshot**
<img width="799" alt="image" src="https://user-images.githubusercontent.com/6817500/96287137-56c20900-0f96-11eb-816a-abde9306b997.png">

**Environment**
Semgrep 0.27.0

(Priority for me: somewhat important)

**Comment by DrewDennison** [comment]
@msorens thanks for the bug report. tagging our TS expert @mjambon for an update on when this can get fixed

**Comment by mjambon** [comment]
@msorens I would suggest the following workaround:

```
class $X {
  bar() {...}
}
```
See https://semgrep.dev/s/6WQ6

For matching a similar function definition, you'd have to create a separate pattern introduced with the `function` keyword:
```
function bar() {...}
```

@aryx please let us know if you think of a better solution here. It looks like we'd have to allow method definitions as top-level patterns.

**Comment by msorens** [comment]
@mjambon Two problems with your workaround.

1. The output goes from just a few lines (the function definition) to perhaps 100 lines (the entire class body). That presents a poor user experience; need to be able to constrain output to be terse.

2. What exists today does not quite make sense:
- one can match a single line of code (or single expression, if you will)
- one can match an entire class
- one can match an entire function that exists as a top-level definition
- one cannot match an entire function that exists as a method within a class  _<--[ Very strange restriction?!? ]_

**Comment by aryx** [comment]
This is because of grammar ambiguities and yacc shift/reduce conflicts.
When seeing bar(), yacc has no idea that you start to define a method in a semgrep pattern. It thinks you
started to write a function call. In typescript, the parser knows because you can define methods only inside a class, so when you parses 'class foo {', the official typescript parser knows that bar() is the start of a method definition, and not a function call, because function calls are not allowed as method elements.

**Comment by aryx** [comment]
Things are even worse in Javascript because some keywords like 'function' or 'class' are actually allowed as method names, and so for semgrep it's pretty difficult to parse any kind of patterns, hence the current requirement to write 'function bar() {' to clearly indicate to semgrep you want to parse a function/method.

**Comment by aryx** [comment]
@mjambon note this is actually where tree-sitter shines by using a Generalized LR algorithm instead of yacc LALR(1).

**Comment by aryx** [comment]
I can add some parsing hacks around yacc to allow toplevel method semgrep pattern, but it will have some restrictions.
