### ISSUE TITLE
Ruby metavars don't match full class paths

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#1892]
**Describe the bug**
Currently, metavariables in Ruby will only match a solo class path (e.g. `class Foo`), but *not* if the class is something like `class Foo::Bar`.

**To Reproduce**
https://semgrep.dev/s/clintgibler:ruby-class-metavar-bug

**Expected behavior**
Ideally `class $CLASS ... end` should match all of the following:

~~~ruby
class Foo
end

class Foo::Bar
end

class Foo::Bar::Blah
end
~~~

Until this is the default behavior, rule writers will have to write separate pattern clauses for each potential depth of the module hierarchy, which is not ideal.

**What is the priority of the bug to you?**
Probably P1 (important to fix or quite annoying) or P2 (regular bug that should get fixed). 

A customer told us about this bug, which made it harder to complete a custom rule they were writing.

**Comment by aryx** [comment]
It's because the way Ruby defines classes does not fit well with how the other languages are doing it, which means the generic AST does not represent well such class definitions. In every other languages a class is defined by a single identifier, which defines a class in the current scope (package, module, etc.).
