### ISSUE TITLE
[JS] A metavariable can't match both a fieldname and a variable in an object as in { ..., $URI, ...}

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1930]
**SSRF is detected with explicit name "uri":**
https://semgrep.dev/s/3eze

```
const uri = $REQ.query.validationURL;
...
const $OPTION = {...,uri, ...,};
...
$REQUEST.post(...,$OPTION,...);

```

**SSRF is missed with $URI pattern:**
https://semgrep.dev/s/4B3x

```
const $URI = $REQ.query.validationURL;
...
const $OPTION = {...,$URI, ...,};
...
$REQUEST.post(...,$OPTION,...);
```

**Comment by dvyakimov** [comment]
I think, I understood:
https://semgrep.dev/s/Rr2g
It needs to be with this format:

```
const $URL = $REQ.query.$PARAM;
...
const $OPTION = {...,$OBJ:$URL, ...,};
...
$RES.post(...,$OPTION,...);
```

Is it correct behavior?

**Comment by aryx** [comment]
It's because internally a JS object like o = { fld1, fld2: 3} is rewritten internally as o = { fld1: fld1, fld2: 3}
and using a metavariable $URI to match both a field name and a variable does not work.
We could probably fix it.
In the mean time yes you can be more explicit and do uri: $URI, or $FLD:$URI like you did above.
Here is the simplest fix:  https://semgrep.dev/s/D8Rd/

**Comment by dlukeomalley** [comment]
@aryx If I read your comment correctly, do you think this is an `enhancement`?

@dvyakimov Do you feel like you have a path forward based on @aryx's sample he shared?
