### ISSUE TITLE
Feature - #nosem should be case-insensitive

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#1991]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Using `#nosem`, `#NOSEM`, `//NOSEM`, etc. should work the same way.

**Describe alternatives you've considered**

Use the current convention.

**Additional context**
This feature is debatable, but hey! I am asking because we have a lot of `//NOPMD` peppered in some of our Java code so my first instinct was to do `//NOSEM`

**Comment by mschwager** [comment]
The `nosem` functionality is case-insensitive, you just need a space before it, e.g. https://semgrep.dev/s/z8Od/

Here's the `nosem` logic if you're curious: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/constants.py#L44

**Comment by j-martin** [comment]
Ah! Can we re-open to handle no space prefix?

**Comment by mschwager** [comment]
> Ah! Can we re-open to handle no space prefix?

I can re-open if you'd like, but the required space prefix was intentional. To avoid maintaining a list of all supported language's comment syntax we don't actually require the comment symbol. To minimize false positives in `nosem` detection we required the space prefix, e.g. we won't detect the following as a `nosem` annotation:

```java
call_nosemaphore();
```

However, there are still false positives like:

```java
public nosemaphore() {
}
```

This deficiency has been noted before: https://github.com/returntocorp/semgrep/pull/1531.

So we can definitely re-open for removing the space prefix, but consider the following:

- No space prefix can lead to higher false positives in `nosem` annotation detection
- We can offset this by requiring a comment symbol before the optional space
- Although this will incur the cost of maintaining a list of supported language's comment symbols

Thoughts?

**Comment by j-martin** [comment]
That's entirely reasonable. I think it should be documented then since I can't think of a linter (that I've used) that cares about the leading space in the comment.

**Comment by mschwager** [comment]
Sure thing! See https://github.com/returntocorp/semgrep-docs/pull/42

**Comment by j-martin** [comment]
Cool. It might also make sense to throw a warning when `nosem.*` (no space prefix) is found.
