### ISSUE TITLE
Typescript rule hangs on Signal Desktop

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2102]
This hangs for at least an hour:

using Signal-Desktop at https://github.com/signalapp/Signal-Desktop 

```
ine@imbp4 ~/D/r/t/Signal-Desktop (development) [130]> time semgrep --debug -f r/typescript
trying to download from https://semgrep.dev/r/typescript
using config from https://semgrep.dev/r/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
loaded 1 configs in 0.7014610767364502
running 16 rules from 1 config remote-url_0
running 16 rules...
Running rule typescript.angular.security.audit.angular-domsanitizer.angular-bypasssecuritytrust...

...ran on 510 files
Running rule typescript.angular.security.audit.angular-domsanitizer.angular-sanitize-none-context...

...ran on 510 files
Running rule typescript.react.best-practice.react-props-in-state.react-props-in-state...
```

```
$ semgrep --version
0.32.0
```

Labeling as P0 (high) as this makes Semgrep totally unusable when running any set of rules that contains this rule.

**Comment by nbrahms** [comment]
@ievans As of 0.33, we set a default timeout of 5 seconds per file, and a maximum number of 3 timeouts per file (so we'd expect your run to take around 15 seconds, assuming one file is breaking here).

Would this alter the priority of your issue?

**Comment by ievans** [comment]
@nbrahms yes I think that would definitely make it a P2!

**Comment by aryx** [comment]
Someone reported a similar problem on some private Go repositories.

**Comment by ievans** [comment]
@nbrahms @aryx surprisingly, even in v0.33 I tried leaving it overnight and it didn't terminate after 6hrs. We should re-prioritize IMO (cc @mjambon?)

**Comment by aryx** [comment]
Ok by adding more logging and by using SEMGREP_CORE_EXTRA="log_to_file mylog -debug -profile" I managed to find the issue; There is no timeout on any file, which is good; the -timeout option is working as intented. The problem is that given the rules in r/typescript, semgrep-core finds more than 4M matches, and then it takes forever to get the range and metavar information for those 4M matches (this part of the code was not under a timeout condition; only the parsing and matching was, because they were specific to a file).

I'm writing some code to do more stats on those 4M matches; I'll probably add a pass after the engine find matches to filter some of those matches and transform them in some Timeout for certain files with the offending rule in additional information. Hopefully this can be surfaced later in the semgrep wrapper and warn the user that certain pattern, on certain files do not generate a timeout but GenerateTooManyMatches (a new kind of internal/resource-exhaustion error).

**Comment by aryx** [comment]
I've added a -max_match_per_file option to semgrep_core, with a default to 10 000. When a file generate matches
above that limit, we fake a Timeout exception on this file in the list of errors returned by semgrep-core to the semgrep-python wrapper. We could change that error type later, but at least it prevents semgrep from stalling forever on Signal-desktop.

**Comment by aryx** [comment]
Still takes 8m19, but a least it finishes:
```
ran 24 rules on 714 files: 1074 findings
43 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed

real	8m19.704s
user	11m24.919s
sys	0m34.871s
```

**Comment by aryx** [comment]
Note that the semgrep-python wrapper captures the stderr of semgrep-core, and only when it finishes it outputs it (when run with semgrep --debug). This is a bit annoying @brendongo because it prevents to see the progress output of semgrep-core, to see for example live which files it is currently processing.

**Comment by ievans** [comment]
Thanks @aryx 

> I've added a -max_match_per_file option to semgrep_core, with a default to 10 000. When a file generate matches

This sounds like a great resolution for now!
