### ISSUE TITLE
Error: :found mismatch between test and result ids - test={test_ids} result={reported_ids}"

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2141]
In semgrep UI I see 5 test errors
https://semgrep.dev/s/ZWp7

But if i try to look at it in CLI, I get some system error:

<img width="909" alt="Снимок экрана 2020-12-01 в 12 38 08" src="https://user-images.githubusercontent.com/34271513/100722813-13025200-33d2-11eb-90bc-0ad164b43026.png">

"found mismatch between test and result ids - test={test_ids} result={reported_ids}"

**Comment by mschwager** [comment]
Hi there @dvyakimov,

This is trying to tell you that your test is returning findings that aren't annotated, or aren't tested in the test code. More specifically, the `sfs.golang.cors.sameorigin.echo.requestheader` rule is missing tests in your test code. To fix this error you can either temporarily remove the rule from your config file or added tests for that rule to the test code.

Ideally this should be a warning instead of a hard error, but our `--test` functionality does not have great support for granular logging at this point.

EDIT: a good quick solution would be to gate this error on the `--strict` flag :+1:
