### ISSUE TITLE
Separate ocaml and nodejs worlds to facilitate contributions

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2240]
This was discussed here: https://r2c-community.slack.com/archives/CK86BJ5DW/p1605820145019400

The goal is to allow contributions to tree-sitter grammars without setting up an ocaml dev environment, and also allow contributions on the ocaml side in semgrep-core without having to know about setting up nodejs for the tree-sitter parser generators.

We want an easy tool for turning the collection of tree-sitter grammars residing in [semgrep-grammars](https://github.com/returntocorp/semgrep-grammars) into up-to-date parser code in [ocaml-tree-sitter-lang](https://github.com/returntocorp/ocaml-tree-sitter-lang). ocaml-tree-sitter-lang code is ready to compile and plugs into the semgrep-core project as a submodule. Essentially we want:

> `semgrep-grammars` &rarr; `ocaml-tree-sitter-lang`

This "magic command" is currently not magic at all. It takes a lot of work since it requires setting up both the tree-sitter/nodejs and ocaml environments, building ocaml-tree-sitter, and running it on the appropriate git repos, branches and submodules without getting confused.

Good things to know:

* ocaml-tree-sitter-lang does not contain original source code. It contains large generated files and we won't mind getting rid of its history the day it gets too slow. It's usually ok to push a bad commit to its main branch by accident.
* We're looking to replace the `make -C lang release` command of ocaml-tree-sitter and all the preliminary setup steps.

Maybe we could offer a docker image that includes ocaml-tree-sitter and its prerequisites, takes a semgrep-grammars commit ID as input and commits the generated code to a local clone of ocaml-tree-sitter-lang.

See also #2239

**Comment by aryx** [comment]
A nice thing is that semgrep really just need ocaml-tree-sitter-lang/ and the runtime part of ocaml-tree-sitter.
We don't need the ocaml-tree-sitter/semgrep-grammars at all under semgrep; we just care about ocaml-tree-sitter-lang
so maybe it would be better to extract the runtime part of ocaml-tree-sitter/ and put just that under semgrep/ (and actually even better under semgrep/semgrep-core/).

That way we would have semgrep/semgrep-core/ocaml-tree-sitter-lang/ and semgrep/semgrep-core/ocaml-tree-sitter-runtime.

The whole preparation and nodejs part of ocaml-tree-sitter can be completely separate from semgrep.
What do you think?

**Comment by aryx** [comment]
For example today I've updated semgrep-grammar to the latest tree-sitter-ruby, then I updated ocaml-tree-sitter to the latest semgrep-grammars, then I've made a new release in updated ocaml-tree-sitter-lang.

Now the only thing I need to pull in semgrep is the latest ocaml-tree-sitter-lang; I don't even care about the latest ocaml-tree-sitter (if the runtime and types didn't change; for example a new parsing result type will need me to update to the latest ocaml-tree-sitter, but otherwise there's no need).

**Comment by mjambon** [comment]
This is a pain point for everyone involved with updating tree-sitter grammars for semgrep. I set the priority to medium because it's not strictly blocking but it's very important to a lot of people.

Pain points:
* too many submodules involved when updating a grammar, leading to human mistakes
* generating ocaml code requires the contributor to set up ocaml and know how to troubleshoot

Here's the structure I suggest:
* one repo `semgrep-tree-sitter` containing:
  * ocaml code generator (currently in ocaml-tree-sitter)
  * ocaml runtime library to be used by the generated code (currently in ocaml-tree-sitter)
  * tests for the ocaml code generator and runtime (requires the runtime library; currently in ocaml-tree-sitter)
  * grammars: the contents of the current semgrep-grammars repo
  * code to automate the publication of ocaml code derived from the tree-sitter grammars (new)
* one repo containing the large generated libraries to be used by semgrep: ocaml-tree-sitter-lang (unchanged)
* semgrep-core: uses the ocaml-tree-sitter runtime library and the generated libraries for each grammar (unchanged)

Updating a tree-sitter grammar in semgrep-tree-sitter should not require the contributor to build the ocaml components locally. Testing the tree-sitter grammars involves the usual nodejs setup only. CI will take care of generating and publishing ocaml code into ocaml-tree-sitter-lang, and this should just work.

**Comment by aryx** [comment]
For "semgrep-core: uses the ocaml-tree-sitter runtime library and the generated libraries for each grammar (unchanged)"
does that mean there is another repo with just the ocaml-tree-sitter runtime library? or it's still the full semgrep-tree-sitter?

**Comment by mjambon** [comment]
@aryx ocaml-tree-sitter per se is an ocaml code generator + the runtime library to support the generated code. I won't split them into different repos, for sure. We could distribute them as separate opam packages if that's useful. The key requirement is to not require downloading the tree-sitter-* submodules when we just want the ocaml-tree-sitter runtime library.

**Comment by mjambon** [comment]
Marking this as high-priority because it affects the productivity of all contributors, both internal and external.

**Comment by aryx** [comment]
In your original plan you have "The goal is to allow contributions to tree-sitter grammars without setting up an ocaml dev environment," and again later you wrote: "Updating a tree-sitter grammar in semgrep-tree-sitter should not require the contributor to build the ocaml components locally." but really I think we can assume people contributing/modifying the semgrep grammars have an OCaml environment. It's more the nodejs setup that annoys me and the time it takes to build the .c and .ml files from all the grammars. Is there a way we can make it easier to set nodejs for people who want to compile semgrep? Maybe we should remove in the end the ocaml-tree-sitter-lang intermediate? The main problem I want to address is that someone modifies semgrep-grammars, e.g. the rust grammar, or the rust semgrep grammar, and all the tests pass. BUT the Parse_rust_tree_sittter.ml will not compile with those changes, because the grammar changed so some constructors changed. Now someone else is arriving, also modifying another semgrep grammar, e.g., the R grammar, and regenerate ocaml-tree-sitterlang but now he also has to fix Parse_tree_sitter_rust.ml befcause ocaml-tree-sitter-lang pulls all the latest changes from semgrep-grammars.

**Comment by aryx** [comment]
Ideally, the person who modifies a semgrep grammar will type make, and be forced to modify the Parse_xxx_tree_sitter.ml, so that the burden does not go on someone else.

**Comment by aryx** [comment]
ocaml-tree-sitter-lang was ok when it was just martin (and occasionally me) modifying the semgrep grammars, but now we have 5 people possibly modifying it, and it requires discipline to not walk on each other toes.

**Comment by Ruin0x11** [comment]
IMO, I think it's only practical to modify the semgrep grammars if you're also going to modify the parser code, since changes in the former can cause compile errors in the latter, so you'd need both dev environments set up anyway to make sure nothing breaks. It sounds like it's a tradeoff between having an `ocaml-tree-sitter-lang` that can easily get out of sync with `semgrep-grammars` on a constant basis, or the ability to contribute to the OCaml core without needing to set up a Node environment a single time.

**Comment by mjambon** [comment]
The current situation is:
* semgrep-grammars is now included in ocaml-tree-sitter instead of being a submodule (since today)
* generated code is published to semgrep-LANG for each language LANG, instead of all the languages existing in ocaml-tree-sitter-lang (work in progress)

**Comment by mjambon** [comment]
Basically, we're dropping the goal of "separating ocaml and nodejs worlds".

**Comment by mjambon** [comment]
The split of ocaml-tree-sitter-lang into semgrep-javascript, semgrep-ruby, etc. is now live!
