### ISSUE TITLE
[Python] Can't enforce metavariable equality between fields and identifiers of the same name

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2304]
Function with self.$SECRET = $SECRET can't be found

https://semgrep.dev/s/2xyj

**Comment by mschwager** [comment]
Hi @dvyakimov,

It looks like we generally cannot find patterns of the form `self.$META = $META` yet: https://semgrep.dev/s/jRry/

cc @aryx on whether this is feasible or not.

**Comment by dvyakimov** [comment]
Why it's not a bug? :)

**Comment by ievans** [comment]
@dvyakimov I agree this is a bug :D adding the label. Can you share what kind of priority this is for you? P0 = can't do anything with semgrep if not fixed, p1 = medium, p2 = minor annoyance

**Comment by dvyakimov** [comment]
p1

**Comment by nbrahms** [comment]
@ievans @dvyakimov The reason why we might _not_ consider this a bug is that the left-hand-side is a field, while the right-hand side is an identifier, and these are not semantically equivalent. That said, I can't think of a clear counter-example where considering fields and identifiers semantically equivalent would be an issue.

cc. @aryx  for thoughts here.

@dvyakimov In the meantime, you could work around this by enforcing _textual_, rather than _semantic_ equivalence, like so:

```yaml
patterns:
  - pattern: self.$FIELD = $IDENTIFIER
  - pattern-where-python: vars['$FIELD'] == vars['$IDENTIFIER']
```

Thanks for the report, and I hope this work-around helps!

**Comment by aryx** [comment]
Got a fix, but then it introduces some regressions elsewhere ...

**Comment by aryx** [comment]
This now works on develop: https://semgrep.dev/s/2xyj?version=develop
