### ISSUE TITLE
Semgrep-action reporting wrong line number in notification

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#2343]
**Describe the bug**
Slack notification links to the wrong line number

Helpful context: https://returntocorp.slack.com/archives/C010SQK6GSD/p1610039074017600?thread_ts=1609985111.013900&cid=C010SQK6GSD

**To Reproduce**
Not totally sure, but this is the situation where we encountered it:
1) Introduce a new rule to a managed policy
2) Create a pull request on a repo with pre-existing issues
3) Compare the line number that is printed out by a semgrep finding against the one in the slack notification

**Expected behavior**
The line number from the finding to be printed out in the notification.

**Screenshots**

**What is the priority of the bug to you?**
P2 because I have only seen in once, but possibly higher because 

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
This was on semgrep.dev

**Comment by nbrahms** [comment]
33m
nathan  This finding was first discovered when scanning commit ce7901b1dea65315f48182165a7ddf660da1a93a on Nov. 24, 2020. At that time, it appeared on line 174 of DataTable.tsx. It was then marked as fixed at some point after that. It was then rediscovered by a scan of commit a95fc5acef8a81a1e13a0bcc13510d895821992c on Jan. 6, 2021, where that line now appears on 206.
:+1:
1

33m
nathan  So the open question here is how it got "fixed" ever (did we turn the rule off then turn it back on recently?)
32m
nathan  Seems like there are a bunch of UI nits here to fix:
32m
nathan  
Notification for a reopening should note that the issue is resurrected
31m
nathan  
Notification for a reopening should link to the actual offending code; for technical reasons it will be easiest for us to link to the original code in the original commit
31m
nathan  
Findings page needs a way to show issues reopened in last 30 days
