### ISSUE TITLE
Lua method calls not fully handled

### ISSUE THREAD

**Issue by mwild1** [semgrep/semgrep#2404]
Hi folks, congratulations on the release, and thanks again @Ruin0x11 and everyone involved with adding Lua support!

I just ran the sample `$X == $X` rule to get started, and found an issue.

**Describe the bug**
Method calls (of the form `object:method()` seem to be only partly handled.

In Lua `foo:bar("abc")` is syntactically equivalent to `foo.bar(foo, "abc")`, but it is not parsed this way by semgrep.

**To Reproduce**
I'd link to semgrep.dev, but Lua is not listed there (yet? :) ).

Lua code:

```
return foo:one() == foo:two()
```

incorrectly matches the pattern `$X == $X`.

**Expected behavior**

I'm not certain, but I feel that probably the solution is translating to the canonical `object.method(object)` form in the AST (and then translating patterns the same way).

**What is the priority of the bug to you?**

Method calls are used extensively, and right now it appears that semgrep cannot match them correctly at all. I think that makes this a pretty high priority issue.

**Environment**
I tested with semgrep 0.37.0 from pip.

**Comment by Ruin0x11** [comment]
Yes, that's fair. I hope we can get more test cases to make sure the Lua support is actually usable.

I think this is because currently the generic AST variable resolver will assume the language you're using treats variable definitions like `let` where a new binding name is created. So it would count a statement like `foo = foo` as creating an entirely new binding on the left hand side `foo` that gets assigned the old binding `foo` on the right hand side. I think those should get treated as assignment operations instead if there isn't a `local` keyword.

**Comment by aryx** [comment]
But his example is using ==, not =.

**Comment by Ruin0x11** [comment]
Yes sorry, I found another issue while I was testing. I added test cases for both in my PR.
