### ISSUE TITLE
go - equivalent naming import does not work

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [semgrep/semgrep#2424]
I was testing this registry rule `go.jwt-go.security.jwt-none-alg` and I noticed that it does not work when the Go import has an alias (like `foo`). I've made a live editor clone here https://semgrep.dev/s/fproulx-boostsecurity:go-equivalent-naming-import???registry=go.jwt-go.security.jwt-none-alg

@minusworld looked at this with me and if we modify the pattern to have a variable in the import, then it breaks the default behavior (https://semgrep.dev/s/ZveL/)

**Comment by dlukeomalley** [comment]
@fproulx-boostsecurity Thanks for opening a ticket after the Slack convo. Gauging your priority, how urgent is this fix/improvement needed?

**Comment by fproulx-boostsecurity** [comment]
I would say that this makes matching pretty much anything in Go that is
specific to a given imported  package almost completely unreliable. Any
import alias can break those rules from matching. That blocks us from
declaring that we have robust Go scanning support.

**Comment by mschwager** [comment]
Interestingly it looks like we do support this behavior in Python:

```
$ cat test.py 
import yaml as totally_not_yaml

totally_not_yaml.load(filename)
```

```
$ python -m semgrep -l python -e 'yaml.load(...)' /tmp/test.py 
/tmp/test.py
3:totally_not_yaml.load(filename)
ran 1 rules on 1 files: 1 findings
```

However, conversely, we don't consider imports without aliasing: https://github.com/returntocorp/semgrep/issues/1096

cc @aryx I'd say this is fairly important - part of the [equivalences we advertise](https://semgrep.dev/docs/writing-rules/pattern-syntax/#imports) are imports.

**Comment by mschwager** [comment]
IMO this is more of a bug than an enhancement. We advertise import equivalences for GA languages, which Golang is one of. I suspect this is an issue with multi-line imports in Golang because it appears to work for single-line equivalences: https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/tests/go/equivalence_naming_import.go

**Comment by mschwager** [comment]
Okay, I think this bug is a bit more complex than I originally anticipated. It appears to be a confusion between Golang's concept of `package`, and the `import` mechanism. Unfortunately it appears that we cannot totally rely on the `import` string for aliasing. E.g.

- This works: https://semgrep.dev/s/W8WA/, the `import` string "matches" the package name
- This doesn't work: https://semgrep.dev/s/0Q8b/, the `import` string is different from the package name

The `import` string is [`jwt-go`](https://github.com/dgrijalva/jwt-go), but the `package` name is [`jwt`](https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L1). This causes some confusion when dealing with import aliases, and imports in general I suspect. This seems to be problematic because, if I understand correctly, there's no easy way to tell what the package name is simply by looking at the import URL. I.e. we'd have to investigate the package itself to determine the package name, which is difficult from a static analysis point of view.

**Comment by nbrahms** [comment]
Since there's no syntactic information to indicate that the `jwt-go` package is named `jwt`, we'll need to implement user-defined equivalences for this. I'm not sure if we've implemented this yet at all (or how it would work), so leaving this as a feature-request for equivalences.

As a workaround, I think https://semgrep.dev/s/dK1Q/ is probably the best Semgrep can do in the near term, although it could subject the user to false positives.

**Comment by nbrahms** [comment]
@fproulx-boostsecurity can you confirm that the above workaround alleviates your current issue? Much thanks, and our gratitude for raising this issue.

**Comment by fproulx-boostsecurity** [comment]
OK. I understand. But yeah I guess some user equivalence in the rule to specify the package name will be necessary... :/

**Comment by DrewDennison** [comment]
@IagoAbal this seems related to your constant propagation work. Down the road, could we use a similar approach to do this for renamed imports?

**Comment by IagoAbal** [comment]
Semgrep seems to assume this (c.f. https://blog.golang.org/package-names#TOC_4.):
>  By convention, the last element of the package path is the package name

If there are other conventions that have widespread use perhaps we should take them into account too.

It was not very difficult to find a few more Go packages that use the `-go` suffix in their path. Should we perhaps add support for that convention?

**Comment by fproulx-boostsecurity** [comment]
Looks like that as this article explains:
```
Yes, people tend to write packages so they match their URL. But the URL doesn’t define how you use the package. If you look at the source code for json-iterator/go, you’ll see that each file has package jsoniter at the very top. This is what defines how one should reference its variables and functions. The import paths for the standard library packages just happen to be the same as how you use them, that’s how they’re defined in the source code, so it’s easy to think that the trend holds true for all imports.

Another example of this is with the Youtube package from Google. The import path for it is google.golang.org/api/youtube/v3, so you might initially think that you prepend v3 to function calls and variable references to use the package, however once again you’ll see in the source code that the package name is defined as youtube.
```

so I guess that only way is for the semgrep rule to specify this extra metadata, which it cannot figure out by scanning just one `.go` file ... as you said "user-defined equivalences" I guess - which in that case it's not just an equivalence , it's actually the only and proper way to refer to it by default (unless aliased)

**Comment by IagoAbal** [comment]
@fproulx-boostsecurity we went for recognizing other naming conventions that seem common in Go, `.../xyz/vN` and `.../xyz-go`. Your example should now work. Let us know if you encounter other import naming issues, maybe we need to reconsider that solution.
