### ISSUE TITLE
internal: clone shallow submodules

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2425]
Cloning semgrep and its submodules takes about 2 minutes in CI, which is long. `git clone ... --shallow-submodules` should allow cloning semgrep and its submodules quicker than currently. See https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules and `git clone --help`.

**Comment by aryx** [comment]
Note that an alternative is to remove ocaml-tree-sitter from semgrep.
We really just need ocaml-tree-sitter-lang and ocaml-tree-sitter-lib.
The rest of the machinery, and especially all those tree-sitter-xxx we don't need.

(at the same time in the futur we may want to remove ocaml-tree-sitter-lang instead since it introduces
an intermediate steps that prevents to modify a tree-sitter-grammar and be able to just type make
and get everything updated).

**Comment by mjambon** [comment]
This was solved last week by https://github.com/returntocorp/semgrep/pull/3022
