### ISSUE TITLE
Rule with code execution is not skipped and fails whole scan (and fails pipeline as a result)

### ISSUE THREAD

**Issue by mfocuz** [semgrep/semgrep#2427]
**Describe the bug**
Sorry to create is as bug, while it also could be considered as feature. But for me it currently fails whole pipeline.
I'm running semgrep with setting --config=semgrep-rules/, where "semgrep-rules/" is pulled from repo.
In case of there is a rule with code execution inside, whole scan stopped and says:

`at least one rule needs to execute arbitrary code; this is dangerous! if you want to continue, enable the flag: --dangerously-allow-arbitrary-code-execution-from-rules`

Adding this flags is not acceptable in my and most probably many other cases

**To Reproduce**
Run scan on any project with "--config=semgrep-rules/" 

**Expected behavior**
Skip rules with code execution if no flag "--dangerously-allow-arbitrary-code-execution-from-rules", just print warning but do not stop whole scan

**What is the priority of the bug to you?**
P0 - fails pipeline.

**Environment**
official binary

**Comment by dlukeomalley** [comment]
Thank you for filing this ticket @mfocuz. To immediately unblock you, I wanted to learn more about the rules you're running. Where are they from?

For folks running Semgrep in CI, assuming your rules are not custom, we recommend pulling from the registry: https://semgrep.dev/explore

You can run registry rules through commands like: `semgrep --config "p/r2c-ci"`

The rulesets that are available from the registry do NOT require the `--dangerously-allow-arbitrary-code-execution-from-rules` flag.

Beyond that, I wonder if we can remove the offending rule from your `semgrep-rules/` directory or potentially re-write it; with new features like metavariable-regex we've found less and less need for arbitrary code execution. CC @aryx @grayson who may have more thoughts here.

**Comment by mfocuz** [comment]
Hi @dlukeomalley , I clone rules from here https://github.com/returntocorp/semgrep-rules and run it.
Due to its official repo, my idea was to run always latest rules. Is it wrong approach?

**Comment by aryx** [comment]
You can use URLs with the --config, so no need to locally clone the semgrep-rules. Semgrep can use the network to fetch
the rules on-the-fly. For example --config p/r2c will use the best and latest rules in  https://github.com/returntocorp/semgrep-rules

**Comment by mschwager** [comment]
Hi @mfocuz,

We've made your suggested improvements in https://github.com/returntocorp/semgrep/pull/2450. Those changes will go out with the next release sometime this week :+1:

**Comment by mfocuz** [comment]
cool, thx!

**Comment by mschwager** [comment]
Hey @mfocuz,

After merging in https://github.com/returntocorp/semgrep/pull/2450 we realized that this would break backwards compatibility with existing Semgrep installations, so we reverted. Generally, we believe that silently skipping `pattern-where-python` rules (e.g. in a CI scenario where a user may not be watching `stdout`) could lead to findings being missed. We could include some kind of `--skip-dangerous-rules` flag, but at that point users can simply remove the dangerous rules from their Semgrep run.

Since we found a workaround by running something like `--config p/r2c` instead of cloning and running `semgrep-rules` directly, does that seem reasonable to you?
