### ISSUE TITLE
go - constant propagation does not work with short variable assignment

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [semgrep/semgrep#2440]
It appears that Golang support for constant propagation does not cover `:=` short assignment statement. It works with `var` declaration though.

https://semgrep.dev/s/fproulx-boostsecurity:go-const-propag-broken

**Comment by IagoAbal** [comment]
I believe the problem may be in how `:=` is represented internally, I need to check Go's language spec first.

**Comment by IagoAbal** [comment]
Internally `:=` is not being represented as an assignment in the way that one would expect, the encoding is kind of "obfuscated". As far as I understood it, this is because some users want to distinguish `:=` from `=` during matching. I will fix constant propagation to recognize this case and handle it properly.
