### ISSUE TITLE
Rule evaluation slows down linearly+ with length of paths.exclude

### ISSUE THREAD

**Issue by karoun** [semgrep/semgrep#2475]
**Describe the bug**
I'd like to grandfather in all the current instances of a pattern, but `ERROR` for new ones, so I'm using `paths.exclude` to list all the existing file paths. Unfortunately, that list is ~1,350 entries long and double-unfortunately, `semgrep` slows down massively (<3s → ~80s) when I add it to my ruleset.

**To Reproduce**
[Add lots of exclusions to `paths.exclude`](https://semgrep.dev/s/0Qyb)

**Expected behavior**
I'd expect `semgrep` to take slightly more time to process exclusions, but not orders of magnitude more. One possible optimization could be to use exact matching [instead of globbing](https://github.com/returntocorp/semgrep/blob/61547b1934deccd2c47affd9559d2b1347fd2dcf/semgrep/semgrep/target_manager.py#L201) if the exclude lacks glob characters.

**Screenshots**
N/A

**What is the priority of the bug to you?**
~P1~ P2 (has workaround)

**Environment**
Official binary

**Comment by ievans** [comment]
Hi @karoun! thanks for taking the time to file a bug--this is definitely something we should fix. cc @brendongo who knows the most about that part of the code.

I wanted to hear more about your use case though -- I bet most users haven't run into this because they have been using the semgrep CI wrapper (https://github.com/returntocorp/semgrep-action) to "grandfather" in instances of a new pattern rather than using the `excludes` key. By default, the Semgrep CI wrapper is aware of git structures and will only report issues that are new in the diff and is smart enough to handle branches and commits, etc. (We should document this better; https://semgrep.dev/docs/integrations/ explains some of it). 

Would using the CI wrapper unblock you here?

**Comment by karoun** [comment]
Oh wow, that's super slick — thanks @ievans!

**Comment by ievans** [comment]
@karoun since the semgrep CI wrapper unblocks this but it's still a bug we'd like to fix, marking as a P2 for now
