### ISSUE TITLE
Make violation thresholds configurable per-rule

### ISSUE THREAD

**Issue by karoun** [semgrep/semgrep#2476]
**Is your feature request related to a problem? Please describe.**
I'm trying to deprecate a common pattern in a codebase, and it's too frequent/tetchy to autofix/patch all at once. If I make it a `WARNING`, new instances will creep in, but if I make it an `ERROR`, I'll be forced to `exclude` all the existing matches (which is both [very slow](https://github.com/returntocorp/semgrep/issues/2475) and allows new violations in excluded files).

**Describe the solution you'd like**
Perhaps just for `WARNING`s (?), but I'd like there to be a configurable threshold for each rule such that if the number of matches exceeds it, it'll be treated as an error. ESLint [implements something similar](https://eslint.org/docs/2.0.0/user-guide/command-line-interface#-max-warnings), in the form of a global `--max-warnings` CLI flag.

**Describe alternatives you've considered**
My current approach is to parse the JUnit/JSON output from `semgrep` and implement per-file/per-rule warning thresholds via custom tooling.

**Additional context**
N/A

**Comment by mschwager** [comment]
Hey @karoun,

Thanks for the idea! Another option is leveraging the [`nosem`](https://semgrep.dev/docs/ignoring-findings/#ignoring-findings-via-inline-comments) functionality to allow all current findings, and stop new ones from creeping in. This would be a large code change, since it seems your codebase has many findings, but it's one way to achieve this workflow.

I know we've been thinking about alternative methods for achieving this workflow. @ievans mentioned one in https://github.com/returntocorp/semgrep/issues/2475#issuecomment-769525917 using `semgrep-action/agent`. cc @dlukeomalley who may have more thoughts here.

**Comment by dlukeomalley** [comment]
@karoun Following up on some of earlier conversations, I think [Semgrep CI](https://github.com/returntocorp/semgrep-action/) solves most of the use case here. The maintainer group's preference is for any CI integration to leverage the diff-aware scanning + baselining features of Semgrep CI.

I'm tentatively closing this issue, is that ok given the functionality of Semgrep CI? Happy to chat more here or catch up on Slack.
