### ISSUE TITLE
String regex escaping special characters

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#2486]
**Describe the bug**
Creating a string regex that has special character escaping results in semgrep looking for the exact sequence of characters instead of the escaped character itself. For instance, in the semgrep.dev example linked below, the regex matches the first line but not the second. 

**To Reproduce**
https://semgrep.dev/s/EkvA/

**Expected behavior**
Would expect semgrep to match the second case.

**What is the priority of the bug to you?**
P2

**Comment by mschwager** [comment]
I'm not entirely sure how [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) are handled in Javascript. I.e. I'm not sure if the `${...}` portion is actually part of the string itself and can be searched. The fact that `${tainted}` isn't highlighted here tells me that may be the case: https://semgrep.dev/s/7oYR/

cc @aryx who knows more about the PCRE inline regexs and Javascript parsing functionality.

**Comment by colleend** [comment]
that's a very good point 🤔 another interesting happening is https://semgrep.dev/s/LwXJ/: I get an error "Could not parse target.jsx as js" although the error is in the pattern 😓

**Comment by emjin** [comment]
Matt's correct---the ${...} portion is parsed as an interpolated string. The first link you gave was behaving as expected; it was matching the presence of a $ in the first string (https://semgrep.dev/s/emjin:dollar-rule shows it's not exact match). You can actually search directly for an interpolated string, if that's all you want! (see https://semgrep.dev/s/emjin:inter-string) I'm not sure if this works with regexes.

The https://semgrep.dev/s/LwXJ/ is because of poor error message. The problem is actually that the regex can't be parsed by the library we used. If you want that regex, you can file an issue and we can look into changing the regex parsing library!

**Comment by aryx** [comment]
Someone should file a task in semgrep-app for saying there's an error in the code when the error is really in the pattern.

**Comment by emjin** [comment]
> Someone should file a task in semgrep-app for saying there's an error in the code when the error is really in the pattern.

https://github.com/returntocorp/semgrep-app/issues/1630

**Comment by colleend** [comment]
seems like the inter-string rule is giving me the $ rule instead -- what's the syntax to search directly for the interpolated string again? Ideally for this pattern, I would want to find an interpolated string with string literals to the left or right side of the interpolated string (the second example in https://semgrep.dev/s/EkvA/)

**Comment by emjin** [comment]
Oops linked the wrong thing! @colleend Does https://semgrep.dev/s/weXn work?

**Comment by colleend** [comment]
perfect! 🙏 🙏
