### ISSUE TITLE
Semgrep should return non-zero exit code when results are found

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#2544]
Per https://semgrep.dev/docs/cli-usage/, Semgrep should return a non-zero exit code when results are found.

On the https://github.com/digininja/DVWA repo, when clone and run with `eslint-plugin-security` ruleset:

```bash
$ semgrep --config p/eslint-plugin-security
... omitted for brevity ...
ran 7 rules on 10 files: 1 findings
$ echo $?
0
```

CC @jmeit-fwdsec who found the bug

**Comment by mschwager** [comment]
I believe this has always been the case, and the docs appear to be incorrect. IIRC this is why we have the `--error` flag:

```
  --error               Exit 1 if there are findings. Useful for CI and
                        scripts.
```

I'm definitely supportive of this, I think it makes more sense to have the reverse: exit > 0 with findings by default, and provide a flag to exit 0 with findings when provided. This is what `flake8` does:

```
  --exit-zero           Exit with status code "0" even if there are errors.
```

However, I think this will be a big change because there are lots of installations depending on the current behavior. We'll have to come up with a solid upgrade plan/path :+1:

**Comment by nbrahms** [comment]
@dlukeomalley What do you see the priority of this issue as?

**Comment by msorens** [comment]
This is one of those minor things I had wondered about when I first encountered it: why did one have to use the `--error` flag to force semgrep to provide a conventionally expected exit code? I am therefore in favor of the change, but I agree, it is a breaking change to an unknown number of users. Perhaps should wait until you are ready for v1.x so you can introduce semantic versioning and then, per convention, break whatever you want. 😉

**Comment by aryx** [comment]
The problem is that the more we wait, the more people will be affected, as the number of users of semgrep grows every week. So better now than later.

**Comment by aryx** [comment]
Who knows when 1.x will come.
