### ISSUE TITLE
Per line ignore for HTML files

### ISSUE THREAD

**Issue by jithurjacob** [semgrep/semgrep#2566]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to ignore lines for HTML files. I've used exclude to ignore the file entirely.

**Describe the solution you'd like**
Ability to ignore lines with nosemgrep comments like other languages.

**Comment by minusworld** [comment]
Ah! Good catch. I think this should be a quick fix. I'll work on it shortly.

**Comment by minusworld** [comment]
@jithurjacob This is in the development branch and will go out in the next release.

For your reference, `nosem` comments currently need to be at the end of the line. Since HTML comments are not allowed inside of tags, you can also include `nosem` as an HTML attribute. This isn't ideal but it does get things started.
This is the test file we included for this, which you can use for reference:

```html
<h4>From: {{ from_email }}</h4>
<h4>To:
    {% for recipient in recipients %}
    {{ recipient }}&nbsp;
    {% endfor %}
</h4>
<h4>Subject: {{subject}}</h4>
<div class="email" style="display: block;">
    {{ message }}
</div>
<div class="email-text" style="display: none;">
    <pre>{{ body }}</pre>
    <a href='{{ link }}'>{{ link_text }}</a> <!-- nosem: var-in-href -->
    <a href = '{{ link }}' >{{ link_text }}</a> <!-- nosemgrep: var-in-href -->
    <a href = "{{ link }}" >{{ link_text }}</a>
    <a
        href = "{{ link }}" nosem="var-in-href"
    >
        {{ link_text }}
    </a>
    <a href="{{ url_for('index') }}">{{ link_text }}</a>
    <a href="https://example.com/">{{ link_text }}</a>
    <a href="https://example.com/{{ link_path }}">{{ link_text }}</a>
</div>
<hr>
```
