### ISSUE TITLE
typescript parsing bug: 'public abstract async methodName()'

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2737]
https://semgrep.dev/s/Bkl2

Verified to compile correctly in TS4.0, although editors complain about this.

**Comment by nbrahms** [comment]
@dlukeomalley let's keep all medium+ external-facing bugs on the customers board 🙇

**Comment by mjambon** [comment]
It was a bug in the official typescript implementation. `abstract` and `async` don't go together. It is now reported as such at least since [typescript 4.1.5](https://www.typescriptlang.org/play?ts=4.1.5#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIIAOAriMgJawKiQzz1gCeAdnSMFABQCUALgQAFKNgC21MAFMAPADds1ACYA+ANyEAvoSA) but it is tolerated in 4.0.x.

We could probably tolerate any combination of modifiers in the tree-sitter parser, though. Due to how tree-sitter parsers work, this would tolerate duplicate modifiers, as in:
```typescript
abstract class Foo {
  public abstract abstract bar(): Promise<void>;
}
```

**Comment by mjambon** [comment]
Closing this because the user will have to fix their code at some point anyway, by removing the `async` keyword occurring next to `abstract`.

**Comment by aryx** [comment]
Nice, we reach a point where parse errors reported by users are actually legitimate parsing errors :)
