### ISSUE TITLE
Can not compile javascript pattern -> f(...) + ... + f(...)

### ISSUE THREAD

**Issue by ankush** [semgrep/semgrep#2754]
**Describe the bug**
Semgrep 0.42 does not compile following pattern as valid Javascript patter:
`f(...) + ... + f(...)` or the one I was actually interested in: `f("...") + ... + f("...")`

**To Reproduce**
Steps to reproduce the behavior: https://semgrep.dev/s/8yPy

**Expected behavior**
This appears to be a simple pattern, should compile just fine.

**Screenshots**
n/a

**What is the priority of the bug to you?**
P2

**Environment**
Affects both online playground and CLI, so likely all CI tools too.

**Comment by Sjord** [comment]
Thanks, @ankush, for reporting an issue. I am not sure whether this is a bug or not, but the following pattern seems to do what you want:

```
f("...") + $A + f("...")
```

**Comment by ankush** [comment]
That pattern won't accept this: `f("bar") + var1 + var2 + f("foo")` 

Basically, I am not sure how currently we can write pattern for multiple variables if `+ ... +` doesn't work. Which is why it feels like a bug to me.

**Comment by aryx** [comment]
yes, it's because of the way addition is parsed. + is a left associative operator, so
f("bar")+$A+f("foo") is parsed as ((f("bar')+$A)+f("foo"))) so if you add another +var2 in the code, then it will not match the pattern.
We could treat specially "..." when inside an arithmetic operation and allow it to match multiple terms.
