### ISSUE TITLE
[Internal] Pass the whole rule to semgrep-core in evaluation.py

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2773]
To get semgrep-core -fast, we need to pass the whole rule to semgrep-core, instead of individual patterns like it's the case right now. At some point we also want to pass a big set of rules to semgrep-core at once too, to dedup similar patterns in different rules, but for now let's focus on just passing a whole rule.

This is the most important thing to do to improve the performance of semgrep I think.

We can start by having a --experimental flag to semgrep that use a different code path to pass a whole rule to semgrep-core.
Semgrep-core itself accept a whole rule with the -config <file> flag (instead of the misnamed current -rules_file).

**Comment by aryx** [comment]
cc @mschwager @nbrahms @DrewDennison

**Comment by aryx** [comment]
Note that there are still 28 mismatches between semgrep and semgrep-core -config when used in semgrep-rules, and a few more regressions when using -fast. I need to fix them, but in the mean time we can in parallel work on updating the python wrapper to pass the whole rule to semgrep-core.

**Comment by aryx** [comment]
The only feature not handled by semgrep-core -config is the pattern-where-python, so we may need to keep some of the evaluation.py logic for that, but this should not be too hard because the interface between semgrep and semgrep-core should be similar: semgrep-core will still return a set of matches with metavariables (it's just that it handled the boolean logic composition itself so there's less work in evaluation.py to do).

**Comment by mschwager** [comment]
This seems like a fairly large task, and since it's an internal ask I'm going to remove from the customers board and defer on prioritization (@dlukeomalley, @minusworld, @DrewDennison, @nbrahms?).

This seems like a great start, but I think there's a lot of functionality depending on the current implementation. I'm curious what the plan is for making this transition. We can start dogfooding internally once we have a switch to prefer this implementation, as you mentioned. What's next from there? I would suspect a switch in `semgrep-agent` and/or `semgrep-app`, which we can then use to test it out in real workflows.

Some other non-exhaustive thoughts on what this could affect (we don't necessarily need answers now):

- The `--debugging-json` functionality (`semgrep-app` debugger) depends on the current implemenation.
- It looks like taint mode depends on the current implementation.
  - Maybe we just remove taint mode at this point, but it's a consideration.
- Broader testing ecosystem. `semgrep-rules` tests is a start, but I'm curious about the integration tests in this repository.
  - We can probably just run integration tests side-by-side with the new flag.
- External users. Hopefully testing and dogfooding gets us most of the way, but are we planning to test with external users?

**Comment by aryx** [comment]
I'm down to 13 mismatch in semgrep-rules (down from 28 this morning, and for context there are 2673 rulid: in semgrep-rules, so that's 13/2673 mismatch not bad). I've also fixed all regressions with -start in semgrep-rules, so with or without -fast we now have 13 mismatch

**Comment by aryx** [comment]
I like your transition plan @mschwager. good ideas.
