### ISSUE TITLE
mode taint should be improved minimally to make it somewhat useful

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [semgrep/semgrep#2787]
I have a test case here (which BTW is broken in `0.42.0`+ -- filed separate bug here https://github.com/returntocorp/semgrep/issues/2786) 

Here is a playground that shows basically the only scenario that works.
If the other scenarios listed would be made to work this would make mode taint actually useful...

https://semgrep.dev/s/fproulx-boostsecurity:dom-xss-taint-tracking

**Comment by aryx** [comment]
@IagoAbal want to take a look? Does some work on the IL could fix the issue?

**Comment by fproulx-boostsecurity** [comment]
Basically if the following scenarios (`mode: taint`) were made to work, that would at least allow to implement some injections rules that have a good number of `TPs` and also many `FNs`. But that's a conscious choice, for my use case that's a valid trade off (High Signal / Low Noise). Better to have many good, easy to understand and fix `TPs`, than wasting time on many hard to validate `FPs`, .

```
    // NOT WORKING - Direct use
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: location.hash });

    // NOT WORKING - Mutate before use
    const c = location.hash + "bbb";
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: c });

    // NOT WORKING - Mutate before use - in-line
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: "aa" + location.search });
```

**Comment by IagoAbal** [comment]
Hi! I think it shouldn't take much work to handle these examples. It just probably requires a bit more work on our IL as @aryx is suggesting. I will take a look at it this week!

**Comment by IagoAbal** [comment]
Most of these examples can be make to work by introducing extra temporary variables during AST-to-IL. The dataflow analyses only track facts on simple variables. This is clean and convenient. Perhaps we should consider changing the IL to force some subexpressions to be variables instead.

**Comment by IagoAbal** [comment]
@fproulx-boostsecurity The first examples do not work because the dataflow analysis kind of assumes that the _source_ will be a function, it is expecting something like:

```yaml
pattern-sources:
    - source(...)
```
I will fix that so it works also for sources that are object attributes.

Then the problem with `window.location.href` is that it's basically `(window.location).href` and that doesn't match `location.href`. There could be different solutions to this, but in the meantime, would it work for you having two different patterns `window.location.href` and `location.href` ?

```typescript
    // NOT WORKING - Indirect use with global var
    const b = window.location.href;
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: b });
```

If the only thing you need is that we detect a wrapper function like `dangerous()` as tainted then that we could add fairly quickly. If you need inter-procedural taint analysis that could take longer. We want to add inter-procedural capabilities but this is more work, and it's not in the short-term roadmap yet.

```typescript
    // NOT WORKING - Via intra-file func call
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: this.dangerous() });
```

**Comment by dkasak** [comment]
> I will fix that so it works also for sources that are object attributes.

@IagoAbal Slight tangent, but another thing that would be useful is to be able to specify a *parameter* of a certain function as a taint source. This comes up in various web frameworks where functions of a certain name are automagically called upon a HTTP request, e.g. `resource_POST` gets called when someone `POST`s to `/resource` and receives the request as its first parameter, so that parameter should be tainted.

It's not immediately obvious how to fit into the existing source-specification syntax, though. I'll open a new issue for this if it's something that you think has a chance of being supported (I found this issue while searching whether someone has already suggested it).

**Comment by dkasak** [comment]
> There could be different solutions to this, but in the meantime, would it work for you having two different patterns `window.location.href` and `location.href`?

And to get back on topic, perhaps this could be made to work with [equivalences](https://semgrep.dev/docs/experiments/overview/#equivalences)? So that the patterns don't have to be duplicated.

**Comment by IagoAbal** [comment]
@dkasak please open a new issue and provide some more detail for that use case where a parameter is a taint source, thanks! The best is to use https://semgrep.dev/editor to share the example that you would like to work (but it doesn't). You can assign it directly to me.

Regarding `window.location.href`, yes, I think this could be handled with user-specified equivalences indeed. That may be a better workaround. I was also considering whether this should be built-in, so that `location.href` is equivalent to `this.location.href`, in which case you could instead write a pattern `$X.location.href` that matches both uses.

**Comment by aryx** [comment]
We could use a special metavariable to tag the tainted parameter, e.g. foo($TAINTED,...)

**Comment by aryx** [comment]
But could you give us precise example and
Prcise reference
To API where this would be useful?

**Comment by fproulx-boostsecurity** [comment]
In that case, that's for DOM XSS, client-side with React (provided example), but it could apply to many other scenarios. The fact that this can work at file level, vs function level (for normal match mode) is pretty cool. That's really what I see as the real value, improve those injection rules to work minimally cross-function.

**Comment by IagoAbal** [comment]
The first examples are now fixed: https://semgrep.dev/s/fproulx-boostsecurity:dom-xss-taint-tracking?version=develop
Now finishing up a PR that will add some basic cross-function capabilities!

**Comment by IagoAbal** [comment]
@fproulx-boostsecurity All your examples should now work except for `location.href` still not matching `window.location.href`. I think @dkasak suggestion to use equivalences is a good one, let us know otherwise! Also note that the cross-function support is still very basic, so your example works because dangerous() is defined before render(), if it were defined after then it wouldn't work. Should fix this sometime soon.

@dkasak I would still appreciate if you could open an issue with a concrete example where a given parameter is a source of taint.

**Comment by dkasak** [comment]
ftr, I'm planning to, just a bit busy right now!
