### ISSUE TITLE
[python] Type annotation breaks identifier bindings in metavariables

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2866]
Originally from this Slack conversation: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1617204624073700

The user noted that the following rule isn't working as expected: https://semgrep.dev/s/0xdbe:sequelise_rawquery_engine. I believe the `query` variable on line 2 should produce a finding. However, if we change the `pattern-inside` to `execute(...)` it works as expected: https://semgrep.dev/s/GWOe/.

Digging in to this a bit it seems as though the `query` variable is receiving multiple unique IDs.

In the original `pattern`:

```
{<Range start=63 end=121 metavariables={'$QUERY': 'a23cbedc412eb7f80e4413a0b489a3c9'} propagated={}>}
```

In `pattern-inside`:

```
{<Range start=0 end=144 metavariables={'$QUERY': 3, '$CONNECTION_STRING': '91d58db39beb8d588819b07cc050dfeb', '$ENGINE': 1} propagated={}>}
```

This means metavariable matching on the `$QUERY` variable fails, so the match fails.

Shouldn't the `$QUERY` metavariable have the same unique ID here? cc @aryx

**Comment by nbrahms** [comment]
@mschwager Can you add in the user's priority please?

**Comment by mschwager** [comment]
I didn't get a response for priority from the community Slack

**Comment by nbrahms** [comment]
Looking at https://semgrep.dev/s/Aly0/, it appears that the type annotations cause us to improperly bind the expression hash, rather than the variable AST identifier, to the matched Identifier node.

**Comment by aryx** [comment]
It's because 'query : str = f"stuff"' is parsed as an Assign (Cast(str, Id query), String "stuff")
and so $QUERY matches the whole Cast expression, not just just the Id.
For other languages we don't have the problem because variable declarations and assignments are different constructs
(e.g., let x : int = 1;  vs x = 1) and when we match variable declarations, we allow a variable declaration without a type to also match a variable declaration that specifies a type.

**Comment by aryx** [comment]
Thx matt and nathan for the hints of what was wrong.
