### ISSUE TITLE
Invalid pattern capture with parenthesis for Python

### ISSUE THREAD

**Issue by sangwoo-joh** [semgrep/semgrep#2902]
**Describe the bug**
When capturing patterns for Python, semgrep ignores parenthesis matching in some cases.

**To Reproduce**
For the code below:

```python
    if cond(1, 2, z) or not (z(x) is k(y)) or cond333(3 ** x):
        return
```

Pattern: `not $X is $Y`

**Expected behavior**
Do not capture the `not (z(x) is k(y))`, because it is `not ($X is $Y)` pattern.

Since it captures the last closing parenthesis `)` wrongly, it is impossible to write a safe autofix rule to fix this pattern to `$X is not $Y`.

**Screenshots**
![image](https://user-images.githubusercontent.com/15664082/113983393-d44f3d80-9884-11eb-995e-5c7d71977f04.png)
As you can see the screenshot, it wrongly captures `not (z(x) is k(y)` **ignoring** the last closing parenthesis `)`.

**What is the priority of the bug to you?**
If this behaviour is pervasive in Python, it should be fixed quickly.

**Comment by brendongo** [comment]
@aryx seems like a matching/python parsing issue rather than autofix?

**Comment by brendongo** [comment]
Hi @sangwoo-joh looks like this might be a little difficult to fix because we currently don't keep track of noop parenthesis in our parser (doing so allows us to treat `not a is b` as semantically the same as `not (a is b)`) so the fix will be a bit complex in the autofix side.

A rule like https://semgrep.dev/s/zk50 that leverages pattern-inside might get you the right autofix while this issue remains.

**Comment by sangwoo-joh** [comment]
Hi @brendongo , thanks for your update!
I will use the pattern-inside rule until the issue will be fixed.
Thank you!

**Comment by nmote** [comment]
Reproduction in the playground: https://semgrep.dev/s/20WB
