### ISSUE TITLE
Provide a LICENSE file along with pypi release

### ISSUE THREAD

**Issue by priv-kweihmann** [semgrep/semgrep#2957]
Currently it can only be assumed from meta data under what license the pypi release is shipped.
INAL but I think LGPL somehow requires to ships the LICENSE text along with a release, which isn't the case if just pulled from pypi

**Comment by brendongo** [comment]
Will go in the next release @priv-kweihmann thanks for filing the issue

**Comment by pombredanne** [comment]
Related to this in https://github.com/returntocorp/semgrep/blob/4b39218cf63987d657c5e1b79f81d41fce6e2057/semgrep-core/src/datalog/Datalog_experiment.ml and a few other places there is this notice:

>  * This library is free software; you can redistribute it and/or
>  * modify it under the terms of the GNU Lesser General Public License
>  * version 2.1 as published by the Free Software Foundation, with the
>  * special exception on linking described in file license.txt.
>  *
>  * This library is distributed in the hope that it will be useful, but
>  * WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the file
>  * license.txt for more details.


... yet I could not find a license.txt nor any reference to the exception in question

There is one in coccinelle at https://github.com/coccinelle/coccinelle/blob/master/license.txt but this is GPL so that should not be it.

And another one in https://github.com/returntocorp/pfff/blob/8ed7f8575ae8d9b2ff0d587f6258df701775f3fa/license.txt which seems to be it on the surface of it?

Generally speaking do you also have the LGPL static linking exception overall?

**Comment by priv-kweihmann** [comment]
I think this one needs to be reopened. I don't see any LICENSE file in https://files.pythonhosted.org/packages/3c/3b/5013024534e36d2f999b75c99250061524192c3aba9b4a7e2062d95462a0/semgrep-0.66.0.tar.gz

**Comment by brendongo** [comment]
Oh yeah I'll reopen and take a look

**Comment by brendongo** [comment]
Looks like the license is included in the wheel files but not the source tarball
