### ISSUE TITLE
Can't use ellipsis in Java { } structure

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3001]
I expect that 

```
          @ApiResponses(value = { ..., @ApiResponse(responseCode = "404", ...), ... })
          $T $F(...) {
            ...
          }
```

is a valid semgrep pattern, but it is not. Changing it to `@ApiResponses(value = { @ApiResponse(responseCode = "404", ...) })` works fine though. Live example: https://semgrep.dev/s/J37y

**Comment by aryx** [comment]
dupe of https://github.com/returntocorp/semgrep/issues/2996?

**Comment by aschilling** [comment]
The workaround via `@ApiResponses(value = { @ApiResponse(responseCode = "404", ...) }) ` does not work properly, as soon as there is a comma at the end of the API response, see [https://semgrep.dev/s/lj8E](https://semgrep.dev/s/lj8E). In this example, a match is detected because the sample occurrence ends with a comma, which is is identified as a non-match by the ellipsis operator. Because of pattern-not-inside a match is detected, although it should not be a match.

The difference to [#2996](https://github.com/returntocorp/semgrep/issues/2996) is that the referenced issue concerns the misbehaving pattern operator while this issue concerns the misbehavior of the ellipsis operator.

**Comment by nbrahms** [comment]
@ievans What's the priority of this issue for you?

**Comment by ievans** [comment]
@nbrahms was reported by an external user, see https://r2c-community.slack.com/archives/CK86BJ5DW/p1619455010337100

**Comment by aschilling** [comment]
Hi I think this is a rather important issue which prevents semgrep for Java usage. Today, annotations are commonly used to configure runtime behavior, therefore such configurations are rather common and thus I think the priority of this issue should be high.

**Comment by aryx** [comment]
ok, bumping the priority

**Comment by aryx** [comment]
so @emjin and @chmccreery you're on this right?

**Comment by chmccreery** [comment]
Yes! @emjin shall I put time on our calendars for today? Or next week?

**Comment by emjin** [comment]
Next week? Getting a bit late for me today
