### ISSUE TITLE
Show which files are currently processed in --debug mode

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3220]
context: https://r2c-community.slack.com/archives/CK86BJ5DW/p1622147935097300

right now if semgrep-core segfaults on a file, there is no easy way to know what was the file in the error messages.
People resorts to:
```
Don't know how big the repo is and if you have tried this already, but for places where semgrep was barfing on the file itself, I had reasonable success going with a simple pattern ('$X = $X') and then just trying different files and folders and file extensions in a binary search to quickly zero down the file with the issue. Moving to a simple pattern also meant that debug output was much more tractable
```
which is not good.

The --debug mode should display the rules x files pair being currently processed.

**Comment by aryx** [comment]
related: https://github.com/returntocorp/semgrep/issues/3044

**Comment by mschwager** [comment]
While reviewing some other changes I noticed that `semgrep-core` debug functionality is enabled via the `--debugging-json` flag, not `--debug`: https://github.com/returntocorp/semgrep/pull/3154#issuecomment-845270231. I suspect this is a bug due to the confusing nature of `OutputSettings.debug`.

**Comment by aryx** [comment]
@brendongo I think one of the issue is that we capture the stdout/stderr of semgrep-core python side, and display its content only after semgrep-core terminated; we should display its content as we go.

**Comment by brendongo** [comment]
So right now, the way we use subprocess in python waits until the process is finished before it returns and has the stdout and stderr of the subprocess. There are two ways around this: 

(1) if we don't capture stderr in the subprocess, it will go straight through to stderr without having to wait. This would mean we have to be more attentive to what gets printed out to stderr in semgrep-core since it will always get printed out.

(2) There is probably a way to use the underlying subprocess.Popen and poll the subprocess as it is running. Normally you will need a multi threaded approach so you don't get into a deadlock trying to do a blocking read on stderr when the subprocess is trying to print a lot onto stdout. But I think with the simplifying assumption that semgrep-core only ever prints to stderr and just once at the end on stdout we might be able to get away without having to use threading. 

- https://fabianlee.org/2019/09/15/python-getting-live-output-from-subprocess-using-poll/
- https://www.endpoint.com/blog/2015/01/28/getting-realtime-output-using-python
- https://stackoverflow.com/questions/18421757/live-output-from-subprocess-command

**Comment by aryx** [comment]
@brendongo can we fix that? I think it will really help to debug those segfault, to at least
get the last file that was processed.
semgrep --debug should currently display the list of analyzed file.

**Comment by aryx** [comment]
Ok, just thought about it again. What about we simply do (1) and not capture stderr in the subprocess when in --debug mode? That way in normal mode we capture it and avoid issues where semgrep-core prints stuff on stderr by mistake, and in --debug mode anyway we don't care about those mistakes.

**Comment by brendongo** [comment]
yeah that makes sense @aryx
