### ISSUE TITLE
Generic/autofix Metavariable Name Issue

### ISSUE THREAD

**Issue by haydenplemmons** [semgrep/semgrep#3458]
**Describe the bug**
When applying autofixes, uses metavariable with shortest name instead of the actual variable referenced. 
set $B, autofix will never use a variable named $BA or $BAR, it will fill in that $B first.

**To Reproduce**
https://semgrep.dev/s/xePj

**Expected behavior**
We would expect it to use the variables that I give it, read the whole variable name, not just the first matching characters

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Currently local, ultimately it will be a gitlab pipeline involving a docker image

**Comment by jtimmons** [comment]
I ran into this as well in a similar situation and debugged a bit. Seems that during the message/autofix string interpolation the set of metavariables are just looped over in no particular order and replaced - this means that if the shorter metavariable name is hit first then it'll replace that first. An easy way to avoid these types of collisions this would be to just replace the metavariables in length order so that the longer variable would be handled before the shorter.

I can take a stab at fixing tomorrow if people agree with the approach above, it's a minor annoyance but could be good to avoid someone else's confusion in the future

**Comment by emjin** [comment]
That seems like a good solution! You're very welcome to make a fix
