### ISSUE TITLE
Expressions forming python decorators aren't matched ('@foo', '@foo()', '@foo.bar()')

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3489]
Using metavariables in Python `from ... import ...` style imports misses decorator usage of the metavariable.

See here: https://semgrep.dev/s/jk4y

![image](https://user-images.githubusercontent.com/343265/125345631-a22efb00-e30d-11eb-9977-0b06ea78975e.png)

**Comment by mschwager** [comment]
Looks like this is not just imports, it's any metavariable defined in a separate pattern and used in a decorator call: https://semgrep.dev/s/1Ggl. If we take away the decorator in the pattern it works as expected: https://semgrep.dev/s/96n2.

**Comment by jtimmons** [comment]
Just hit this as well, looks like it's not specific to the python language either. Here's an example of looking for methods within a class in TS:
  - If we include the class as part of the match then it works fine: https://semgrep.dev/s/kkPO
  - But, if we make the match more specific to the method being inside the class then it fails: https://semgrep.dev/s/w12N
  - Similarly, removing the decorator from the method match works correctly now: https://semgrep.dev/s/xe20

**Comment by mjambon** [comment]
I reduced the example to this: https://semgrep.dev/s/pkqJ

![image](https://user-images.githubusercontent.com/343265/125346987-39e11900-e30f-11eb-82ae-3e4fd15df7ba.png)

Expressions in decorators are not matched, but the user expects them to be matched.

**Comment by aryx** [comment]
This is because an expression pattern currently can't be used to match a decorator, because in many languages
the decorator is not an expression but a special kind of calls, with many restrictions.

**Comment by aryx** [comment]
you need to write it like this:
https://semgrep.dev/s/Gwv1/

**Comment by aryx** [comment]
You need to also put the def because you can't currently match just a decorator
(we could change that though).

**Comment by aryx** [comment]
So this has nothing to do with metavariable; It's just that an expression pattern does not currently match a decorator,
so you are forced to explicitely set a decorator context by using @expr first, and then we don't accept single decorator pattern so you are forced again to attach it to an entity like a function

**Comment by mschwager** [comment]
> you need to write it like this:
> https://semgrep.dev/s/Gwv1/

Nice! This works for my use-case. Although I still find it surprising that if I specify `foo.bar` it doesn't match `@foo.bar`. I suspect other users would find this surprising as well. It may be worth considering adding this use-case :+1:

**Comment by IagoAbal** [comment]
Should we turn this issue into a feature request or should we close it? @mschwager @jtimmons

**Comment by IagoAbal** [comment]
@aryx we could change `| NamedAttr of tok (* @ *) * name * arguments bracket` to `| ExprAttr of Tok * expr` perhaps? We don't need to change the parsers, just their encoding into Generic.

**Comment by aryx** [comment]
I'm a bit reluctant to change to the more general ExprAttr. In almost all languages there are strong restrictions on what can go in an attribute, so I prefer to be more precise. But maybe we could do like vardef_to_assign, and dynamically convert some of those NamedAttr to expression if someone is looking for an expression and it turns out it matches a named attribute.

**Comment by aryx** [comment]
Closing for now.

**Comment by huonw** [comment]
We're hitting the fact that decorators aren't considered function calls too, because we're wanting to flag certain strings unless they appear in particular function calls. https://semgrep.dev/s/WpeE is a reduced example; I can't work out how to use `pattern-not-inside` to silence the error for A, without also silencing it for B. Any progress here? (Or tips for my specific rule?)

---

The real use case: we kept _trying_ to do an f-string substitution like `f"foo {variable} bar"` but forgot the `f`, so we've written a semgrep rule that looks for `{...}` inside strings without the f. However, this rule conflicts with web API frameworks like FastAPI that uses strings and `{...}` for path parameters, like:

```python
import fastapi

app = fastapi.FastAPI()

@app.get("/entity/{id}") # A
def f(id: int) -> str:
    return "entity: {id}" # B

...
```

We want to avoid flagging every single path parameter like A, but continue to flag mistakes like B, which requires filtering out the matches that are within `FastAPI(...).$METHOD(...)` calls.

**Comment by IagoAbal** [comment]
We could then add that equivalence to see attributes as function applications as @aryx suggested. I believe this shouldn't be hard.
