### ISSUE TITLE
returntocorp/semgrep-agent:v1 image not working

### ISSUE THREAD

**Issue by timfeirg** [semgrep/semgrep#3500]
**Describe the bug**

"semgrep-agent": executable file not found in $PATH

**To Reproduce**

![image](https://user-images.githubusercontent.com/4319104/125117276-9500e900-e120-11eb-9713-6dfcd0a8b6d4.png)

**Expected behavior**

semgrep-agent runs normally

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

using returntocorp/semgrep-agent:v1

**Comment by underyx** [comment]
Hey @timfeirg! Is it possible that you tried semgrep-agent a long time ago, before we added the command alias? Maybe you just need to run `docker pull returntocorp/semgrep-agent:v1` before running this command. For the record, I cannot reproduce the issue with the same command, probably because of that.

**Comment by timfeirg** [comment]
I pulled the image yesterday but it was through a chinese mirror, the mirror itself was outdated, sorry for the trouble, it was a china problem.

**Comment by underyx** [comment]
Thanks for reporting back! And wow, that's a fascinating issue, it's the first time I definitely heard of this problem with docker images! All the more reason for us to start semantically versioning semgrep-agent 🤔
