### ISSUE TITLE
Investigate perf regression between 0.55.1 and 0.58

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3520]
Many PRs done after 0.57 got some random perf regressions reported by the bot-action.
It's hard to pin at a specific PR because many of those PR don't even modify OCaml code but still got
perf regressions.

I had to reset the baseline to 0.57 just before I released 0.58, but we were seeing sometimes
some > 12% perf regressions (mostly on small bench < 10s).

**Comment by aryx** [comment]
see https://github.com/returntocorp/semgrep/pull/3519

**Comment by aryx** [comment]
see https://github.com/returntocorp/semgrep/pull/3516 that had lots of perf regressions reported (even though it was just
a refactoring diff).

**Comment by emjin** [comment]
Putting priority:high because the longer this is put off, the less we will remember what we did during this period. We should either investigate soon or we won't investigate at all.

**Comment by IagoAbal** [comment]
Are we sure that these are really perf regressions rather than just noise? My impression is that it was somewhat random, #3516 looks like an extreme case and I believe that did not happen very often. Then we had fine-tuned the alarms in different ways, I think now we don't report deviations of less than 20%.

Just looking at the first ones reported:
- 4.105 vs 3.73
- 3.257 vs 2.785
- 21.864 vs 19.805
- ...

Do our perf tests run on a dedicated CPU? Or is it a shared CPU? If I run Semgrep on my machine while I run other stuff I also get few second differences between runs.

**Comment by aryx** [comment]
nobody is gonna fix that ... closing.
