### ISSUE TITLE
Can't suppress with // nosemgrep because of autoformatter

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3521]
I can’t use //nosemgrep because my autoformatter moves it to its own line, where it is ignored by semgrep. 

To reproduce: https://semgrep.dev/s/340G
Desired behavior: I'd like all of the examples in the above snippet to be suppressed by the `nosemgrep` annotation, including:
* where `nosemgrep` is on its own line before the target line
* where `nosemgrep` is inside the matched range.

This is currently blocking me from merging my PR.

cc @mschwager @minusworld curious if you have thoughts

**Comment by mschwager** [comment]
I agree, this limitation is often painful. Ideally, it'd be great if we could support all the different "ignore annotation" styles of something like `eslint`, but there are a few considerations. The fundamental difference with Semgrep here is that Semgrep findings often span many lines, and will have many overlapping spans across findings. I see a couple challenges

1. Coordinating a specific `nosemgrep` rule ID with a specific finding becomes difficult. I.e. if I'm looking at a `nosemgrep` comment in code, and it's a finding spanning many lines, how do I know where the finding starts? What if it's 50 lines away?
2. Blanket `nosemgrep` ignores become very far-reaching. E.g. a blanket `nosemgrep` in a `class` somewhere will ignore _all_ potential findings spanning that class (same for functions, etc).

Overall I'm supportive of improved functionality here, but I think we have to be careful of unintended consequences. It'd probably be a good idea to map out exactly which forms of `nosemgrep` we'll accept, and how blanket and specific (rule ID specified or not) exemptions interact with finding spans.

Another orthogonal, but relevant consideration: is it time to move `nosemgrep` functionality into `semgrep-core`? That would allow us to properly analyze language-specific comments rather than use a blanket text-based regex. That may make other `nosemgrep` functionality improvements easier :+1:

**Comment by mschwager** [comment]
Could we get 90% of the value here by looking for `nosemgrep` comments on the same line N, and N-1? I think that would cover the autoformatter case.

**Comment by nbrahms** [comment]
> Could we get 90% of the value here by looking for `nosemgrep` comments on the same line N, and N-1? I think that would cover the autoformatter case.

I can imagine some gross edge cases:
```py
exec(false_positive_input)  # nosemgrep:noexec
exec(true_positive_input)
```

I'd propose maybe
```py
# nosemgrep-next-line:noexec
exec(false_positive_input)
```

**Comment by ievans** [comment]
@nbrahms I like that proposal but it does add some complexity in "what you have to remember beyond "nosemgrep".

What if `nosemgrep` on a line with only that and whitespace suppresses the next line? Any edge cases we can imagine for that?

**Comment by nbrahms** [comment]
@ievans I think that would work too. Mostly I'm thinking of trying to get parity with other linters so the user mental model is nothing new. Cf. `eslint-disable-next-line`.

**Comment by nbrahms** [comment]
Another possibility would be to push `nosemgrep` to `semgrep-core`, and have it work on the next _statement_. This could help in instances like:

```py
db.execute(
  "my crazy sql query with" +
  user_input
)
```

cc. @aryx

**Comment by dlukeomalley** [comment]
Speaking with a Semgrep user today, they've run into pain when they run 1+ scanning tools that both fire in the same region and/or on the same starting line: they have to choose between suppressing Semgrep or the other tool (eslint iirc) because both tools require the suppression comment to be on the proceeding line. 

What was the rationale for not respecting rule-id specific `nosemgrep` comment (i.e. `// nosemgrep foo.baz`) anywhere within the match body?

My crazy idea: **deprecate nosemgrep in favor of a centralized ignore/finding file.**

Why I like this:
1. The ignore file can record a rule’s UUID, so it’s safe across rule name changes (a current pain point for us migrating rule names)
2. It’s still checked into the codebase and human readable, so during PRs people can review what was suppressed
3. Using CLI command for suppression let’s Semgrep users provide a suppression reason from a set list of reasons. If they allow that to be shared anonymously the rule authors in the community could get amazing aggregate feedback on their rule. We could also then guide people towards other ways of handling the FP, like adding the path in question to `.semgrepignore`.
4. We’ve gotten many “baseline” scanning requests lately from sec eng folks, so this unifies parts of the sec eng and dev flow. Bento did this with success ([sample](https://github.com/returntocorp/bento/blob/master/.bento/archive.json)).
5. It’s universal and works across languages!

What I don’t like:
1. I have to use Semgrep CLI to suppress
2. Suppressions aren’t inline, so I don’t discover them as I’m reading code (solvable with good IDE integrations that show results inline?)
3. It deviates a bit from existing tools

Taking this further, I’d augment the Semgrep CLI findings output, PR comment format, etc. to include a UUID for any specific result so users have an easy line to copy paste, like `$ semgrep mute 2`

**Comment by zakrush** [comment]
@dlukeomalley There is one more problem in your description. What to do if the code left the line that was in the file .semgrepignore? I have problems with the semgrep that the code goes away, and every time new triggers on the same alert. Developers don't want to setup comments, becouse the comment will can go away from muted code.

**Comment by mschwager** [comment]
> My crazy idea: deprecate nosemgrep in favor of a centralized ignore/finding file.

Copying in some further comments from Slack:

> There's a lot of value in seeing the ignore immediately next to the offending code. Having to cross-reference a separate file or use some non-standardized tooling seems like a huge pain.

**Comment by dlukeomalley** [comment]
Related: https://github.com/returntocorp/semgrep/issues/3153

**Comment by zwass** [comment]
Next _statement_ (ignoring comments) seems like an appealing option to me. I notice for example that eslint's `eslint-disable-next-line` does not ignore comments and that means it _must_ be the last comment before the line. If semgrep has the same limitation then both options will not be usable for suppression (though this can be worked around by eslint's disabling through a block, which I'd rather not do).

**Comment by malexmave** [comment]
+1 for "Next line that contains more than comments and a whitespace" being a nice semantic, also for writing rule test cases where the `ruleid`, `ok`, `todook` etc. are currently also mutually exclusive if I am not mistaken.

**Comment by aryx** [comment]
I would vote for //nosemgrep alone on its line means implicitely //nosemgre-next-line, and //nosemgrep with some code before mean this line.

**Comment by zwass** [comment]
Another important property of this applying to the next statement (ignoring comments) is that we can then add comments explaining why the ignore was put in place

```
// nosemgrep
// this is not a security issue because blah blah blah
os.Exec(args)
```

**Comment by underyx** [comment]
When solving this, please test whether semgrep-agent still understands which findings are ignored right and whether semgrep-agent sees the same source code for the finding before and after ignore.

Currently semgrep-agent has to resort to a brittle hack to be able to recognize that the finding is identical before and after ignoring, because adding an inline nosemgrep comment changes the source code (syntactic context) of the finding. To achieve this, semgrep-agent strips nosemgrep comments from matches with a regex. This could break in any number of ways 😬

**Comment by nbrahms** [comment]
> I would vote for //nosemgrep alone on its line means implicitely //nosemgre-next-line, and //nosemgrep with some code before mean this line.

Explicit is always >> implicit IMO. We can always surface a warning if there's no text before a bare `nosemgrep`.

**Comment by mjambon** [comment]
This feature seems important but hard to do if we want to be completely clean. I see two main options:

### A: Simplified but easier way, in python

Implements the following:
* a nosemgrep comment alone on a line applies to the next line.
* a nosemgrep comment followed by code on the same line applies to that line.
* a nosemgrep comment preceded by code on the same line applies to that line.

The limitation of this scheme is that it doesn't play well with other comments, but it should be better than what we offer now and compatible with the more complete solution described below.

### B: More elaborate way, in ocaml

Implements the following:
* a nosemgrep comment applies to the piece of code that follows it, skipping over other comments and whitespace
* ... unless it follows code on the same line in which case the nosemgrep applies to this line.

This solution B requires correct discrimination between comments, whitespace, and (significant) code, which can be achieved properly with each language parser, but needs a bit of work. The tree-sitter parsers normally provide comments but we need to not discard them (https://github.com/returntocorp/ocaml-tree-sitter-core/issues/2). All this will be probably be more work than solution A.

### Notes

The original example given by @ievans (https://semgrep.dev/s/340G) is
```js
function foo() {

  alert( 
      // nosemgrep
  'hi this is a long text that the autoformatter will force onto its own line ok see the problem now'
   );

     alert(       // nosemgrep
  'hi this is a long text that the autoformatter will force onto its own line ok see the problem now'
   );
}
```
where all the nosemgrep comments should prevent a match on `alert(...)`.

The autoformatters will move comments in ways that are hard to predict in general, but we assume that either
* the comment will stay within the region matched by semgrep
* the comment will be hoisted up to just before the region matched by semgrep

If an autoformatter moves comments below the original line, the nosemgrep comment will no longer apply to the correct line. This can usually be circumvented by placing the comment before the target code rather than in a trailing position. Otherwise, see below.

### Last-resort measure

If some autoformatters are too weird, we could offer another kind of nosemgrep comment that's still easy to use and disables matches on a broader region. Perhaps something like `nosemgrep~5` could disable any matches in the range [current line - 5, current line + 5].

Such feature could also be abused to disable semgrep on a whole file, by writing `nosemgrep~10000`.

**Comment by IagoAbal** [comment]
I believe we should keep it simple and in Python.

Should `nosemgrep` inside a matched region disable the match? It would do the job here:
```
alert(
   // nosemgrep: rule-id
  'alert text'
);
```

Also, as last resort, `nosemgrep+5` could disable the next 5 lines, or `nosemgrep-5` could disable the previous 5 lines. Probably you only need the `+` version.

**Comment by mjambon** [comment]
New proposal, in two independent and compatible parts A and C. A is the same A proposal as earlier. The earlier B proposal was dropped. Both A and C should be implementable from python.

### A: nosemgrep comment applies to current line or next line

Implements the following:

* a nosemgrep comment alone on a line applies to the next line.
* a nosemgrep comment on the same line as code applies to the current line.
* `nosemgrep: my-rule, my-other-rule` disables just the specified rules.

The keyword `nosemgrep` is what's in use currently, so we're keeping it.

### C: semgrep-on/semgrep-off blocks

This allows disabling semgrep matches on multiple lines:

```
/* semgrep-off */
something();
more_stuff();
/* semgrep-on */
```

Features:
1. an unmatched `semgrep-off` or `semgrep-on` is reported as an error.
2. a semgrep-off comment that follows code on the same line is an error due to possible confusion with the trailing nosemgrep comments. `foo(); # semgrep-off` is illegal.
3. a pair of `semgrep-off:my-rule` and `semgrep-on:my-rule` disables just the specified rule `my-rule`. Multiple rules can be specified as a comma-separated list e.g. `// semgrep-off: my-rule, my-other-rule`.
4. the whole semgrep-off/semgrep-on feature is marked as experimental and subject to change or removal.
5. [detail] a semgrep-off or semgrep-on comment may not be on the same line as significant code. This is because it makes the code clearer and it's a simpler rule to remember than rule (2) above, which it extends.
6. [detail] non-nested overlaps are tolerated e.g. the following is accepted (because it's easier to implement?):
```
// semgrep-off: foo
...
// semgrep-off: bar
...
// semgrep-on: foo
...
// semgrep-on: bar
```

**Comment by clintgibler** [comment]
Love the discussion on this thread 👍  A few comments/thought:

### Block Comments
The block comments (`semgrep-[off|on]`) are an interesting idea, I hadn't thought of that before. 

One comment on this: I feel like the current naming is unintuitive, though contextually it makes sense; that is, turning *on* the ignoring with `semgrep-off`.

```
// semgrep-off

... you've enabled something to make Semgrep behave differently here ...

// semgrep-on

... wait, is something happening between this on and off block? No, it's the opposite

// semgrep-off

...
```

When users think about it and read the docs, they will get it, but maybe we can make it more obvious, like:

```
// semgrep-ignore-on or semgrep-ignore-enable

...

// semgrep-ignore-off or semgrep-ignore-disable
```

Slightly more verbose, but less confusing in my opinion.

### Non rule-specific ignores should be considered an anti-pattern

There's been a few examples in this thread about blanket `nosemgrep` comments that will ignore anything on a line or region.

I ignoring any rule firing on a line or region should be considered an antipattern, and if we wanted to be really strong about it, remove this functionality, requiring every `nosemgrep` to specify one or more rule IDs.

Why?

Say one day you ignore a line because Semgrep is complaining about some style or best practice thing.

Then later the code changes, things get moved around, and now there's a critical security vulnerability there. Will you notice? No, because you're blanket ignoring findings there.

While this may be unlikely to happen in practice, I think ignoring any rule firing in a context/LOC would make an AppSec engineer nervous.

*Sidenote*: it'd be interesting to surface users when there's a `nosemgrep` that's not filtering out a finding. That implies the code has changed and there's no longer an issue. If we don't do that already, we should.

### Centralized ignore file vs inline ignores

[Brakeman](https://github.com/presidentbeef/brakeman) uses a centralized ignore file:

> By default, it looks for a configuration file in `config/brakeman.ignore`. To create and manage this file, use: `brakeman -I`.

This has the benefit of making it easy to review all the ignores in one place, and we can nicely capture "why" as well. 

There are definitely UX benefits of inline though.

### Who is allowed to ignore findings?

AppSec engineers at multiple companies have mentioned to me that they'd like to be the only ones who can ignore Semgrep findings. Perhaps developers can propose ignores, but that goes to the AppSec team for approval. 

Other companies are OK with devs self-servicing but want to periodically review what's been ignored (e.g. maybe have an alert to the `appsec` Slack room when a new ignore is added.

We may want to have some sort of Semgrep ignore triage or approval flow.

CC @dlukeomalley Also, "only allow ignores from the App" could be an interesting App / Teams feature.

### tl;dr

Channeling my product hat (🙇  @dlukeomalley), regardless of the specific implementations, I think the user outcomes I've tried to outline above are:
* There should be some way to onboard a repo (a la Bento): run Semgrep with some rules, and then it walks you through each finding, and you can choose to ignore that finding (and specify a reason), disable that rule, or keep it.
    * This could be a "wizard", a la Brakeman.
* We should push (/force) people to use rule-specific ignores. Blanket ignores seem dangerous or at least not ideal.
* There needs to be a way to easily show: these are all of the ignores my code base has, e.g. `semgrep --show-ignored`
    * Yes you can use `grep`, but Semgrep should make that easy because we know our ignore syntax.
* Ignoring findings - Different orgs will want to handle this differently. Some want devs to do it, others want the AppSec team to be the only ones who can ignore findings. (there may also be compliance requirements for this)
   * Central management and review of ignores could be a valuable App feature.

**Comment by clintgibler** [comment]
@minusworld Comments from Slack:

> I think my preference would be something explicit rather than implied; ESLint does this with `// disable-eslint-next-line` and `// disable-eslint-previous-line` or whatever the specific words are. Makes it really clear where the suppression should apply; behavior that deviates is clearly a bug.

> My thought for a while now has been to just copy ESlint. They seem to do it pretty well.

> @nbrahms’s proposal seems to fit this well enough from my read of the thread, although it would require remembering to turn `semgrep-on` back on. iirc ESlint supports both block suppression and line suppression, fwiw

**Comment by nbrahms** [comment]
Specific eslint names: https://eslint.org/docs/user-guide/configuring/rules#using-configuration-comments-1

@clintgibler I'd warn against things like `semgrep-ignore-disable`. Let's not use no double negatives never ;) This is why `eslint` has the simple `eslint-enable` & `eslint-disable`.

**Comment by mjambon** [comment]
To avoid the confusion introduced by double negatives, perhaps begin/end is a better language than on/off. It would give us something like this:
```
...
// begin-semgrep-ignore: my-rule
...
// end-semgrep-ignore: my-rule
...
```
or
```
...
// begin nosemgrep: my-rule
...
// end nosemgrep: my-rule
...
```

**Comment by mjambon** [comment]
@clintgibler 
> There should be some way to onboard a repo (a la Bento): run Semgrep with some rules, and then it walks you through each finding, and you can choose to ignore that finding (and specify a reason), disable that rule, or keep it.
> This could be a "wizard", a la Brakeman.

I think I would appreciate that if I were a developer dealing with false positives.

> Ignoring findings - Different orgs will want to handle this differently. Some want devs to do it, others want the AppSec team to be the only ones who can ignore findings. (there may also be compliance requirements for this)
> Central management and review of ignores could be a valuable App feature.

I don't know how this should be implemented but it makes a ton of sense to me.

**Comment by aryx** [comment]
@mjambon did you see the comment @underyx had on semgrep-agent above?

"When solving this, please test whether semgrep-agent still understands which findings are ignored right and whether semgrep-agent sees the same source code for the finding before and after ignore.

Currently semgrep-agent has to resort to a brittle hack to be able to recognize that the finding is identical before and after ignoring, because adding an inline nosemgrep comment changes the source code (syntactic context) of the finding. To achieve this, semgrep-agent strips nosemgrep comments from matches with a regex. This could break in any number of ways grimacing"

**Comment by mjambon** [comment]
@aryx thanks for the heads-up, I hadn't realized that. I just asked @underyx to take a look at https://github.com/returntocorp/semgrep/pull/4535

**Comment by mjambon** [comment]
https://github.com/returntocorp/ocaml-tree-sitter-core/pull/48 will allow us to parse comments correctly in the languages parsed with tree-sitter. This will allow for a more accurate and correct inspection of comments if desired. The current hack used for the implementation of nosemgrep is likely to stay in place for the time being, though.
