### ISSUE TITLE
YAML string matching metavars are off by one character

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#3572]
**Describe the bug**

See here how the metavar matching highlight is off to the left by one character.

<img width="190" alt="Screen Shot 2021-07-21 at 18 57 48" src="https://user-images.githubusercontent.com/1060436/126520699-47299664-35e7-4f2b-a814-def8959fe59d.png">

**To Reproduce**

https://semgrep.dev/s/underyx:yaml-metavar-repro

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by underyx** [comment]
Bumping to P1 because this makes metavariable-regex rules impossible or possible only with a super ugly workarounds (of adapting regex patterns to the last character being cut off)

**Comment by IagoAbal** [comment]
Off by one, or off by two characters?

**Comment by underyx** [comment]
@IagoAbal good question. could be off-by-two if the quotes are meant to be matched as well.

**Comment by harold-stripe** [comment]
Actually yes this is right, off-by-two

But should we actually need to match the quotes?
In YAML
```yaml
test:
  - "exp"
  - 'exp'
  - exp
```
These 3 are equivalent. If I want to do a Regex, should I actually need to add ['"]? in front and at the end of all my expressions? Quotes can be added by dev just because they like it or because they use a symbol/expression that forces them to. (🇳🇴 being the best example)
I think it would be nicer if when doing rules, I don't need to think strings in simple of double quotes.

**Comment by underyx** [comment]
Actually I think in other languages we support `"$VAR"` instead of `$VAR` to capture string contents instead of the full _thing_.

**Comment by harold-stripe** [comment]
That would be really great!

**Comment by emjin** [comment]
Ah, I suspect this actually is an off-by-one error, because of how the YAML parser we use interprets strings. This is slightly annoying (basically, the YAML parser is smart and gets rid of extra information when parsing literals, but we actually want the extra information). @underyx Do you think it would be reasonable to have `$X` match `123` in this case for YAML?

**Comment by erwanlr** [comment]
Same issue in PHP btw: https://semgrep.dev/s/34Pr

**Comment by enncoded** [comment]
I was trying to make the owasp metadata tags in the rules more consistent by turning each one with a string value to a length 1 array and encountered this issue.

This current issue is making it harder for me to update this rule: https://github.com/returntocorp/semgrep-rules/blob/develop/yaml/semgrep/metadata-owasp.yaml

**Comment by brandonspark** [comment]
I'm pretty sure I fixed this some time ago in https://github.com/semgrep/semgrep/pull/6724. Closing this issue.
