### ISSUE TITLE
Improve PHP parse rate to beta percentage

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3576]
[PHP currently has](https://semgrep.dev/docs/status/):

- All Semgrep beta features
- A 10+ rule ruleset: https://semgrep.dev/p/phpcs-security-audit
- 97% of 99% beta parse rate

If we can bump up this last 2% parse rate we can promote it to beta!

**Comment by mschwager** [comment]
Some fodder here:

- https://github.com/returntocorp/semgrep/issues/2648
- https://github.com/returntocorp/semgrep/issues/2650
- https://github.com/returntocorp/semgrep/issues/3587
- https://github.com/returntocorp/semgrep/issues/3588
- https://github.com/returntocorp/semgrep/issues/3589
- https://github.com/returntocorp/semgrep/issues/3590
- https://github.com/returntocorp/semgrep/issues/3591
- https://github.com/returntocorp/semgrep/issues/3592

**Comment by Sjord** [comment]
Do you want to improve the built-in PHP parser, or switch to tree-sitter?

**Comment by mschwager** [comment]
> Do you want to improve the built-in PHP parser, or switch to tree-sitter?

Hmm, that's a good question. @aryx will have a much better idea about the best path forward here.

**Comment by aryx** [comment]
I think we should switch to the tree-sitter one. Note that Slack added support for Hack, which is kinda a superset of PHP.
They could have defined tree-sitter-hack as an extension of tree-sitter-php but didn't, because they said Hack and PHP diverged and it was more pain to make Hack an extension. Anyway, tree-sitter-php should be easy to integrate, it's just lots of boilerplate code to write.

**Comment by Sjord** [comment]
The tree-sitter-php grammar doesn't parse string interpolation correctly yet. E.g. `"hello {$planet["a"]}"`. @cfroystad [got a long way with parsing this](https://github.com/tree-sitter/tree-sitter-php/pull/72), but seems to be stuck on some tree-sitter weirdness. He could use some help with this, and this would further improve parsing percentage.

**Comment by cfroystad** [comment]
Thanks for focusing on this!
I'd be very happy to get some help get unstuck on that. The code is a bit messy due to PHP strings almost being a separate language, thus if anyone is familiar with tree-sitter and willing to lend me a hand, I'd be happy to jump on a call for some pair programming if that would make it easier to assist.

**Comment by aryx** [comment]
As I mentioned above Slack added some support for hacklang, which is mostly an extension of PHP, so maybe @cfroystad  you could copy some of the thing they do to hanle string interpolation in:
https://github.com/slackhq/tree-sitter-hack/blob/main/grammar.js

**Comment by cfroystad** [comment]
I've looked into the hacklang [PR](https://github.com/slackhq/tree-sitter-hack/pull/25/files), but it's incomplete and does not yet implement what I consider the tricky parts of supporting PHP/Hack strings in tree-sitter. The same goes for the Heredoc already merged in master. Am I missing something?

**Comment by aryx** [comment]
Maybe @frankeld or @Nicholas-Lin can help? What are the tricky parts of strings?

**Comment by cfroystad** [comment]
To me, the the tricky part is the PHP simple syntax with subscript or member expressions. The complex part (similar to Hacks embedded_brace_expression) was quite simple due to being clearly annotated - at least in the PHP parser.

The tree-sitter magic I'm struggling with, is this [anonymous node](https://github.com/tree-sitter/tree-sitter-php/pull/72/files#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR1139). It will always resolve to $._variable_name, but if I remove that option it correctly resolves the other options (and of course fails to resolve simple variables).

**Comment by cfroystad** [comment]
My bad, I looked in the wrong PR 😅 I'll go through the correct one this afternoon or tomorrow to see if I can use anything to fix my issue. Thanks for the pointer!

**Comment by cfroystad** [comment]
Finally, we have interpolated strings: https://github.com/tree-sitter/tree-sitter-php/pull/72

This brings us to 100 % parsing in the current selection of test projects.

Note, however, that there is still work to be done on references, PHP 8.1 and ensuring correctness.

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
we are now even at GA level, 99.9%
