### ISSUE TITLE
[js] Can't match duplicate function arguments

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3580]
In https://semgrep.dev/s/K82L, I should be able to match repeated function arguments.

**Comment by kopecs** [comment]
@IagoAbal Thoughts on closing this, given that https://semgrep.dev/playground/s/2Z4Rr works? Seems related to some other naming-related discussion.

**Comment by IagoAbal** [comment]
I would close. IMO each parameter `a` is a different parameter and therefore they should _not_ unify. We also don't unify two different variables `x` just because they happen to have the same name. Indeed the way to write the rule is to use two metavariables and compare them. In this particular case it is inconvenient but in general I believe it's the right approach. Perhaps we need to check if the docs make this all clear.
