### ISSUE TITLE
Semgrep-cli: tests: Reduce friction for adding tests

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3685]
While not being difficult, it is somewhat cumbersome to add a test to semgrep-cli. Plus, when a test fails, it is not straightforward to know what exactly failed and how to reproduce it.

It would be great if we had a simple test runner like we have in semgrep-core. A test would be a triplet of files, consisting in 1) the config, 2) the target, and 3) the expected output, all sharing the same base name (= the id of the test). If a test fails, the test runner simply has to report the test id of the failing test.

**Comment by mschwager** [comment]
> It would be great if we had a simple test runner like we have in semgrep-core. A test would be a triplet of files, consisting in 1) the config, 2) the target, and 3) the expected output, all sharing the same base name (= the id of the test). If a test fails, the test runner simply has to report the test id of the failing test.

The existing snapshot testing functionality does essentially operate on a triplet of files, however, I agree, the ergonomics are not so simple and straightforward. I can outline how this functionality works here, then perhaps we can turn this into CONTRIBUTING docs or, better yet, improve the testing interface such that it's obvious what's going on.

An example of our snapshot testing is probably worth a thousand words:

- Snapshot tests are defined in Python test files like: `test_check.py` -> [`test_regex_with_any_language_multiple_rule`](https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/e2e/test_check.py#L366)
- This test specifies a:
  - Config file: [`rules/regex-any-language-multiple.yaml`](https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/e2e/rules/regex-any-language-multiple.yaml)
  - Target: [`basic/regex-any-language.html`](https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/e2e/targets/basic/regex-any-language.html)
  - Snapshot output: [`results.json`](https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/e2e/snapshots/test_check/test_regex_with_any_language_multiple_rule/results.json)

So we do have a (config, target, output) triple. The problem I see is that it's a major pain to navigate to all these deeply nested, different files across many directories. I've noticed this myself when writing these tests: "Where the heck did that file go again?", "Where is `basic`, where is `rules`?"

Another crucial ingredient here is a basic understanding of the [`pytest-snapshot`](https://pypi.org/project/pytest-snapshot/) library. A quick read through the docs will help in understanding our testing functionality.

Another problem I've noticed is that the 3 separate arguments are all relative to different directories :exploding_head:. `rules`, `basic`, and `results.json` are all relative to different locations.

I see 3 areas for improvement:

1. For a particular test, place all relevant files in a single directory. E.g. put `regex-any-language-multiple.yaml`, `regex-any-language.html`, and `results.json` in the same directory. This will make it much easier to see the full state of a particular test.
2. Make all test arguments fully specified and relative to the top-level (`tests` or `e2c`) directory. E.g. `e2e/rules/regex-any-language-multiple.yaml`, `e2e/targets/basic/regex-any-language.html`, and `e2e/snapshots/test_check/test_regex_with_any_language_multiple_rule/results.json`. Sure, it's more verbose, but now I don't need to do any mental gymnastics and keep the directory structure of all tests in my head. Or, as a Python aficionado would say: "Explicit is better than implicit."
3. Document this information. I think this information mostly lives in a few people's heads rather than being documented anywhere. I actually think this is the least important because, if we can make the interface obvious enough, we shouldn't need much documentation.

Thoughts?

**Comment by IagoAbal** [comment]
Thanks for joining the discussion Matt! I think that 1+2+3 would definitely improve things. The only issue with having the three files in the same place is that the target itself may be a YAML file, but I guess we can use (are using?) `.yml` or something for this. In semgrep-rules I think they use the extension `.test.yaml`. IMO it's fine to have three folders, if that's all and there are no sub-folders.

Ideally we shouldn't have to touch any Python file to add a test. In semgrep-core we only touch OCaml code for adding a new test suite, but once a suite is set up, you simply add files into the folder and they are picked up automatically.

Right now when a pytest fails you only get a diff, and you have to figure out how to reproduce the problem by inspecting the Python code that runs the test, @mjambon recently suffered this. This is a bit frustrating considering that the tests typically are just comparing actual and expected output. If the test runner is aware of this, then it can also provide better error messages when something fails.

We could also let the `.json` oracle contain `...` and perhaps use Semgrep itself to match the actual result against the oracle, that way we can ignore stuff that is not important: `semgrep-core -lang json -f oracle.json output.json` should work I believe.

**Comment by emjin** [comment]
Still relevant

**Comment by aryx** [comment]
closing, I think what we have is ok, especially now that it's faster to run the python tests.

**Comment by aryx** [comment]
you can always use semgrep-core/tests/OTHER/rules/
or the one in deep-semgrep.
