### ISSUE TITLE
Generic Mode Doesn't Match Ellipsis Inside '['

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3747]
**Describe the bug**
Generic mode doesn't match as expected when ellipsis are inside '['. 

**To Reproduce**
https://semgrep.dev/s/N8eL

**Expected behavior**
Would expect the pattern above to match on lines 3-7 and line 12!

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by mjambon** [comment]
This is because in generic mode, `$X` always matches a single alphanumeric word. To match a sequence of items (punctuation or words), we now have `$...X`, which works for this example: https://semgrep.dev/s/y6Wd
![image](https://user-images.githubusercontent.com/343265/132093525-2c7f5df1-5b48-4929-980e-155bccdc819d.png)

**Comment by mjambon** [comment]
cc @IagoAbal who implemented the `$...X` feature :-)

**Comment by colleend** [comment]
awesome, good to know 👍  thanks for looking into this!
