### ISSUE TITLE
semgrep.dev bug report - Rust function matching not working

### ISSUE THREAD

**Issue by robre** [semgrep/semgrep#3750]
https://semgrep.dev/s/K8wj

**Comment by robre** [comment]
cant match a simple function `pub fn $FUN(...) -> $RESULT { ... }` (should match line 95)

**Comment by kopecs** [comment]
This is expected behaviour, as the contents of macros are simply token trees, not syntactically valid Rust code. For cases like this you can use either [`metavariable-pattern`](https://semgrep.dev/docs/writing-rules/rule-syntax/#metavariable-pattern) or [extract mode](https://semgrep.dev/docs/experiments/extract-mode) to match the macro contents and parse them as Rust.
