### ISSUE TITLE
Reoccurring Expressions Variable Matching incorrect

### ISSUE THREAD

**Issue by aaron-hau-zd** [semgrep/semgrep#3757]
https://semgrep.dev/s/jkKD

Not sure if I am doing it wrong. I created an anti-pattern with "Reoccurring Variable", but it still matches

![Screenshot 2021-08-26 at 16 40 26](https://user-images.githubusercontent.com/87050776/130930955-b5e6de7c-c16b-48cf-97e6-cc67975d0027.png)
Line 13 -- should not be flagged
![Screenshot 2021-08-26 at 16 39 47](https://user-images.githubusercontent.com/87050776/130930774-3ff76539-e754-42fe-81a1-9b4a9897ab68.png)

**Comment by emjin** [comment]
This is because the first pattern matches 

```
unsafe_function(sanitized_input)
``` 

which indeed does not look like

```
$SAFE = sanitize_string(...)
unsafe_function($SAFE)
```

You can do what you want using `pattern-inside`. However, this actually looks like a perfect rule for taint tracking mode! Read about it here: [https://semgrep.dev/docs/writing-rules/data-flow/ ](https://semgrep.dev/docs/writing-rules/data-flow/ )

For future reference, we have a community slack which is usually the fastest way to get help on rules! You can join here: [https://r2c.dev/slack](https://r2c.dev/slack)
