### ISSUE TITLE
PHP - Taint - Array flagged as tainted when key is tainted

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3770]
**Describe the bug**
When a tainted source is used as an array key, the whole array is flagged as tainted, leading to false positives

**To Reproduce**
https://semgrep.dev/s/4PE8

**Expected behavior**
The array should not be detected as tainted

**What is the priority of the bug to you?**
- P1: important to fix or quite annoying

**Comment by IagoAbal** [comment]
Given your rule this `$not_tainted = $rows[$tainted];` is going to be tainted because `$tainted` is tainted. But you could say that `$A[$B]` is a sanitizer, or you could even sanitize only the key as in https://semgrep.dev/s/N80n. Would that work for you?

**Comment by IagoAbal** [comment]
@erwanlr when time allows please let me know if my proposed solution works for you, or if I understood your problem wrong. Thanks!

**Comment by erwanlr** [comment]
It could work, I haven't had the time to try it yet. However, I still believe such case should not be flagged, as with `$data = $rows[$tainted];` `$data` does not contain tainted data unless there was something like `$rows[$tainted] = $other_tainted` done before

**Comment by IagoAbal** [comment]
I understand your point, but I am not sure whether we should built this into Semgrep. In general it doesn't seem like a good idea that you index an array/map with untrusted user input. Despite it makes the rule more verbose, I would say it's preferable that the user explicitly says:
```
    pattern-sanitizers:
      - patterns:
          - pattern: |
              $ARRAY[$SOURCE]
          - pattern: $SOURCE
```
Instead of making `$data` tainted in `$data = $array[$tainted]` we could perhaps not taint `$data` but issue some  warning on `$array[$tainted]`.

Any thoughts on this @aryx @inkz @minusworld ?

**Comment by inkz** [comment]
@IagoAbal I agree with you. I think it makes sense to keep current behavior and explicitly mitigate some of the FPs that are specific for each rule

**Comment by IagoAbal** [comment]
Closing this for now but I will double check with more people from r2c's security team, and of course feel free to reopen if you want to add to the discussion.
