### ISSUE TITLE
$...BODY not working for Python

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#3771]
**Describe the bug**
Similar issue to https://github.com/returntocorp/semgrep/issues/3170 but in Python

**To Reproduce**
https://semgrep.dev/s/DwPy/

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by sabrinabrogren** [comment]
I think this issue is still present.

**Comment by kopecs** [comment]
This arises out of the fact that we treat the (top-level) statements in a Python class as fields (think declarations in a Java class, fields on a C struct, etc...) in the generic AST, which the matching engine treats order-independent. This is so a pattern like

```java
class $C {
    ...
    void foo() { ... }
    ...
    void bar() { ... }
    ...
}
```

will match even if the actual class defines them in the opposite order. While this isn't strictly true to the semantics of Python, equivalent behaviour is probably what people expect given the relative commonality to just throwing random statements in a class.

Other languages don't support ellipsis metavariables in this context, so we should perhaps not permit it here either. It happens to be allowed by the parser since we allow this generally where a statement would appear, hence it parsing here but not in Java (for instance).

Given there are several challenges with allowing an ellipsis metavariable in this context---primarily that is is unclear what should be bound to the metavariable---I'm closing this.
