### ISSUE TITLE
Improve surfaced semgrep-core messages

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3774]
Since https://github.com/returntocorp/semgrep/pull/3657 we surface `semgrep-core` messages so users can report and fix them. These are not very good messages. For example:

```
semgrep-core reported a fatal error:
-----
Fatal Error: Parse_info.NoTokenLocation("FakeTokStr")
Raised at Parse_info.token_location_of_info in file "src/pfff/h_program-lang/Parse_info.ml", line 321, characters 28-64
...
Called from Memory_limit.run_with_memory_limit in file "src/system/Memory_limit.ml", line 59, characters 6-62
Called from Dune__exe__Main.iter_files_and_get_matches_and_exn_to_errors.(fun) in file "src/cli/Main.ml", line 630, characters 17-816
-----
Please file a bug report at https://github.com/returntocorp/semgrep/issues/new/choose
```

We should explain what is happening and include the rule/file where this happened so they can file a bug report.

**Comment by IagoAbal** [comment]
I believe that it is only shown if you run with `--verbose` in which case Semgrep should be telling you on which rule is that happening?

I agree that we should catch these exceptions and handle them properly. But what is happening here is that there was an uncaught exception, and in such case I think the error message is just right. The idea is precisely that the users report these backtraces so that we can investigate and handle the errors better.

**Comment by IagoAbal** [comment]
OK I was wrong, I did a small test with a known way to trigger a fatal error and the error is shown regardless of `-v`. I think that's good because then we get these bug reports. Right now Semgrep will still analyze more stuff regardless, but that maybe change when we pass all the rules to semgrep-core... if there is a fatal error then it will stop analyzing.

The file that is being analyzed you can get it with `--debug`. Right now we "catch" these unexpected exceptions in `semgrep_with_rules_file`, so maybe we should do it (also?) inside `semgrep_with_rules` (inside the iter_files_and_get_matches_and_exn_to_errors loop). Perhaps even in `Run_rules.check`.

This way we will know which rule and which file triggered the error, and also we can keep analyzing the rest of the rules and files instead of aborting.

**Comment by IagoAbal** [comment]
There are way too many places where you can get a `NoTokenLocation` exception. To the point that I don't think is feasible to do the same as I did with `range_of_any_opt`. I would rather get rid of fake tokens all together, but that's probably some (tedious) work.

**Comment by IagoAbal** [comment]
OK...

> Right now Semgrep will still analyze more stuff regardless, but that maybe change when we pass all the rules to semgrep-core... if there is a fatal error then it will stop analyzing. ...

All this was wrong. We already catch exceptions and convert them to errors in `Main.iter_files_and_get_matches_and_exn_to_errors`. Actually fatal errors are even reported with the path of the target file, we just need to print it. The rule id we do not report currently, but since Semgrep CLI sends one rule at a time... it should be able to print it too.
