### ISSUE TITLE
Feature: Only run rule inside folder if specific pattern present in file at root of folder

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3788]
**Is your feature request related to a problem? Please describe.**
Recently I came across a scenario where I needed a rule to be executed only on files belonging to the same vendor (which can be identified by the presence of the vendor name in a readme.md at the root of a library for example)

**Describe the solution you'd like**
The possibility to have a rule executed only on a folder where a specific pattern is detected in a file at the root of it.

E.g:
- folder_1/
  - file_1.php
  - file_2.php
- folder_2/
  - readme.md
  - file_3.php
  - sub_folder/
    - file_4.php

If `readme.md` matches the given pattern (ie a regex with the vendor name/url), the rule should be executed on the entire `folder_2` (so not on `folder_1` in this case)

**Describe alternatives you've considered**
None, workaround is to run this specific rule manually on the folders, and then run all other rules on all code

**Comment by IagoAbal** [comment]
As a workaround you could use Semgrep via its Python API to first find those readmes, then run your rules on the folders where those readmes are.

**Comment by brendongo** [comment]
@erwanlr I think this is beyond the scope of semgrep for the near future and can be handled by a script that calls semgrep selectively over files after using semgrep on readme,md files. Closing since we dont plan on baking this functionality into semgrep.

We might consider adding file targeting with regex on the file name but probably not on rules firing on one file determining what other files to run semgrep on.
