### ISSUE TITLE
[Terraform] Metavariable Pattern on strings do not match regular identifiers

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3929]
**Describe the bug**
Using metavariable-pattern in terraform produces no matches.

**To Reproduce**
https://semgrep.dev/s/WpgE

**Expected behavior**
Would expect the rule to match the two lines of test code in the link.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-404/metavariable-pattern-not-matching-with-terraform.

**Comment by aryx** [comment]
Here is a fix: https://semgrep.dev/s/pYkZ/
It's because $TYPE matches a string, not just an identifier, so then in the pattern-either after
you need to also use strings. But then the problem is that if you do pattern: "aws_iam_policy" it will not work
because YAML remove the quotes, so then you need this pattern:| to avoid the thing YAML does.

You can probably also use resource "$TYPE" ... { ... }
and then use a metavariable-regex: on $TYPE. This might be simpler.

**Comment by colleend** [comment]
I see, thanks for the example!

**Comment by colleend** [comment]
Seems like matching on just `$TYPE` doesn't work (gives an internal matching error as seen here: https://semgrep.dev/s/Oegn) -- should I file an issue for that? It's not an essential fix, so I don't think its necessary, but just wanted to get your opinion :D

**Comment by aryx** [comment]
because $TYPE matches a string content, which is not considered a valid program; it's text, without any syntax constraint,
but metavariable-pattern: assumes the metavariable content is a program (otherwise we use metavariable-regexp for that).
The error message maybe should be improved. Or maybe we need to add this special case for terraform where indeed what is inside those resource strings are kinda identifier (in fact the grammar support either a string or an identifier).

**Comment by colleend** [comment]
I think improving the error message would be great for now, maybe adding a special case for terraform would be nice if other people come upon this problem 👍
