### ISSUE TITLE
semgrep-ci should only scan the sections of the file applicable to the diff

### ISSUE THREAD

**Issue by directionless** [semgrep/semgrep#4010]
**Is your feature request related to a problem? Please describe.**

When adding semgrep to a large code base, it is desirable to only scan the things a PR changes, and not the whole code base. This lowers the friction to adoption. (I believe this is part of why semgrep-ci / semgrep-agent exist)

However, as I understand status quo, they appear to operate on the entire file that's been changed. In some code bases, that inadvertently brings in a large amount of additional things to scan and correct, thus increasing friction.

**Describe the solution you'd like**

CI findings should be limited to the changed section, and not just the changed file.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-445/semgrep-ci-should-only-scan-the-sections-of-the-file-applicable-to-the.

**Comment by dlukeomalley** [comment]
@directionless - **Semgrep CI only surfaces findings introduced in the PR**. You're right that it scans the whole changed file, twice! The file is scanned at the base commit of the PR, then at HEAD, and the results are compared. Findings that did not exist at the base commit are then surfaced to the developer. The benefit of this approach is that security issues may exist in the file outside of the diff, but be caused by code modification in the diff (e.g. changes to input sanitization in the diff-ed code -> security issue later in the file when the input is used or executed). 

See https://github.com/returntocorp/semgrep-action#usage-outside-ci for running Semgrep CI locally. Note the `--baseline-ref` argument that sets the base of the PR to compare against.
