### ISSUE TITLE
[JS] Parse error with metavariables in strings and duplicate lines

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4071]
**Describe the bug**
I'm not really sure where to begin describing this bug, so here are bunch of semgrep.dev links instead! 😛 

- https://semgrep.dev/s/KX7Y - original observed error
- https://semgrep.dev/s/qYdb - works with ellipsis
- https://semgrep.dev/s/lZ86 - works when I remove line 32 in the source code

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-496/[js]-parse-error-with-metavariables-in-strings-and-duplicate-lines.

**Comment by mjambon** [comment]
Maybe it's something related to constant propagation, I don't know. I assigned @IagoAbal

**Comment by IagoAbal** [comment]
@minusworld I don't understand the issue. You're asking Semgrep to match a constant with `"$STRING"` and `"..."`, and `html` has a known constant value (or am I missing something?).

Note that after `html = html.concat("hello")`, `html` is still a known constant, because 1) we know that `html` is a constant prior to this assignment, and 2) `"hello"` is just another constant string.

This is constant propagation at work, but you can disable it:
```
options:
    constant_propagation: false
```
If you think it should not match even with constant propagation enabled, then please let me know why.

**Comment by minusworld** [comment]
I thnk based on the Issue description, it seems like it used to be a parse error. I don't think I can replicate it anymore, so it must've been fixed.
