### ISSUE TITLE
HTML Support

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#4078]
**Is your feature request related to a problem? Please describe.**
It'd be nice to have native HTML support in Semgrep. For simple things, generic mode is mostly sufficient, but in some cases rules would have fewer false positives if there was full HTML support.

Also, periodically I find myself writing scrapers for some site. I think to myself - why am I writing code (e.g. using BeautifulSoup or another parsing library) when I have the wonder of Semgrep? It'd be neat to go `curl foo.com | semgrep -e "..."` or the like. There are other CLI tools that make this easy, like [pup](https://github.com/ericchiang/pup) or [htmlq](https://github.com/mgdm/htmlq), but web scraping could be another way Semgrep could do Most Anything You Need (TM). 

**Describe the solution you'd like**
Probably use tree-sitter-html or similar.

I'm not sure if we'd want to also add a `pattern-xpath`, or if you could do functionally the same thing just using existing pattern features. Using patterns might make what you're looking for even more obvious/clear than xpath 🤔 

**Describe alternatives you've considered**
Generic mode is OK for simple things.

**Additional context**
N/A

**Priority**

- P2: Not immediately important, but it'd be nice some day.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-498/html-support.

**Comment by aryx** [comment]
there is actually preliminary support for HTML with tree-sitter-html. I never took the time to finish though but there are a few tests in semgrep-core/tests/html/

**Comment by aegarbutt-stripe** [comment]
I would love to be able to leverage this (to the extent possible) in reviewing JS in HTML or Ruby in ERB files.

For example:

```
<script nonce="<% csp_nonce %>">{{various other content}}</script>
```

Is currently matched by [ruby.rails.security.audit.xss.templates.var-in-script-tag.var-in-script-tag](https://semgrep.dev/playground?registry=ruby.rails.security.audit.xss.templates.var-in-script-tag.var-in-script-tag), even though it seems the intention is to only match the contents between the opening and closing script tag.

I modified the rule with an additional `pattern-not-inside: <script ...>` (See: https://semgrep.dev/s/3BKD) and this appears to have worked for a simple case, but still fails on two other examples. Specifically:

```
<script nonce="<%= csp_nonce %>" defer src="<%= resource_path('foobar.js') %>"></script>
```

If there was first class HTML support, we could more easily write rules that target just the contents between the script tags or just the contents of the script tag attributes.

**Comment by aryx** [comment]
Adding support for html would also make it possible to write a javascript extraction rule that could be used by the futur -pp option of semgrep-core. See #4478

**Comment by Sjord** [comment]
I tested the current HTML support, and it works pretty well. It can already be used to create working rules. For example, this works as expected:

    patterns:
      - pattern: <a target="$TARGET" href="$HREF">...</a>
      - metavariable-regex:
          metavariable: $HREF
          regex: (https?:)?//
      - pattern-not-inside: <a rel="noopener">...</a>
      - pattern-not-inside: <a rel="noreferrer">...</a>
    message: >-
      This anchor tag with 'target="$TARGET"' is missing 'noopener'.

This works better than `lang: generic`, mainly because it is aware of where tags start and stop, instead of the 10-line rule. Also, `html` knows that attributes can be quoted in different ways (double quotes, single quotes, unquoted), which `generic` does not.

Ellipses in attributes don't seem to work. I also want to match `<a rel="noreferrer noopener">`, but a pattern like `<a rel="... noopener ..."></a>` doesn't work. Of course, this can be worked around by using a variable and metavariable-regex.

Ellipses in nested tags also don't seem to work. The pattern `<h1>...<a></a>...</h1>` does not match `<h1><div><a></a></div></h1>`.

Other than that, I think this is already pretty useful and should be listed as an experimental language. This issue could be closed, because there is at least some support for HTML. We should open new issues for specific things that don't work yet in HTML.

**Comment by aryx** [comment]
You're right! I'll try to create separate issues for the bugs you listed then!

**Comment by aryx** [comment]
cc @minusworld
