### ISSUE TITLE
Could not match function definition in Go interface.

### ISSUE THREAD

**Issue by janisz** [semgrep/semgrep#4172]
**Describe the bug**
Could not match function definition in interface.

**To Reproduce**
https://semgrep.dev/s/Dznd

**Expected behavior**
Function is matched.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
It's because the syntax for method inside interfaces is ambiguous when you allow it at the top with
other Go constructs.
For example how should we parse $FOO(...)?  is it a method call or a method definition in an interface.
Right now you can disambiguate by putting the 'func' keyword before as in:
https://semgrep.dev/s/Oen2
