### ISSUE TITLE
go: unable to match package comment

### ISSUE THREAD

**Issue by mhoffm-aiven** [semgrep/semgrep#4209]
example: https://semgrep.dev/s/AXJB

This can be useful to auto-fix copyright headers or `// go:generate` comments at the beginning of packages.

**Comment by aryx** [comment]
It's because when we do a pattern-inside, we compute the range of the matched AST, so your rule will only report comments that happen to be in the range of some matched code in the AST. The first comment is before the first AST element so is not in the range, and the second comment is between a package and main, so it will be reported.
If you didn't have the main after, it would not be reported either.

**Comment by mhoffm-aiven** [comment]
Hey @aryx, thanks for looking into it! Is this something that could be supported in semgrep in the future, or should i close this issue?

**Comment by aryx** [comment]
It does not fit very well with the semgrep philosophy right now. At the same time we also support regexp matching,
so it could be nice to support this use case. Maybe you should try the generic mode of semgrep; it could support what you want.

**Comment by mhoffm-aiven** [comment]
I understand! could you help with that? how would the generic pattern look for "match above `package xxx` ?

**Comment by aryx** [comment]
maybe @minusworld or @mjambon could help

**Comment by ievans** [comment]
how about https://semgrep.dev/s/Z4d4 with generic?

**Comment by aryx** [comment]
nice isaac!

**Comment by mhoffm-aiven** [comment]
Works for me! Thanks for your help everyone!

**Comment by aryx** [comment]
Closing then.
