### ISSUE TITLE
Taint mode appears to be broken for some languages

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#4253]
**Describe the bug**
Taint mode sanitizers don't seem to work in C#.  Source/Sink seems to work fine though.  See attached semgrep.dev link.

**To Reproduce**
https://semgrep.dev/s/kboberg@chegg.com:asp_taint_test

**Expected behavior**
Sanitizer definitions correctly perform cleanses for taint tracking.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Comment by IagoAbal** [comment]
Thanks for the report @chgg-kboberg! I fixed you rule: https://semgrep.dev/s/nK2Y, this should work. Let me know if you have other cases where it doesn't work and I can help you fine-tuning it.

If you have 15-20 minutes I also recommend you reading https://r2c.dev/blog/2021/taint-mode-is-now-in-beta/. For example, when you declare `- pattern: public ActionResult $CMETHOD(...,string $STRING,...){...}` as a source, Semgrep takes that pattern and matches it, and annotates all the matched coded as a source of taint. Since your pattern matches the entire method, then every subexpression in the method is annotated as being a source of taint. I fixed that this way:

```
    pattern-sources:
      - patterns:
          - pattern-inside: public ActionResult $CMETHOD(...,string $STRING,...){...}
          - pattern: $STRING
```

So it's only the occurrences of the `$STRING` parameter that are sources of taint. Hope it makes sense.

If you think taint-mode is not intuitive and you have any suggestion, please let us know! We are aware that it looks quite different to what you get in other tools, and user feedback is very appreciated.

Also, I have plans to add some debugging help for writing taint rules, which I hope to start working on soon-ish.

**Comment by chgg-kboberg** [comment]
Thanks @IagoAbal.  Semgrep rule docs for taint mode probably need the extended docs from the "cookbook" at the end of the blog - I use the Semgrep documentation as my "source of truth" and didn't think to go check the blog for functionality documentation.

**Comment by IagoAbal** [comment]
Have you checked the docs recently? When we published the blog post we also updated the docs: https://semgrep.dev/docs/writing-rules/data-flow/taint-mode/. I pointed you to the blog post because I think it provides some more context that can be interesting/helpful to know about, but for sure the docs should contain all the essential info. Let me know if you are missing something, you can find the "cookbook" here: https://semgrep.dev/docs/writing-rules/data-flow/taint-mode/#mini-cookbook.

**Comment by chgg-kboberg** [comment]
Not recently enough it seems.  This is a no-op then.
