### ISSUE TITLE
Patterns without a trailing `...` match to end of scope

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#430]
https://sgrep.live/94r

```
const $X = require("js-yaml");
            ...
            $X.load(...);
```

I believe this should match lines 8-14 but it matches all the way to line 16.

**Comment by aryx** [comment]
Yes, known issue. The way the engine works for statements matching, is that
it visits all sequence of statements, and when there's a match, it returns the whole range.
More generally I think we need to improve matching location and not just return one range but a set of ranges for each pattern between '...', because in A ... B ... C, the 3 elements may be quite far from each other but we would just return the whole range.

**Comment by aryx** [comment]
Right now the API between sgrep-core and sgrep-lint, and probably between sgrep-lint and sgrep.live is for each match, a single range, but we may want a list of ranges, to highlight the different components in a complex pattern. Also some people may want to just get the matching location of the last element in the pattern, some the middle.

In coccinelle you could prefix a line with '*" indicating that's the line you are interested to see.

**Comment by aryx** [comment]
cc @nbrahms @ievans

**Comment by nbrahms** [comment]
@aryx shouldn't it not return past the last matching statement though?

**Comment by aryx** [comment]
Yes it should not, but fixing that require changing the interface of how the visitor and matcher cooperate with each other (the matcher will need to not only return a boolean and metavariable environment, but possibly a subset of the stmts when matching stmts).

**Comment by aryx** [comment]
I've added stmts matching after stmt matching and expression matching, and you dont have the problem with the stmt/expr matching. You visit all stmt/expr, and when there's a match just print the whole stmt/expr. For stmts things are different because we implicitely add a '...' at the end, and this '...' matches all the rest.
