### ISSUE TITLE
Ensure users aren't surprised by "--config=auto will log in to the Semgrep Registry with your project URL"

### ISSUE THREAD

**Issue by Plasma** [semgrep/semgrep#4460]
Hi team,

Thanks for the semgrep project, I'm wondering what this notice is when running semgrep with the ``--config=auto`` suggestion refers to:

```semgrep --config=auto```
```
....
Logging in to the Semgrep Registry as project 'git@github.com:...`
```

This felt pretty alarming to read, given I thought semgrep was about to try and upload code somewhere?

What does "logging in" refer to? Who sees it? What if the repository on GitHub is private?

Thank you

**Comment by brendongo** [comment]
Hi @Plasma sorry for the confusion. Here semgrep is trying to see if there are any rules configured to run on that git project (keyed by project name) and running those rules. No code is uploaded. What language would have made more sense for you given this functionality?

**Comment by Plasma** [comment]
Thank you @brendong

To provide some background, I followed the quickstart steps (at https://semgrep.dev/getting-started) and when I saw that CLI log message I assumed one or two things were happening:
1) The code was being uploaded to Semgrep to detect the language (as this was the 'auto' mode)
2) The registry was going to try and git pull the code at the URL it showed me to try and detect the code (private repo, won't work)
3) Something else was being done or published with my private repo or URL

I never logged in to the semgrep.dev/login page so had no context of what "Logging in" to the registry was, and thought the above was about to happen. What would happen if `auto` is used when this was not configured ahead of time?

To help suggest some language tweaks, may I clarify exactly what's happening?

If its literally just the CLI checking if there a ruleset configured with this project name (no source pull, no upload, no attempt to load on GitHub, no publishing of the project name, no side effects at all ...?) then that would help clarify the language.

Thank you again for the quick response!

**Comment by nbrahms** [comment]
Hi @Plasma ,

Thanks for pointing this out! Tagging @adamboros as our resident language-clarifier-in-chief.

**Comment by savek-cc** [comment]
Don't think this should be closed yet - the language actually seems to indicate at least a publishing of a project URL to some registry (which might be some central one?) and thus indicate at least an upload of the project URL to some server on the internet.
So does all of that happen locally or does the project URL actually end up being sent off into the internet?

**Comment by emjin** [comment]
@ievans @minusworld I think one of you would be best able to answer this?

**Comment by minusworld** [comment]
Somehow I missed this ticket. My apologies.

@Plasma All the information sent is spelled out in this [privacy doc](https://semgrep.dev/docs/metrics/).

For `--config auto`, the project URL and a hash of the project URL are used to identify a set of rules for that project. On the first run of `--config auto`, it will run a few "inventory" rules that are used to generate a set of rule recommendations for the project going forward. After a few seconds, the project URL and hash are used to identify these recommendations and serve them.

Explicitly, we do not gather any code.

Let us know if you have any questions! :)

**Comment by Plasma** [comment]
Thanks @minusworld ! 

Upon reading the website I could see it didn’t try to upload code, but I assumed at the time (having just ran the CLI without seeing the website beforehand) that the use of the words “logging in” and my Git URL and “auto” I quickly assumed it was about to upload code to detect the language etc.

Could I suggest a wording change to the log line, perhaps `Querying the Semgrep Registry for any configuration files registered to project URL 'git@github.com:...`‘ or something like that?

Thank you for your reply.

**Comment by minusworld** [comment]
@ievans and @adamboros, what do you think of the above suggestion?

**Comment by ievans** [comment]
@minusworld made a PR: https://github.com/returntocorp/semgrep/issues/4460

**Comment by floyd-fuh** [comment]
I'm not writing this to complain, I'm writing it to let you know that not everybody lives in the "Cloud is perfectly fine" bubble.

I can't use a command line security tool that doesn't confirm before sending a project name to a third-party server. I see too many dark patterns here:

- Basically every tutorial just says --config=auto. 
- There are plenty of "hints" that you get better rules when you use the online repository. Reminds me of Google.
- There is no prompt confirming with the user before information is sent to semgrep.
- Automatically extracting information from the .git directory? That's not what I asked semgrep to do.

For me these things violate the Privacy Policy principle of "User control: Put users in control of their data at all times". Because users who use semgrep for the first time and follow a tutorial are not in control.

For me this is a very sad experience. Trust is lost, I won't be able to use the tool anymore until I've looked at every detail of what data is sent to the server. As I already see me digging through proxy and wireshark and I don't have that time, I'll probably just delete semgrep.

**Comment by brendongo** [comment]
@floyd-fuh thanks for clearly sharing your feedback. The auto config mode is designed for users who are less concerned about privacy: our idea is that it would scan your code to find languages, frameworks, and features and then sends that information to the backend to find appropriate rules. 

If we changed first run behavior so that there's a prompt before the first time config auto is used that echos the documentation, would that address your concern? What would you expect to see when auto config is run in a non-tty (eg CI) environment? Or maybe we move this fully behind `semgrep login` to emphasize its suitability for users comfortable with cloud-y features?

**Comment by floyd-fuh** [comment]
Thanks for considering.

I see the auto config mode mainly as convenience. I don't know if that is feasible, but I would really love it to be offline available. Security consultants have the use case that they get random zip files thrown at them on a weekly or monthly basis, so investing time into figuring out which rules I should enable is often not possible.

I think first of all, a command line tool should not interact with a server except if:

1. There's a prompt first. Not only the first time, but always. OR
2. If I clearly indicate on the command line that I want to connect to a server. Generic examples are `wget https://example.org` (of course it will connect to that server), `--login` (obviously there is no "local login" here, so that means its going to login online). Another edge case is if I specify `--autoconfirm`, that indicates that I'm willing to just accept whatever the tool will be doing. A new user will never use `--autoconfirm` unless he has read the manual/help of semgrep. Probably you could state in the manual/help that autoconfirm includes autologin.

So yes, moving behing `semgrep login` seems to be a good choice.

I don't think a first-time use prompt is sufficient.

In a CI environment I would recommend that the `--autoconfirm` or `--login` has to be used or that you have to point to local rules, otherwise the tool exits with an error or does only what is possible without a login. I'm aware that could be problematic to fix because maybe there are already plenty of CI implementations that don't do that... To be honest, anyone who just runs a tool in their CI platform without having it properly tested on their local machine isn't worth considering. So it might be OK to say that `--autoconfirm` is the default in non-tty environments, although I think there are nicer solutions such as putting it behind `semgrep login`.

Really nice would be if you tell the user what data exactly is sent to the server when the prompt appears and in log messages printed.

What would be really cool: `--config=auto` will only warn that the user is not logged-in and then still do whatever is possible in an offline fashion.

I can't really go into too much details because I don't really know the technical details on why `--config=auto` is connecting to the server, if it would be feasible to just "download" the data and then do the search locally or such. Maybe guiding the user how to do that in the printed messages (or point to documentation) would be nice too.

**Comment by Plasma** [comment]
> I can't really go into too much details because I don't really know the technical details on why --config=auto is connecting to the server, if it would be feasible to just "download" the data and then do the search locally or such. Maybe guiding the user how to do that in the printed messages (or point to documentation) would be nice too.

This would be ideal; my main cause for concern for submitting this issue was that I came across semgrep, ran it on a project, and it felt like it was _in the process of_ uploading my project to your servers to do the scan, because it said "logging in" and printed my private repository URL.

I feel like semgrep shouldn't send anything to your servers about my project (not git url, not name, not anything), if it asked "can we check semgrep servers?" I'd also say no to that because I don't know what it's about to do.

My suggestion would be:
1. By default, do not connect to, or even prompt to, access your servers
2. Support a ``--login` that allows the preferences to be fetched from the server as needed, as this is explicit, there's no surprises

Thank you for your understanding.

**Comment by ievans** [comment]
@floyd-fuh @Plasma thanks for the thoughtful comments. I think we’ve made a mistake in our design approach here. For context: we built config auto based on requests from existing users of semgrep.dev who were comfortable passing more information about their repository to our servers. As we’ve added a lot more rules to the registry (200+ just in the last month) many online users want to just grab the latest rules based for the langs + frameworks they’re using, or get cached results if they’re running on a project that has already been analyzed.

The mistake: as we’ve broadcast `config=auto` more in documentation it's easier to miss the notes about "this sends your project URL to the auto config server"; and it's become more complex to reason about online/offline separation. Security consultants have very legitimate concerns about accidentally sending any information about the repositories they are analyzing to remote servers.

So I think I agree that putting such online features behind `semgrep login` may be a good clear line for this and future development. But note, running with `--config=p/python` also fetches from https://semgrep.dev/p/python (no project url sent of course), and I don’t think we’d want to require login for that.

**Comment by Plasma** [comment]
> So I think I agree that putting such online features behind semgrep login may be a good clear line for this and future development. But note, running with --config=p/python also fetches from https://semgrep.dev/p/python (no project url sent of course), and I don’t think we’d want to require login for that.

Thanks @ievans - `--config=p/python` not needing a login makes sense, could `--config=auto` be improved to not require sending anything to the server?

How does `auto` work when there's no project registered at Semgrep servers? If auto doesn't actually _need_ to speak to Semgrep servers, then maybe make whatever extra customizations `auto` does only apply if the account is logged in?

Or perhaps raise a error that `--config=auto requires a login, use --config=p/python for explicit language setting without a login being required` or something?

**Comment by brendongo** [comment]
I opened #5464 to track the feedback above. Closing and tracking there since our internal tracking isn't dealing well with this reopened issue.
