### ISSUE TITLE
Parse error in remote-curl.c from git

### ISSUE THREAD

**Issue by bburky** [semgrep/semgrep#448]
A couple notes on a sgrep's parsing of a C file:

When I was testing curl options sgrep, I tried to use [remote-curl.c](https://github.com/git/git/blob/9fadedd637b312089337d73c3ed8447e9f0aa775/remote-curl.c) from git's source code, but sgrep has a parse error [on line 1220](https://github.com/git/git/blob/9fadedd637b312089337d73c3ed8447e9f0aa775/remote-curl.c#L1219-L1220). It looks like git [defined a macro that expands to a `for` loop](https://github.com/git/git/blob/9fadedd637b312089337d73c3ed8447e9f0aa775/string-list.h#L141-L145), and sgrep doesn't know that and sees a syntax error.

```
> docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config=https://sgrep.live/c/xZg --strict  -v /home/repo/remote-curl.c
DEBUG is on
trying to download from https://sgrep.live/c/xZg
loaded 1 configs in 4.713810205459595
debug: validated config in 0.04884457588195801
running 1 rules from 1 config remote-url
sgrep ran in 0:00:00.164434
{'matches': [], 'errors': [{'check_id': 'ParseError', 'path': '/home/repo/remote-curl.c', 'start': {'line': 1220, 'col'
: 3}, 'end': {'line': 1220, 'col': 18}, 'extra': {'message': 'Syntax error', 'line': '\t\targv_array_push(&args, cas_op
tion->string);'}}]}
sgrep: /home/repo/remote-curl.c: ParseError
run with --strict and 1 errors occurred during sgrep run; exiting
```

If I comment out the offending code, I also get a `no ifdef` error on [line 183](https://github.com/git/git/blob/9fadedd637b312089337d73c3ed8447e9f0aa775/remote-curl.c#L183). It looks like sgrep doesn't understand `#if`, only `#ifdef`?

```
> docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config=https://sgrep.live/c/xZg --strict  -v /home/repo/remote-curl.c
DEBUG is on
trying to download from https://sgrep.live/c/xZg
loaded 1 configs in 2.8946638107299805
debug: validated config in 0.057822465896606445
running 1 rules from 1 config remote-url
(ONCE) skipping: #ifndef NO_CURL_IOCTL
PB: Ast_c_build, on /home/repo/remote-curl.c (exn = (Failure "/home/repo/remote-curl.c:183:0: no ifdef"))
sgrep ran in 0:00:00.139580
{'matches': [], 'errors': [{'check_id': 'FatalError', 'path': '/home/repo/remote-curl.c', 'start': {'line': 1, 'col': 1
}, 'end': {'line': 1, 'col': 1}, 'extra': {'message': 'Fatal Error: (Failure "/home/repo/remote-curl.c:183:0: no ifdef"
)', 'line': '#include "cache.h"'}}]}
sgrep: /home/repo/remote-curl.c: FatalError
run with --strict and 1 errors occurred during sgrep run; exiting
```

sgrep.live demo, copy pasted in remote-curl.c from github: https://sgrep.live/xZg

Would processing a file like this ever be supported by sgrep? Is it possible to gracefully handle parsing an (unknown) macro that behaves like a `for` loop? I think you can treat `#if` however you're already treating `#ifdef`.

**Comment by aryx** [comment]
The C parser in sgrep uses some heuristics to parse C code before preprocessing. 
For more information about this, see the paper "Parsing C/C++ Code without Pre-processing"
https://link.springer.com/content/pdf/10.1007/978-3-642-00722-4_9.pdf

Those heuristics sometimes fail, but sgrep now provides a way to define a set of macros to partially and internally expand via -macros. See the example in the PR attached.
In your case if you define in a sgrep_macros.h #define for_each_string_list_item(a,b) for(;;)
then you will be able to process the file.

Regarding the ifdef, again, the C parser in sgrep uses some heuristics to try to recognize
as many ifdef idioms as possible while still generating a valid AST (this is actually hard, see the paper above) but this sometimes fail too. For those one, you may need to rewrite slightly the code
so that the ifdef lie at clean boundaries in the code (after a full statement, not in the middle of an expression like 
 foo
#ifdef BAR
   (1
#else 
  (2
#endif 
  )
or in the middle of a statement.
The C parser in sgrep recognizes many #if and #ifdef, it just depends where they are located in the code and their context.

The C parser in sgrep is actually the same than the one in coccinelle, a refactoring tool used in the Linux kernel and in practice it can parse 99% of the Linux codebase (but they rewrote sometimes the code to satisfy the conditions I mentioned above).


The alternative is to call cpp, which is what most static analysis tools do, but:
 - this is slow, because the resulting file can be huge
 - this is actually complicated because you need to understand the build system to pass to your static analyzer the right -I and -D to call cpp correctly.

**Comment by bburky** [comment]
Thanks, that helps clarify the parsing behavior. It makes sense that it's impossible to perfectly parse preprocessor statements that don't fall on clean boundaries. I didn't notice that the `#if` spanned across `else if` branches, it makes sense now that it didn't work.

The `-error_recovery` flag looks good and would allow me to still get partial results. If I'm using sgrep to scan unknown codebases I won't always be able to extract the macros for use with `-macros`. For other use cases though, `-macros` looks like a good solution.

Thanks for these changes and clarifying how parsing is handled.
