### ISSUE TITLE
[Python] restore GA level, current parsing stats are at 99.2%

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#4480]
See https://dashboard.semgrep.dev/metric/semgrep.core.Python.parse.pct
we are at 99.2%.
I've recentrly added tree-sitter-python to ocaml-tree-sitter-semgrep and it's at 99.925%
so there is good hope. We just need to switch to tree-sitter for python too.

**Comment by aryx** [comment]
Also we need to add more languages to https://dashboard.semgrep.dev/
now that we have more GA languages.
See here: https://semgrep.dev/docs/language-support/

**Comment by aryx** [comment]
@brandonspark are we there now with tree-sitter-python and all the TODOs fixed?

**Comment by brandonspark** [comment]
@aryx No, sadly not, we are at 99.7%.

There is a single TODO that I left in the code, which I have now fixed in #6014, but I highly doubt that it's why.

I'm pretty sure the fact that we are failing to parse is a result of people passing off fake meta-Python files as Python, which borks the parser. I don't really know if there's something we can do about that.

**Comment by aryx** [comment]
Well we can look at the projects listed in the projects.txt and if 1 project really abuses and have fake meta-python files
we could just skip it (and use another popular Python project instead) and get better stats.

**Comment by brandonspark** [comment]
The two projects are:
```
https://github.com/python/cpython
https://github.com/huggingface/transformers
```

Deleting just one is not enough to get us to 99.9%.

I have investigated both. `huggingface/transformers` uses some weird shenaniganry which looks like metaprogramming.

`cpython` just has code using this weird `except*` and `!` inside of f-strings, which as far as I have checked is not real Python code. Since it also has code _testing_ this syntax, I am under the impression it's a language extension or something, but I'm not sure. `cpython` also has python files which are just tests for the Python grammar, meaning that it has code which does stuff like having a decorator `@False or null`, which is nonsense that would crash any real Python program.

I am down to delete both. Thoughts?

**Comment by aryx** [comment]
Go for it. Just put them in comments in the projects.txt file with your notes on why we skip them

**Comment by aryx** [comment]
It is totally ok to skip cpython. We do the same for other languages where usually the compiler for a lang contains many test cases not representative of real code

**Comment by aryx** [comment]
Got back to 100% Closing!
