### ISSUE TITLE
#nosemgrep requires a path to the config file unexpectedly

### ISSUE THREAD

**Issue by JosiahOne** [semgrep/semgrep#4574]
**Is your feature request related to a problem? Please describe.**
Consider the following folder structure:

```
➜  semgrep_test tree .
.
├── configs
│   └── rule.yml
└── test.py
```

Where rule.yml is:

```
rules:
  - id: poc
    pattern-either:
      - pattern: os.getcwd(...)
      - pattern: pathlib.Path.cwd(...)
    languages:
      - python
    severity: ERROR
    message: "POC"
```

And test.py is:

```
import os

os.getcwd()	# nosemgrep: poc
```

If you run `semgrep --config configs/rule.yml .` you get the following output:

```
Running 1 rules...
test.py
rule:configs.poc: POC
3:os.getcwd()	# nosemgrep: poc
ran 1 rules on 1 files: 1 findings
```

Which I found to be unexpected. The [docs](https://semgrep.dev/docs/ignoring-findings/) indicate you should only need to provide the rule-id, which I thought was "poc" here.

It appears instead that what you need to pass to #nosemgrep: is a namespace-like string that contains the path to the config. e.g. this content for test.py:

```
import os

os.getcwd()	# nosemgrep: configs.poc
```

Causes an expected output from semgrep:

```
Running 1 rules...
ran 1 rules on 1 files: 0 findings
```

**Describe the solution you'd like**
It would be great if you could ignore semgrep rules without needing a path to the config in the `#nosemgrep` comment, if this is possible. Requiring code to include the full path makes it quite brittle in the case where rule configs are relocated.

If that's not possible and namespacing must be used, documenting this on the [docs](https://semgrep.dev/docs/ignoring-findings/) would be super helpful.

**Additional context**
I tested this using semgrep installed on macOS 12.1 via the python3 pip method:

```
➜  semgrep_test semgrep --version
0.79.0
```

**Comment by ievans** [comment]
@JosiahOne thanks for this feedback, great writeup. This is intended behavior, but it is controllable with the flag `--rewrite-rule-ids` / `--no-rewrite-rule-ids`. If you disable rewriting rule ids, you can use # nosemgrep as intended, and the output `rule:configs.poc: POC` will instead read `rule:poc: POC`. 

The rewrite behavior is heavily relied upon for interactions with Registry (https://github.com/returntocorp/semgrep-rules) rules, so that's why it's the default.

@s-santillan is doing a major update to docs on ignores right now, so I'll tag her to make sure https://github.com/returntocorp/semgrep-docs/pull/415 addresses this!

**Comment by JosiahOne** [comment]
Thanks for the quick response and tip @ievans ! I gave ``no-rewrite-rule-ids` a shot and indeed that solves my woes.

Looking forward to the docs update!
