### ISSUE TITLE
javascript.lang.correctness.useless-eqeq.eqeq-is-bad  false positive

### ISSUE THREAD

**Issue by prensing** [semgrep/semgrep#4667]
If I run the following code against the standard Javascript rules, I get what I believe is a false positive for the rule
javascript.lang.correctness.useless-eqeq.eqeq-is-bad on line 4 (the if() line).
```
function (event) {
        var newModelsCnt = 0;
        newModelsCnt++;
        if (newModelsCnt == 0) {
            return;
        }
    }
```
I get this on the command line and also in the online Playground. If I change the initial variable setting to anything but "0", it goes away. 

Command line version: 0.82.0
Run with "--config=auto"

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-865/javascriptlangcorrectnessuseless-eqeqeqeq-is-bad-false-positive.

**Comment by ievans** [comment]
@prensing thanks for reporting this bug!

I made a reproducing snippet: https://semgrep.dev/s/returntocorp:eqeq-is-bad-copy-failure

I believe the comparison is still useless because it always evaluates to `false`, but still not sure why the rule fires here

**Comment by prensing** [comment]
Yes, given that snippet, it will always be false. However, our real code does not have the arbitrary "++"; there is a loop with some logic inside, so the result of the test does vary.

**Comment by nbrahms** [comment]
@IagoAbal I suspect that this is a constant propagation bug?

**Comment by IagoAbal** [comment]
Totally a constant propagation bug. This is because we encode `x++` as a built-in function call, and Semgrep is assuming that function calls aren't mutating variables. We should fix it for `x++` (and variants). We should also do something for the general case, although there is a trade-off to make (inferring wrong constants vs missing constants, and both can lead to FPs).

I wonder if _javascript.lang.correctness.useless-eqeq.eqeq-is-bad_ should be using constant propagation, have we considered this? I'm guessing the main purpose of the rule was to catch stuff like `x == x` where the user wanted to write `x == y`. cc @minusworld
