### ISSUE TITLE
C parsing warning

### ISSUE THREAD

**Issue by lnksz** [semgrep/semgrep#4732]
**Describe the bug**
Semgrep Core — Syntax error. An error occurred while invoking the Semgrep engine.

**To Reproduce**
[link to https://semgrep.dev:](https://semgrep.dev/s/p9we)
With the problematic file being https://raw.githubusercontent.com/nanomsg/nng/v1.3.0/src/protocol/pair1/pair1_poly_test.c

**Expected behavior**
Semgrep successfully parsing/checking the C file

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Using Gitlab bundled `GitLab Semgrep analyzer v2.18.0`

**Use case**
Run semgrep meaningfully on C files in the Gitlab CI pipeline

I see quite a few (280) similar warnings during our library builds (projects like libgpiod, nng, mbedtls, pcsclite) if there is interest (I see that C is still in experimental state) for these, I could share these as well.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-912/c-parsing-warning.

**Comment by aryx** [comment]
This is because of the use of macros that result in non-parseable code by the C grammar.
This code: ```
TEST_LIST = {
	{ "pair1 polyamorous best effort", test_poly_best_effort },
	{ "pair1 polyamorous cooked", test_poly_cooked },
	{ "pair1 polyamorous default", test_poly_default },
	{ "pair1 polyamorous recv no header", test_poly_recv_no_header },
	{ "pair1 polyamorous recv garbage", test_poly_recv_garbage },
	{ "pair1 polyamorous ttl", test_poly_ttl },
	{ "pair1 polyamorous close abort", test_poly_close_abort },
	{ "pair1 polyamorous validate peer", test_poly_validate_peer },

	{ NULL, NULL },
};
```
does not look like C because in C you need to define the type of variables (here TEST_LIST).
I guess TEST_LIST is defined in testutil.h and expands to something that has a type, but semgrep analyzing files one at a time, and because it does not preprocess the code, can't parse correctly this part of the file. Note however that tree-sitter-c (which is used internally by semgrep) can return partially parsed files, and in your example most of the file is actually parsed! Just the TEST_LIST part at the end is not in the AST.
So this is why we just display a warning (and not an error), because we still analyze most of the file.

**Comment by lnksz** [comment]
Thanks @aryx for the feedback! So should I just ignore the other 280 or so warning as well? (There are messages to report them here)

**Comment by aryx** [comment]
Unfortunately for C code, there will always be lots of warnings. It's a fight we can't win, the C preprocessor makes it impossible to get 100% parsing coverage when you try to parse the code as-is (that is without calling the C preprocessor first, like gcc does).

**Comment by lnksz** [comment]
I understand that. And thanks for picking up the fight at all ;)
