### ISSUE TITLE
Support for jsonschema 4.x removed

### ISSUE THREAD

**Issue by priv-kweihmann** [semgrep/semgrep#4739]
Cleanup of setup.py with latest change https://github.com/returntocorp/semgrep/blob/26d72e1eae42e21f0a71c899059eda6c0f6a3819/semgrep/setup.py#L126 reverted the support for jsonschema 4.x without even mentioning that in the commit message.
Can one have that be fixed please.

In my setup I require jsonchema 4.4+ for other tooling in the same scope, so the latest release broke my setup :disappointed:

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-915/support-for-jsonschema-4x-removed.

**Comment by underyx** [comment]
Hey @priv-kweihmann, sorry about that :( I should've added this to the commit message as well; I left a note with the reasoning here: https://github.com/returntocorp/semgrep/pull/4463#issuecomment-1034439918

It's possible there is a solution to the second bullet point and we're just unaware of it. If we can figure that out, maybe it could be reasonable to allow jsonschema v4 even though it would cause errors due to incompatibility in a couple lines of code.

**Comment by andersk** [comment]
The jsonschema 3 bound is increasingly conflicting with other projects that require jsonschema 4, such as [openapi-schema-validator](https://github.com/p1c2u/openapi-schema-validator/blob/0.3.0/pyproject.toml#L35). Please consider reopening and fixing this.
