### ISSUE TITLE
Metavariable-regex is anchored

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4807]
Per docs, this should be unanchored:

https://semgrep.dev/s/KgRY

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-980/metavariable-regex-is-left-anchored.

**Comment by aryx** [comment]
@mjambon can we close this issue?

**Comment by mjambon** [comment]
@aryx no, I didn't touch that. I wasn't aware of this bug. For example, the pattern `a` should match `xxa` but currently, it doesn't. The issue is apparently that the regexp is matched at the beginning of the string using something like `Pcre.pmatch` instead of being matched successively at all the positions in the string using the appropriate function.
