### ISSUE TITLE
Cannot run `semgrep ci` while logged in and with explicit config

### ISSUE THREAD

**Issue by Dmaddu** [semgrep/semgrep#4923]
**Describe the bug**
Hello there,
we use semgrep ci in buildkite pipeline, and we are getting below error with recent docker image
'returntocorp/semgrep-agent:v1'
sha256:3870c12573d2bf4a0a22de79ef4ffcaf92373576e166fddcfb06809966045037

=== Running: SEMGREP_BASELINE_COMMIT=XXXXXX. SEMGREP_RULES=.semgrep semgrep ci
  | Cannot run `semgrep ci` while logged in and with explicit config. Use semgrep.dev to configure rules to run.

Earlier we are using returntocorp/semgrep-agent:sha-f3a1732 image, and there is no error. 

could you please assist in fixing this error? 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1052/cannot-run-semgrep-ci-while-logged-in-and-with-explicit-config.

**Comment by underyx** [comment]
Hi @Dmaddu! Sorry about the breakage here. We've fixed this issue here, and you can now unpin your Docker image: https://github.com/returntocorp/semgrep-action/pull/551

Please unpin as early as possible, because we scheduled an update of the p/secrets ruleset for tomorrow PST morning, which will not be compatible with older versions of semgrep. (The p/secrets ruleset will use string entropy calculation features that we added in semgrep 0.83).

Also note that the `.semgrep/` directory is overwritten by your semgrep.dev config, so you can probably remove that directory from your project!
