### ISSUE TITLE
Squiggly bracket object destructuring and importing not supported for Javascript and Typesecript 

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4971]
**Describe the bug**
Using the squiggly bracket notation to specify multiple objects for an import or for destructuring results in a Semgrep Core error. This issue occurs when using metavariables as well as when manually specifying the variable names to match.

**To Reproduce**
https://semgrep.dev/s/enncoded:js-squiggly-bracket-test
Isolating each of the patterns will result in an engine error.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Fixing this will enable a common way of importing and assigning multiple things in Javascript and Typescript to be represented in Semgrep rules.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1119/squiggly-bracket-object-destructuring-and-importing-not-supported-for.

**Comment by nmote** [comment]
The problem here is that the module name in both the patterns and the program text itself is missing quotes around it.

This leads to an error in the TypeScript playground, too: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwEoFMCOBXFBnGAaOVbSAO2xQF84AzKCEOFADzCh2yA

When I add quotes, Semgrep returns the results that I expect: https://semgrep.dev/s/qZ3O
