### ISSUE TITLE
Running semgrep behind SSL proxy

### ISSUE THREAD

**Issue by InLineR495** [semgrep/semgrep#5084]
Semgrep is running in linux with globally configured proxy does not use it and throws an SSL error. Is there a way i can run Semgrep behind proxy? Or disable SSL verification?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1216/running-semgrep-behind-ssl-proxy. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
Sorry can you provide more details and reproduction for us

**Comment by DrewDennison** [comment]
@InLineR495 we use the python requests framework which means if you do something like

```bash
export HTTP_PROXY='http://<proxy ip:port>'
export HTTPS_PROXY='http://<proxy ip:port>'
```

it should work without any code changes. See https://docs.python-requests.org/en/master/user/advanced/ for more details.

Please let us know if this works or if you're still seeing a bug. If you're seeing a bug, can you include a stack trace?

**Comment by unixerius** [comment]
The problem isn't that the Linux system is behind a proxy, the problem is that it's behind an **intercepting** or **inspecting** proxy server, which breaks open the TLS connection. This proxy usually adds a catch-all certificate which is created by a private certificate authority.

Again this should work just fine as Semgrep uses Python Requests which uses the operating system's trust store. 

For @InLineR495 the issue most likely was that the trust store did not include the root CA cert that's tied to the cert on the intercepting proxy.

**Comment by sflanker** [comment]
In my experience the statement "Python Requests ... uses the operating system's trust store" did not prove to be correct. In order to resolve this issue I had the run the following:

```
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

before I ran this, both `curl` and raw `urllib3` from python worked fine, but semgrep did not. Once I explicitly set this variable semgrep started working.

**Comment by mitch-athena** [comment]
Also behind an inspecting proxy and having this same issue running semgrep in VSCode and already have the `REQUESTS_CA_BUNDLE` exported, as well as `CERT_PATH`, `CERT_DIR`, `SSL_CERT_FILE`, `SSL_CERT_DIR` as this also fixes TLS issues for PIP. Any idea what else is needed to get this working?

Error Notification in VSCode:
```
Fatal error: Failed to download config from https://semgrep.dev/c/p/default: TLS failure: authentication failure: invalid certificate chain
```

Error in output log from Semgrep extension in VSCode:
```log
Refreshing rules
[73.00][ERROR]: Uncaught async exception: Fatal error: Failed to download config from https://semgrep.dev/c/p/default: TLS failure: authentication failure: invalid certificate chain
```

No issue running semgrep from the CLI though.
