### ISSUE TITLE
Python `as` inside `with` multiple

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#5092]
**Describe the bug**

The following fails to parse: 

```
def test_send_fcm_expired(hass, hass_client):
    """Test that the FCM target is removed when expired."""
    registrations = {"device": SUBSCRIPTION_5}
    await mock_client(hass, hass_client, registrations)

    with (
        patch("homeassistant.components.html5.notify.WebPusher") as mock_wp,
        patch("homeassistant.components.html5.notify.save_json"),
    ):
        mock_wp().send().status_code = 410
        await hass.services.async_call(
            "notify",
            "notify",
            {"message": "Hello", "target": ["device"], "data": {"icon": "beer.png"}},
            blocking=True,
        )
    # "device" should be removed when expired.
    assert "device" not in registrations
```

https://semgrep.dev/s/4Ry5

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1218/python-as-inside-with-multiple. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
> `patch("homeassistant.components.html5.notify.WebPusher") as mock_wp`

This seems to use an *as pattern*, which was introduced in [PEP 636](https://peps.python.org/pep-0636/), which is implemented upstream in tree-sitter-python ([tracking issue](https://github.com/tree-sitter/tree-sitter-python/issues/116), [PR](https://github.com/tree-sitter/tree-sitter-python/pull/140)). So it seems that upgrading the tree-sitter-python in semgrep would solve this issue.

**Comment by djmattyg007** [comment]
@Sjord I think you've gotten confused. This has nothing to do with PEP 636 `match` statements. `patch()` is a function provided by the python standard library for monkeypatching code. However that isn't relevant - the question is about how to match the `as` clause in the middle of a `with` context manager statement with multiple context managers in use.

In general I think semgrep's support for context managers (`with` statements) is quite poor. Ideally I'd be able to write rules like `pattern: with func() as value: print(value)` and have it match regardless of how many context managers are in the `with` statement.

I also think that a rule like this:

```
$RESP = requests.get(...)
$RESP.raise_for_status()
```

should match this code:

```
with open("file.txt", mode="r") as f:
    response = requests.post("", files={"file": f})
response.raise_for_status()
```

Right now it doesn't match because semgrep thinks the statements are in two different contexts. This isn't true - the `response` variable continues to exist after the `with` block ends.
