### ISSUE TITLE
pattern-not-regex does not filter as expected in generic mode

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#5148]
**Describe the bug**
I have https://semgrep.dev/s/kw5O, where I am trying to remove findings that begin with a comment character using `pattern-not-regex`. In the past, the behavior of `pattern-not-regex` was to filter out anything that overlapped with the result of `pattern-not-regex`, but that appears not to be the case here.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

This is blocking https://github.com/returntocorp/semgrep-rules/pull/2066. Desired completion date would be end-of-month.

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
This is blocking https://github.com/returntocorp/semgrep-rules/pull/2066.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1252/pattern-not-regex-does-not-filter-as-expected-in-generic-mode. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
This is the solution I got, using only `pattern-regex` instead of the generic mode: https://semgrep.dev/s/GXBn. Ideally, we should write `\.` instead of `.` but it's easier this way.

The problem with the original solution that uses the generic mode is this:
```
      - pattern: management.endpoints.web.exposure.include=...heapdump...
```
The dots match multiple lines because all the lines are in the same block. The filter `pattern-not-regex: "^#.+$"` doesn't work because the match may start after the `#` and not include it, as in the example:
```
#management.endpoints.web.exposure.include=*
```

Also, we have to write `(^|(?<=\n))` instead of `^` to match the beginning of a line. This is unfortunately due to how the regexps are compiled by default. We could change it easily but you need to ask for it and estimate how many existing rules that would break.

There may be other issues with the generic mode here. One improvement would be to add an option to preprocess the input and remove comments (#3428).

Another improvement might be to create a variant of `...` that stays on a single line, or offer an option to specify how many lines the `...` can span. I created an issue for this: https://github.com/returntocorp/semgrep/issues/5211
