### ISSUE TITLE
Dockerfile metavariables for image aliases are not matching

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#5229]
**Describe the bug**
https://semgrep.dev/playground/s/r2c-sec-research-test:missing-image-version

I am trying to update [this rule](https://semgrep.dev/editor/r/dockerfile.best-practice.missing-image-version.missing-image-version) for [this issue](https://github.com/returntocorp/semgrep-rules/issues/2038). I expected the `pattern-not-inside` clause to filter out the last test case because `$ALIAS` should match to `base`, but it does not.

**To Reproduce**
https://semgrep.dev/playground/s/r2c-sec-research-test:missing-image-version

**Expected behavior**
I expected the last test case in the example provided to not match.

**What is the priority of the bug to you?**

- [x] P2: regular bug that should get fixed

**Use case**
This will help me finish resolving this issue: https://github.com/returntocorp/semgrep-rules/issues/2038

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1300/dockerfile-metavariables-for-image-aliases-are-not-matching. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
Note that `FROM ...` doesn't make sense as a pattern because `...` would stand for list of items of the same kind. Unfortunately it's not rejected as a syntax error because `...` is considered a valid image name. Instead users should write `FROM $IMAGE`. We probably should do something about this.

The more serious issue here is this:
![image](https://user-images.githubusercontent.com/343265/172264955-e7f68bf6-2a4d-4580-9b88-adf1e482ad6a.png)
https://semgrep.dev/playground/s/returntocorp:wtf

Dumping the AST shows the problem:
```
$ semgrep-core -lang docker -dump_ast <(echo -e 'FROM abcdef')
Pr(
  [ExprStmt(
     Call(
       N(
         Id(("FROM", ()),
           {id_info_id=2; id_hidden=false; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); })),
       [Arg(
          Call(
            N(
              Id(("!dockerfile_concat!", ()),
                {id_info_id=1; id_hidden=true; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); })),
            [Arg(L(String(("a", ())))); Arg(L(String(("bcdef", ()))))]))]), ())])
```
The `abcdef` should be parsed as a single string, not two.
