### ISSUE TITLE
100% CPU for >30 seconds with no output in Docker after running config auto

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#5257]
Something seems broken about --config=auto when running in Docker

```
$ docker pull returntocorp/semgrep:latest 
--> (sha256:e99bcc36da6827858d8d5e1952f59a4246aacf4e91bfe6a5de98c8d409408128)
$ docker run returntocorp/semgrep semgrep semgrep scan --config auto

Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on
your languages and frameworks.
Fetching rules from https://semgrep.dev/registry ...
```

It takes >45 seconds after this line for the next output. Looking at the docker host, network use is 0 and CPU is 100%.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1363/100percent-cpu-for-30-seconds-with-no-output-in-docker-after-running. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
![Untitled-1](https://user-images.githubusercontent.com/1060436/169147222-54c24f8d-e3e3-49b2-8c90-14634fb606b2.png)

I just ran `--config auto` with a profiler (outside Docker) and it took 25 seconds until semgrep-core is first called. Major opportunities for speedup:
- `rule_without_metadata` spends 7 seconds on deepcopy calls
- `parse_yaml_preserve_spans` takes 15 seconds

**Comment by underyx** [comment]
## `rule_without_metadata` spends 7 seconds on deepcopy calls

This one is a very easy fix. The deepcopy is totally unnecessary, we're just trying to compare the dict without `metadata` in it. I've done this locally and runtime is down to 17 seconds.

## `parse_yaml_preserve_spans` takes 15 seconds

More difficult. My first thoughts:

- we could very well be using JSON for communication with the app, which is easier to parse
- PyYAML is faster than ruamel.yaml and maybe we can switch
- ruamel.yaml has a faster C loader that we should make sure to install in our docker image

**Comment by underyx** [comment]
Update on `parse_yaml_preserve_spans` takes 15 seconds. We run the YAML parser three times:

1. loading settings.yaml
2. loading the rule schema
3. loading the rule contents

The first one is a one or two line file; let's not worry about that one.

I timed the second one on my M1 macbook pro with python 3.10 — 82ms to load the schema with our YAML loader, 0.6ms to load the same thing with the stdlib JSON module. Not a huge gain but I also see no reason to use YAML for our jsonschema definition.

This also implies that the speedup is around 100x if we switch to JSON, which means the 15s of rule parsing would turn into 150ms.

**Comment by underyx** [comment]
Update on `parse_yaml_preserve_spans` takes 15 seconds: fixed this in https://github.com/returntocorp/semgrep/pull/5261.

The profiling run that previously took 25 seconds now takes 2 seconds!

**Comment by underyx** [comment]
Full `semgrep scan --config auto` scan on the `semgrep` repo:

- Before today's perf PRs: 25.1s
- After: 14.3s

The remaining 14.3s is broken down like this:

- 0.5s waiting to download rules from registry
- 8.8s waiting for semgrep-core to return results
- 0.5s loading per-rule per-target timing data that won't be shown anyway
- 0.6s writing verbose skip logs that will be hidden anyway
- 2.4s for POST to metrics.semgrep.dev
- 1.5s unaccounted for

**Comment by underyx** [comment]
## Performance report

These are timings from running `--config auto` on `semgrep/semgrep/semgrep`

✅ - fixed in a PR
🚧 - fix should work but doesn't for some reason 😠

|                    | Step                               | Time | Time (%) |
|--------------------|------------------------------------|------|----------|
|         | import python modules              | 0.5s | 1.3%     |
| :construction:     | rule download                      | 0.8s | 2.1%     |
| :white_check_mark: | rule yaml parsing                  | 15s  | 39.5%    |
| :white_check_mark: | rule_without_metadata deepcopy     | 7s   | 18.4%    |
| :white_check_mark: | dumping rule yaml to pass to core  | 3.9s | 10.3%    |
|           | semgrep-core returns results       | 9.5s | 25%      |
| :white_check_mark: | initializing empty timing matrix   | 0.5s | 1.3%     |
| :white_check_mark: | verbose skip logging into the void | 0.6s | 1.5%     |
|           | unaccounted overhead               | 0.2s | 0.5%     |

Excluded the metrics request because results are already visible while waiting for that.

**Comment by aryx** [comment]
Very nice!

**Comment by underyx** [comment]
Found a new performance sink: now that I'm testing in a repo with `.semgrepignore` I found that the semgrepignore logic took 33% of execution — 12 seconds of 36 seconds.

Turns out we were running expensive path calculation operations once for each target for each ignore pattern. Pre-calculating these path ops before looping through the ignore patterns cut this from 12 seconds to 3 seconds.

But I think many of these path operations might be unnecessary anyway.

**Comment by underyx** [comment]
Even better: By removing the `:include .gitignore` line from the default semgrepignore file, we can skip a toooon of unnecessary file ignoring logic. After all, we are already using `git ls-files` to get the file list, so none of those possibly hundreds of patterns can match anything.

**Comment by underyx** [comment]
Changes broken down commit-by-commit, tested with this script:

```python
#!/usr/bin/env python
import sys
import os
import time
import subprocess

subprocess.call(["git", "checkout", sys.argv[1]])
for i in range(int(sys.argv[2])):
    print(
        subprocess.check_output(["git", "show", "--summary", "--oneline"])
        .decode()
        .strip(),
        end=", ",
    )
    s = time.time()
    subprocess.call(
        ["semgrep", "--config=p/default", "--metrics=off"],
        env={**os.environ, "SEMGREP_APP_URL": "https://bence.dev.semgrep.dev"},
    )
    print(time.time() - s)
    subprocess.call(["git", "checkout", "HEAD^"])
```

## First run

| message                                                                   | time (s) | step Δs | step Δ% | total Δs | total Δ% |
|---------------------------------------------------------------------------|------------:|---------------:|---------------:|----------------:|----------------:|
| perf: Request registry rules as JSON instead of YAML                      |      20.658 |         -7.598 |        -15.68% |         -27.787 |         -57.36% |
| perf: Cache registry responses                                            |      28.255 |          1.554 |          3.21% |         -20.189 |         -41.67% |
| perf: Pass rules to core as JSON                                          |      26.702 |         -2.047 |         -4.23% |         -21.743 |         -44.88% |
| perf: Pre-calculate set of all files once                                 |      28.748 |          0.056 |          0.12% |         -19.696 |         -40.66% |
| perf: Cache per-rule glob filtering                                       |      28.692 |         -1.848 |         -3.82% |         -19.752 |         -40.77% |
| perf: Cache FileIgnore.filter_paths                                       |      30.541 |          0.518 |          1.07% |         -17.904 |         -36.96% |
| perf: Cache _executes_with_shebang                                        |      30.023 |         -1.464 |         -3.02% |         -18.422 |         -38.03% |
| perf: Cache fileignore survives results                                   |      31.486 |          0.698 |          1.44% |         -16.958 |         -35.01% |
| perf: Make semgrepignore faster                                           |      30.788 |         -9.149 |        -18.89% |         -17.656 |         -36.45% |
| perf: Reduce metrics retries by using default timeout                     |      39.937 |         -0.637 |         -1.31% |          -8.508 |         -17.56% |
| perf: Skip creating large empty timing dicts                              |      40.574 |         -3.337 |         -6.89% |          -7.871 |         -16.25% |
| perf: Skip logging skips when not set to verbose                          |      43.911 |         -4.194 |         -8.66% |          -4.534 |          -9.36% |
| perf: Speed up rule deduplication (#5258)                                 |      48.105 |         -0.339 |         -0.70% |          -0.339 |          -0.70% |
| develop |      48.445 |                |                |           0.000 |           0.00% |

## Second run

| message                                               | time (s) | step Δs | step Δ% | total Δs | total Δ% |
|-------------------------------------------------------|---------:|--------:|--------:|---------:|---------:|
| perf: Request registry rules as JSON instead of YAML  |   22.536 |  -8.600 | -15.64% |  -32.462 |  -59.02% |
| perf: Cache registry responses                        |   31.135 |   2.823 |   5.13% |  -23.862 |  -43.39% |
| perf: Pass rules to core as JSON                      |   28.312 |  -2.487 |  -4.52% |  -26.685 |  -48.52% |
| perf: Pre-calculate set of all files once             |   30.799 |   0.202 |   0.37% |  -24.198 |  -44.00% |
| perf: Cache per-rule glob filtering                   |   30.597 |  -1.767 |  -3.21% |  -24.400 |  -44.37% |
| perf: Cache FileIgnore.filter_paths                   |   32.364 |   1.824 |   3.32% |  -22.633 |  -41.15% |
| perf: Cache _executes_with_shebang                    |   30.540 |  -1.670 |  -3.04% |  -24.457 |  -44.47% |
| perf: Cache fileignore survives results               |   32.210 |   0.547 |   1.00% |  -22.787 |  -41.43% |
| perf: Make semgrepignore faster                       |   31.662 | -10.430 | -18.96% |  -23.335 |  -42.43% |
| perf: Reduce metrics retries by using default timeout |   42.092 |   3.444 |   6.26% |  -12.905 |  -23.46% |
| perf: Skip creating large empty timing dicts          |   38.649 |  -5.256 |  -9.56% |  -16.348 |  -29.73% |
| perf: Skip logging skips when not set to verbose      |   43.905 | -10.834 | -19.70% |  -11.092 |  -20.17% |
| perf: Speed up rule deduplication (#5258)             |   54.739 |  -0.258 |  -0.47% |   -0.258 |   -0.47% |
| develop                                               |   54.997 |         |         |    0.000 |    0.00% |

Two consecutive runs with the same code can differ by up 2 seconds from just noise in the measurement.

I also reordered the three commits that appear to cause a slowdown (excluding the request caching one) to the tip of the branch and found that they each cause slight speedups then. So these ones seem to cause a speedup only when applied in combination with other commits, but not in isolation.

**Comment by aryx** [comment]
Very nice bench report. Awesome job bence.

**Comment by emjin** [comment]
Yaaaay thank you so much! This has been annoying me for a while, big quality of life improvement

**Comment by underyx** [comment]
I'll say this is good enough now.
