### ISSUE TITLE
Using Semgrep in pattern mode (`-e`) can result in integer overflows in semgrep-core

### ISSUE THREAD

**Issue by spencerdrak** [semgrep/semgrep#5289]
**Describe the bug**

When using a large integer such as `1151234590987029384721` for the pattern to match, semgrep-core will experience an integer overflow and being matching any patterns that have a `-1` in them.

**To Reproduce**

```
$ cat ./test/test.go 
package main

import "fmt"

func main() {
        fmt.Println(-1)
}

$ semgrep -e 1151234590987029384721 -l go ./test/ 
Scanning 1 file.

Findings:

  test/test.go 
          6┆ fmt.Println(-1)

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 1 rule on 1 file: 1 finding.
```

**Expected behavior**
The expected behavior is that no matches will occur.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
A local build. 

**Use case**
Not much - reporting here for reference later, in case someone ever needs to scan for a large number or something of the like.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1373/using-semgrep-in-pattern-mode-e-can-result-in-integer-overflows-in. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
https://github.com/returntocorp/semgrep/blob/71e42e138c83e6c3bd370ee41e618900300faacb/semgrep-core/src/parsing/Parse_rule.ml#L137

This line seems to be the issue---`Float.is_integer` seems to check if the number has no fractional part, not if the `float` can fit in an `int`, so `Float.to_int` might get called with an out-of-range value and return an unspecified value.

For whatever reason I can reproduce this on v0.93.0 but not later versions.

**Comment by akuhlens** [comment]
This example now works correctly due to changes in the code base. It is worth noting that similar bugs still likely exists at multiple places in semgrep as of now:

https://github.com/returntocorp/semgrep/blob/15f075bd265773069ab6b8501e04c215b2ac0fb3/src/parsing/Parse_rule.ml#L354
https://github.com/returntocorp/semgrep/blob/15f075bd265773069ab6b8501e04c215b2ac0fb3/libs/commons/JSON.ml#L24
https://github.com/returntocorp/semgrep/blob/15f075bd265773069ab6b8501e04c215b2ac0fb3/libs/ojsonnet/Eval_jsonnet.ml#L189
