### ISSUE TITLE
Eliminate Blank nodes to unblock progress on C and C++ support

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5374]
See https://github.com/returntocorp/ocaml-tree-sitter-core/issues/38

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1403/eliminate-blank-nodes-to-unblock-progress-on-c-and-c-support. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
So you want to modify the original tree-sitter grammar? There is no alternative solution?

The problem is that we need to modify the tree-sitter-c one, and then use that in tree-sitter-cpp, and that means
we would need to update to the last tree-sitter-cpp which changed a lot since the last time we generated semgrep-cpp, so
it will be a big refactoring to Parse_cpp_tree_sitter.ml (not that we should not do it; just that it's gonna be lots of work).

**Comment by mjambon** [comment]
> So you want to modify the original tree-sitter grammar?

I'm not sure what you mean by that. I want to modify the pipeline that converts the original grammar into something we can use from OCaml. The modification will result in having normal token nodes instead of those Blank nodes that shouldn't exist.

There's already a bunch of `token()` constructs that were moved into their own rule so they can get a name. These will keep the same name, although it will be through an `alias()`. These names won't change, so the generated types will stay the same and there won't be a need to change anything in the existing boilerplate except for the few places where we had Blanks.

**Comment by aryx** [comment]
ah ok perfect!

**Comment by aryx** [comment]
Why did you create the issue here and not in ocaml-tree-sitter-core?

**Comment by mjambon** [comment]
The issue was created in ocaml-tree-sitter-core. I wanted to have it here to make it easier to track and didn't want to create a Linear-only task.
