### ISSUE TITLE
Deep Expression Operator reports duplicate findings

### ISSUE THREAD

**Issue by ajbt200128** [semgrep/semgrep#5657]
**Describe the bug**
If I use the deep expression operator, it will create two findings when one is expected

**To Reproduce**
[Steps to reproduce the behavior](https://semgrep.dev/s/jA2D)

**Expected behavior**
Only one finding to be created, specifically matching `user.is_admin()`

**Screenshots**
<img width="510" alt="Screen Shot 2022-06-29 at 1 31 21 PM" src="https://user-images.githubusercontent.com/14303434/176539160-97857861-e50a-43e1-9e5f-d026487a4945.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1584/deep-expression-operator-reports-duplicate-findings. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
You don't need deep expressions for this: https://semgrep.dev/s/JO9d

The reason you get two matches is because `<... $USER.is_admin() ...>` matches both: `user.authenticated() and user.is_admin() and user.has_group(gid)` AND `user.is_admin()`. They are not duplicates.

In fact you shouldn't use deep expressions at all here! Precisely because `<... $USER.is_admin() ...>` will match the whole `user.authenticated() and user.is_admin() and user.has_group(gid)`. Otherwise you will be replacing that entire expression with `user.is_not_admin()`. Try the old playground and apply the autofix and you should see this.

I do _not_ think this is a bug.

**Comment by IagoAbal** [comment]
Closing this issue because it looks like a non-issue. But feel welcome to reopen if you have any objections!
