### ISSUE TITLE
semgrep lint cannot read rules under directories that start with a . (dot)

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#573]
**Describe the bug**
Due to this https://github.com/returntocorp/semgrep/blob/bf3f33bf851402cc708ed7500188b342236a7e8b/semgrep/semgrep/config_resolver.py#L131

Rule file directories that starts with a `.` are skipped.

I am using tox to run tests. 
semgrep rules are loaded from 

`/***/njsscan/.tox/py37/lib/python3.7/site-packages/njsscan/rules/semantic_grep`

semgrep won't load the rules due to `.tox` in path.

**To Reproduce**
https://github.com/ajinabraham/njsscan/runs/614300110?check_suite_focus=true#step:7:49

**Expected behavior**
Should not complain about directories that starts with a `.` if they are explicitly specified.

**Screenshots**
Can provide on request

**Environment**
experimental branch

**Comment by DrewDennison** [comment]
hey @ajinabraham believe it or not this was a design choice because I was trying to avoid yaml parse errors from `.github`, `.circleci` etc which all have yaml files. The logic lives in https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/config_resolver.py#L134 I remember putting an escape hatch so if it's `.semgrep` or `.tox-semgrep` it should work but happy to accept PR or I'll add this to our backlog to do in the next release.

**Comment by ajinabraham** [comment]
Make sense. I think I can control tox dir. Let me try that and will update here.

**Comment by DrewDennison** [comment]
cool. It's still a good bug to support hidden files/folders especially if it's an explicitly passed in path

**Comment by ajinabraham** [comment]
I tried this as a work around for now
```
[tox]
toxworkdir=.tox-semgrep
```

**Comment by nbrahms** [comment]
Hi @ajinabraham ... should be fixed in develop mainline now, and in next release. Thanks for spotting it!
