### ISSUE TITLE
alternative apostraphe character: ’ can not be ignored and will show up in single character findings

### ISSUE THREAD

**Issue by DanielDiCarlo** [semgrep/semgrep#5952]
**Describe the bug**
I am currently attempting to write a rule that detects single characters that are not standard a-z 123 or commonly used symbols in programming. However, I would also like for the symbol ’ to not show up as a finding. Even if I mark it as a a pattern-not it will still appear in the findings section.

**To Reproduce**
https://semgrep.dev/playground/s/gAZR

**Use case**
What will fixing this bug enable for you?
I will be able to implement a rule at my company that produces no false positives and will not have to write a python script to accomplish this task.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1797/alternative-apostraphe-character-can-not-be-ignored-and-will-show-up. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
Hello! The solution here is to use `pattern-not-regex` rather than `pattern-not`. It also helps to specify the language in the `languages` section as `regex` rather than `generic`. An updated rule is https://semgrep.dev/s/RLdq

Explanations:
* `generic` means that patterns are for matching in generic mode. This is the matching engine used for patterns specified with `pattern-not` or `pattern`.
* specifying `regex` as the "language" is a little better because we get an error if we try to use `pattern-not` with it when we mean `pattern-not-regex`.
* the generic mode normally supports matching single utf-8 characters. The problem here is that it determines that the input doesn't look like source code and refuses to scan it. This is based on some undocumented heuristic and is intended for only scanning source code like a human would write. It's useful when scanning a file tree indiscriminately as it saves time and avoids noisy matches (in binary files or minified code). Here, it's a bit counterproductive. Maybe a warning would be helpful.

Please let us know if you think of ways to avoid these issues in the future.
