### ISSUE TITLE
Instance method of internal class can not be matched

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6001]
**To Reproduce**
https://semgrep.dev/s/x5by

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1827/instance-method-of-internal-class-can-not-be-matched. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Another example where typed metavariable doesn't match despite all the info is available: https://semgrep.dev/s/PLqN

**Comment by emjin** [comment]
Fixed in develop; will go out in the next release (probably next Tuesday). Your example will work, but I believe on line 7 instead of `Object m = new Hello.internalB().t()` you meant this to be `Object m = new Hello.internalB.t()`. To match that, I think the better pattern is `new world.Hello.internalB.t()`

You can see your original rule working on develop https://semgrep.dev/playground/s/x5by?develop=true, or my suggestion here https://semgrep.dev/playground/s/returntocorp:internal_class_instance_call-copy?develop=true!

**Comment by backcover7** [comment]
@emjin Yes. You're correct. The only difference between the two rules is the instance function call and static function call.
And can we match this case now?

> Another example where typed metavariable doesn't match despite all the info is available: https://semgrep.dev/s/PLqN

**Comment by emjin** [comment]
> And can we match this case now?

This one requires more inference than Semgrep currently does. We don't keep around the current package of a file because in most cases, if you only can look at one file at a time, it's not useful. We _do_ do that in DeepSemgrep, the proprietary multi-file extension of Semgrep, however. In general would love to hear more about your use case.

**Comment by backcover7** [comment]
> > And can we match this case now?
> 
> 
> 
> This one requires more inference than Semgrep currently does. We don't keep around the current package of a file because in most cases, if you only can look at one file at a time, it's not useful. We _do_ do that in DeepSemgrep, the proprietary multi-file extension of Semgrep, however. In general would love to hear more about your use case.

So are you saying the package based rule works in deepsemgrep mode?

**Comment by emjin** [comment]
I believe so. If it doesn't, it's something we should fix.
