### ISSUE TITLE
`semgrep --pattern "foo"` should infer search language from current directory

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#6331]
**Is your feature request related to a problem? Please describe.**

See https://news.ycombinator.com/item?id=33240839

**Describe the solution you'd like**

I think Semgrep should:
1. Walk the targets
2. Recognize all the in the targets by file extension
3. Set those languages (plus generic?) in the rule YAML generated from the CLI supplied pattern
4. Ignore any parse errors if at least one language ran without parse errors?

**Describe alternatives you've considered**

**Use case**

**Additional context**

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-2019/semgrep-pattern-foo-should-infer-search-language-from-current. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Maybe we could try to infer a set of potential languages from the pattern. We could try parse the pattern with every language, and collect the list of languages for which the pattern is valid. But you may end up scanning _too much_ and having a worse experience (longer runtime, more noise).

If the problem is verbosity (that's what @lbhdc seems to have complained about originally?), one must note that you can write `semgrep -l py -e foo(...)` instead. I don't see a problem with some users defining an alias  for Semgrep if that makes their life easier.
