### ISSUE TITLE
Special annotation class match

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6372]
**Describe the bug**
The special annotation class cannot be parsed correctly in semgrep.

**To Reproduce**
https://semgrep.dev/s/gg0Z

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by mjambon** [comment]
The following pattern is parsed without an error:
```
public @interface $Y {...}
```
What fails is:
```
public @$X $Y {...}
```
My understanding of Java is that `@interface` placed in this position is a keyword similar to `class` or `interface`. It can't be any string like an annotation. For example, the following is illegal syntax because `@something` isn't valid in this position:
```
public @something $Y {...}
```
I believe that's why we don't support the metavariable syntax `$X` in `public @$X Foo {}`. In your example, I would use the pattern `public @interface $Y {...}`. Are there cases where this doesn't match what you want?

**Comment by backcover7** [comment]
@mjambon I rechecked again and agree with you. I think this is not a bug anymore. Please close it if you want.
