### ISSUE TITLE
support string and variable concatenation with + ... 

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#656]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to match in python:

```python

foo2 = bar + "baz" + f"{FOOBAR}FOO" + bar
```

and I tried using 

```
$X = $Y + "..." + ...
```

**Describe the solution you'd like**
The ellipsis operator, `...` should match 0 or more sequences of string concats

https://semgrep.live/4Z7

@ajinabraham also requested this feature for JS

**Comment by DrewDennison** [comment]
> Can a rule like `var $X = "=~/.*http[s]*:///" + $REQ.host + ...;` or something similar be supported for strings?

**Comment by mschwager** [comment]
If we add this, don't forget to update the docs: https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#ellipsis-operator

**Comment by aryx** [comment]
It's because of the associativity of +, it's left associative so matching
$X = 1 + 2 + ...
against
foo = 1 + 2 + 3 + 4
will try to match
$X = (1+2)+ ...
against
foo=((1+2) + 3) + 4

Note that you can also use the deep ellipsis operator to solve your problem.
$X = <... 1 + 2 ...> would match foo = 1 + 2 + 3  + 4.

**Comment by ajinabraham** [comment]
Sweet!
