### ISSUE TITLE
Can't match only if statements with else blocks in python

### ISSUE THREAD

**Issue by ndavison** [semgrep/semgrep#669]
Hi,

I'm not sure if this is a bug or I'm just doing it wrong, but I was trying to use semgrep to find instances in python code where a value is being checked in an if statement with an `else:` block:

https://semgrep.live/0OW

This seems to match the if statement without an else block. FYI if the pattern and code is changed to use an `elif` instead, that seems to work fine:

https://semgrep.live/WEj

**Comment by ievans** [comment]
Thanks for the bug report @ndavison ! I agree, this is a bug.

Specifically:
```
        if request_method == $X:
          $S
        else:
          $Z
```

should not match 

```
def a():
    if request_method == 'GET':
        x = 1
```

@aryx it looks like the `...` operator in the iff block is overly greedy in this case? I tried a tweak to prove whether or not that is the issue, and ran into another bug: https://github.com/returntocorp/semgrep/issues/670

**Comment by aryx** [comment]
It's because of the way ifs are internally translated. the generic AST does not make the difference between
if (1) { foo(); } else { }
and
if(1) { foo(); }
In both cases the generic AST will see If (Int 1,  Block [Call foo], Block []).
It does not know whether a else was given in the pattern.
This has some advantages, but maybe it's better to change the If and remember if there was an else or not.

**Comment by nbrahms** [comment]
At the very least it seems that https://semgrep.live/kxbX should work for this use case
