### ISSUE TITLE
Constant propagation at top level with arithmetic not working

### ISSUE THREAD

**Issue by agamm** [semgrep/semgrep#6759]
**Describe the bug**
A basic usage of two variables in a function parameter are not detected.

**To Reproduce**
https://semgrep.dev/s/PNyp

**Expected behavior**
It should find the print (one match).

**Screenshots**
--

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
--

**Use case**
Write a post about semgrep on https://unzip.dev

**Comment by nmote** [comment]
It looks like you're expecting Semgrep to evaluate simple arithmetic expressions. This would be a cool feature, but I'd be surprised if it ended up being something that we prioritized in the near future.

**Comment by agamm** [comment]
(Sorry if this isn't relevant here, I can delete) Do you have a simple example I can share with readers so they will comprehend the usage and value quickly?

**Comment by nmote** [comment]
I dug in a bit more, and it turns out that Semgrep does in fact evaluate simple arithmetic as part of constant propagation. The issue here was that it wasn't performing constant propagation at the top level, which was addressed in #6712 but was not released to the playground until recently. You'll find that the example you gave works as you expect now.
