### ISSUE TITLE
Document how to run semgrep ci on PRs for workflow_dispatch GitHub event

### ISSUE THREAD

**Issue by nwalsh1995** [semgrep/semgrep#7278]
**Is your feature request related to a problem? Please describe.**
I want to test my semgrep ci run on a pull request via the GitHub workflow_dispatch action. I want exactly the same behavior as if the event was triggered by the `pull_request` GitHub event, except that I can point it to different PR numbers via Github Action inputs.

This allows me to change my semgrep configuration in a branch and test it on other existing PRs without having to commit the configuration file.
The workflow dispatch will need to include the PR number and probably look like this: 

![image](https://user-images.githubusercontent.com/1879632/222816319-627d930a-ffdb-43b8-8c67-892642ca76ca.png)

Because there is special internal logic detailing how `semgrep ci` runs on `pull_request` events internally, I'm not sure the proper settings to make `semgrep ci` work equivalently on `workflow_dispatch` events as it does on `pull_request` events.

**Describe the solution you'd like**
Semgrep provides example configurations for `semgrep ci` to run in a GitHub actions that are triggered via the `pull_request` or `push` events [here](https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#sample-github-actions-configuration-file). Provide another tab for workflow dispatch, or include the `workflow_dispatch` configuration in these files.

**Describe alternatives you've considered**
Using [act](https://github.com/nektos/act) to run GitHub action locally and checkout out the PRs myself. Emulates GitHub action but does not actually run the action on GitHub.

I tried to create this manually but ran into a lot of issues due to the internals of how `semgrep ci` handles `pull_request` event differently. For instance I think we need to set `SEMGREP_BASELINE_REF` and potentially other configuration options.

**Use case**
Quicker iteration on semgrep workflow files and a simple way to test the workflow end-to-end without having to commit into the main branch of the repository.

**Comment by underyx** [comment]
As a first thought, this sounds difficult to do, because GitHub prepares a special git state simulating the result of merging a given PR only when the pull_request event is used. Without GitHub's special handling of those events, the simulations is gonna be imperfect. So as workarounds, I have these two ideas:

1. You could set up an `on: pull_request` job that fires only when e.g. a specific dummy semgrep team's review is requested, or when a special label is added. This kinda lets you trigger Semgrep scans manually while still keeping the event as `pull_request`.
2. You could get very close to the PR behavior by running this command: `semgrep ci --baseline-commit $(git merge-base your-default-branch-name)`
