### ISSUE TITLE
Problems in high sierra - Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by javixeneize** [semgrep/semgrep#735]
Hi

I have installed the package using brew in my high sierra (10.13.6) and im having this error when running semgrep

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

Any idea what might be the problem? I have cmake installed

Thanks

**Comment by rcoh** [comment]
Hi @javixeneize -- the issue seems to be that binaries compiled on 10.15 are incompatible with 10.13. The binaries in our brew tap are compiled using Github actions which only supports 10.15.

Can you try using our homebrew core package? Homebrew builds it on 10.13 natively so it should work for you:

```
brew uninstall semgrep
brew install semgrep
```
(This is brand new so we haven't added it to the docs yet)

**Comment by javixeneize** [comment]
Hi

I know whats the problem now. Brew installs python 3.8 as its a requirement for semgrep but it does not activate it, so i was still using semgrep with python 3.6.5. It is fixed now but maybe this can be added to the documentation/throubleshooting

**Comment by aryx** [comment]
seems to be fixed.
