### ISSUE TITLE
Semgrep PostMessage Detection

### ISSUE THREAD

**Issue by InitRoot** [semgrep/semgrep#810]
**Describe the bug**
I'm trying to find url parameters in all postMessage javascript code. To learn the syntax of semgrep I'm only looking for url, and have no idea how to include the postMessage logic. At the moment if I'm trying simple code it works, however, using more complex js files it doesn't detect the url.

**To Reproduce**
It works on the below link using a very simple version of code as a test:
https://semgrep.live/r5e

Now I've randomly went to a site and then copied their JS files and added the URL statement into it. The test however fails on this example. I would have hoped it matches line 162.
https://semgrep.live/NAy

Would have hoped the below gets detected. 
![image](https://user-images.githubusercontent.com/954507/82553953-4c295200-9b65-11ea-9538-708dc1cd179c.png)

**Expected behavior**
At the moment the above has no logic to look for PostMessage first, as a start and to learn the syntax I'm only looking to see the urls. If anyone can share examples on how to achieve please do.

**Comment by ievans** [comment]
Hi @InitRoot, thanks for opening an issue! 

There are two issues here: one is that your pattern is specifying a function call $F with a single argument, but line 162 is actually a function call with two arguments: $F({ ... }, "*"). So the correct pattern is `$F({ url: ... }, ...)`

In fact this is a UX problem. The default timeout for parsing javascript files is about 5 seconds, and due to a prior bug #520 these patterns are exceeding that timeout. The semgrep.live editor isn't showing you this -- I'm going to file a bug for that. If you slightly decrease the size of the file and use the pattern with a ... to handle the second argument, it works just. See https://semgrep.live/Zpw

**Comment by ievans** [comment]
Closed in favor of #811 and #812. Thanks again @InitRoot for the report, we'll queue this up for fix!

**Comment by ievans** [comment]
@InitRoot following up here: we actually shipped a bunch of perf improvements in v0.10 that makes this no longer timeout, and we updated the logic so that timeouts are properly reported as errors.
