### ISSUE TITLE
Error parsing variable arguments with ellipsis operator

### ISSUE THREAD

**Issue by ricsirigu** [semgrep/semgrep#818]
**Describe the bug**
I'm trying to catch this kind of SQL injection 

```java
    public class Test{
        public List<Msg> findMsg(String userId, String idTest, String typeId) {
            StringBuilder sql = new StringBuilder();
            
            sql.append("SELECT * X in (" + userId + ") "+  idTest + " " +typeId+ " ORDER BY 1 ");

            return findMsg(sql,true);

        }
    }
```

You can find the rule in the following link

**To Reproduce**
https://semgrep.live/JLW

**Expected behavior**
A rule correctly parsed that catches a SQLi with variable arguments

**Comment by dlukeomalley** [comment]
Thank you for filing this @ricsirigu. I have this queued up to investigate this morning.

**Comment by dlukeomalley** [comment]
@ricsirigu, I was able to get your pattern working [here](https://semgrep.live/D7o), more details below!

I initially got the pattern compiling by adding quotes around the `...` to denote string literals:

```
$SQL.append("..." + $PARAM + "...");
```

String matching like this can be problematic because it won't catch variations like the following:

```
"foo" + $PARAM
$PARAM + "bar"
$PARAM
```

To get around this, we have a special syntax that says "if $PARAM appears anywhere" in a statement:

```
$SQL.append(<... $PARAM ...>);
```

Here is the pattern with the "appears anywhere" syntax used: https://semgrep.live/D7o

Is there a more specific SQL related method you could use for detection? With this pattern I'm worried you'll detect any use of a string builder that gets use in a later method invocation.

**Comment by mschwager** [comment]
Hi there @ricsirigu,

It seems that there are two questions in play here: 1.) how can I fix this parse error from happening on my rule? and 2.) how can I detect SQL injection? It looks like @dlukeomalley has answered the first question. Regarding the second question, we also have a pre-built `semgrep` rule for detecting SQL injection in Java.

* You can find it in our registry under `java.lang.security.audit.formatted-sql-string.formatted-sql-string`: https://semgrep.live/r?lang=java&sev=ERROR,WARNING,INFO&tag=security
* You can find the specific rule file here: https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/security/audit/formatted-sql-string.yaml

If that isn't exactly what you need you may be able to pull it down and modify it to fit your situation. Hope that's helpful :+1:

**Comment by ricsirigu** [comment]
@dlukeomalley @mschwager you guys are awesome! Thank you for your support


> Is there a more specific SQL related method you could use for detection? With this pattern I'm worried you'll detect any use of a string builder that gets use in a later method invocation.

Unfortunately not, but in the codebase that I'm analyzing its enough

**Comment by dlukeomalley** [comment]
Keep us posted if you run into any other issues @ricsirigu. We've also got a bunch of security engineers and pattern writers hanging out on [Slack](https://join.slack.com/t/r2c-community/shared_invite/enQtNjU0NDYzMjAwODY4LWE3NTg1MGNhYTAwMzk5ZGRhMjQ2MzVhNGJiZjI1ZWQ0NjQ2YWI4ZGY3OGViMGJjNzA4ODQ3MjEzOWExNjZlNTA).

Closing this ticket for now. In bocca al lupo 👍
