### ISSUE TITLE
Flow not parsed in react-coinbase-commerce

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#838]
semgrep fails to parse  https://github.com/coinbase/react-coinbase-commerce

**Comment by brendongo** [comment]
Parsing errors due to semgrep not supporting flow

**Comment by aryx** [comment]
We might switch that to a wontfix no?
Typescript is already hard to handle ... unless Facebook is ok to pay us a lot to support Flow (which I doubt they will).

**Comment by hexagonrecursion** [comment]
I encountered this as well when trying to apply semgrep to the mozilla repository https://hg.mozilla.org/mozilla-central/. Some files in it are using flow. It is not common though.

**Comment by hexagonrecursion** [comment]
Is there a reason you can't use the Babel parser?

> https://flow.org/en/docs/tools/babel/
> Flow and Babel are designed to work great together. It takes just a few steps to set them up together.

**Comment by hexagonrecursion** [comment]
I guess one possible workaround would be to replace the custom flow syntax with the comment-based one https://flow.org/en/docs/types/comments/.

**Comment by hexagonrecursion** [comment]
On the subject of the workaround: [noppa](https://github.com/noppa) has [pointed out to me](https://github.com/facebook/flow/issues/8524#issuecomment-724067454) that there is a tool that can automatically replace the custom flow syntax with the comment-based one https://babeljs.io/docs/en/babel-plugin-transform-flow-comments/

**Comment by aryx** [comment]
> Is there a reason you can't use the Babel parser?
> 
> > https://flow.org/en/docs/tools/babel/
> > Flow and Babel are designed to work great together. It takes just a few steps to set them up together.

We usually avoid to call pre-processors because we want to report bugs on the original source file, not on pre-processed code 
that may not maintain correct line information. If babel can maintain those line information, they you could indeed call babel first on the file and then run semgrep on it.
However, semgrep also has the autofix feature, and in that case we definitely want to modify the original source file, not the pre-processed one so in that case you may not be able to call babel.
