### ISSUE TITLE
Issue in Parsing Code Snippet having matched Pattern.

### ISSUE THREAD

**Issue by deepanshukhanna** [semgrep/semgrep#8420]
**Describe the bug**
Inconsistency in running semgrep rules on similar text-
I am using semgrep in detecting issues in code snippets. what i have seen is its behaviour is not consistent when the code snippet is not syntactically correct.

**To Reproduce**
Run on below rule-
rules:
  - id: ABC1001
    languages:
      - c#
      - js
      - java
    patterns:
      - pattern-either:
          - pattern: $P
      - metavariable-regex:
          metavariable: $P
          regex: ^("ABC08"|"ABC09"|)$
    
    message: ABC08 pattern detected!
    severity: ERROR
    options:
      generic_comment_style: c

1. If(test == "ABC08" - Parsing Error
2. If(test == "XYZ08" - No Detection as expected

**Expected behavior**
It should pass for both code snippets:
1. If(test == "ABC08" - Should be detected
2. If(test == "XYZ08" - No Detection as expected

**Screenshots**
![image](https://github.com/returntocorp/semgrep/assets/35728165/959221d5-e75c-4361-a517-5aad2aed0896)
![image](https://github.com/returntocorp/semgrep/assets/35728165/7fca0884-1dda-417f-9bd2-53ec6ab4b1bc)

**What is the priority of the bug to you?**
P1
- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
local build

**Use case**
I can use it in my project as it will be based on detection in code snippets not entire file

**Comment by nmote** [comment]
While we do attempt error recovery when parsing, some parsers can do this better than others. In general, you should not expect Semgrep to work well on syntactically invalid code.

You might be interested in generic mode for something like this, or perhaps if you know something about the code snippets you are analyzing, you could wrap them in additional text to before passing them to Semgrep so that they are syntactically valid programs.
