### ISSUE TITLE
Support chained option calls in a first class way

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#849]
calls to ```foo().option('a', bar).option('b', bar)``` can be made in any order. We need a better syntax for matching function calls in any order. Perhaps something like `foo().<... option(...) ...>` would work?

https://semgrep.live/w9Y

**Comment by mschwager** [comment]
This is somewhat similar to #744. Instead of chained method calls it references chained decorators and others. Basically I see the generalized need here as: 1.) a way to capture variadic statements (function arguments, method calls, decorators, etc) and 2.) gate findings from (1) on certain logic (i.e. do *all* of these statements meet certain criteria, do *any* of these statements meet certain criteria, etc).

**Comment by salecharohit** [comment]
This is indeed a very important feature that I would expect to see as now a days devs like to chain functions Example below
```            
Document doc = Jsoup.connect(url).timeout(3000).execute().parse();
```

In the above scenario I'd like to capture the connect and execute functions but it all depends on the implementation.

Something like Jsoup.connect(...)...execute(...) would be desirable to capture.
Also do let me know if there is any other way of catching the above code snippet.

**Comment by aryx** [comment]
Actually we now support ... in chained operations. See https://github.com/returntocorp/semgrep/issues/2208
It works for Java and Javascript right now.
