### ISSUE TITLE
Const-analysis to propagate more implicit constants in Go

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#882]
**Describe the bug**
I expect constants to propagate in Go so I could match on all 3 of the following lines:

```go
x := "str"
y := x
z := y
```
Pattern:

```yml
$VAR := "str"
```

https://semgrep.live/9AAk

**Comment by aryx** [comment]
only 'const' variable are propagated (easy way to know if it's safe to propagate because
with 'const' we know the variable is really a constant that nobody is gonna change).

To support your use-case would require a const-analysis, to detect places where the user could have put a 'const' keyword but didn't.

**Comment by dlukeomalley** [comment]
@aryx Upon inspection I misread the Go. You are correct, `:=` is not a const. I'll reply to the user who I was corresponding to about this and close this issue.
